storj/storj

go.mod
`vgo run cmd/storj/main.go` will now build and pull dependencies in correctly.
=> Fix go.mod to work with vgo

examples/eestream/serve-collected/main.go, examples/eestream/serve-pieces/main.go, examples/eestream/serve/main.go, examples/eestream/store/main.go, internal/pkg/readcloser/fatal.go, internal/pkg/readcloser/lazy.go, internal/pkg/readcloser/limit.go, internal/pkg/readcloser/multi.go, pkg/eestream/decode.go, pkg/eestream/pad.go, pkg/eestream/rs_test.go, pkg/eestream/secretbox_test.go, pkg/eestream/transform.go, pkg/ranger/content.go, pkg/ranger/http.go, pkg/ranger/http_test.go, pkg/ranger/reader.go, pkg/ranger/reader_test.go, pkg/ranger/readerat.go
This PR does the following:
- Implements the `HTTPRanger` type
- Updates the `ranger` and `eestream` libraries to use `io.ReadCloser` instead of `io.Reader`
- Extracts an internal package `/internal/pkg/readcloser` with ReadCloser helper types
- Provides CLI tools under `/examples/eestream` to demonstrate the usage of the `eestream` library with `HTTTRanger`.
=> HTTP Ranger

examples/eestream/serve-collected/main.go, pkg/eestream/decode.go
This is a 5x performance improvement for the eestream library when working with http rangers.
The issue was that the decoder retrieved the range readers sequentially, which in case of http ranger means 40 sequential GET requests to remote farmers. Reworking this operation to parallel execution significantly improves the waiting time for streaming start and seek operations.
My reference test scenario is streaming a 200 MB MKV video from AWS N.Virginia to Bulgaria (i.e. US - Europe latency).
The observed improvement is:
- Streaming begins after 10 seconds (was 45-50 seconds before)
- Seeking takes 3 seconds (was 15 seconds before)
The above number are in half in nn alternative test scenario for streaming the same video from AWS Frankfurt to Bulgaria (i.e. Western Europe - Eastern Europe …
=> Reduce network latency by initializing Rangers in parallel

internal/test/util.go, pkg/overlay/cache.go, pkg/overlay/cache_test.go, storage/redis/client.go
if you construct an error directly at package init time, you
won't get useful stack traces or anything. zeebo/errs expects that
you always construct an error (.New) when the error actually
happens. instead, you call Class at init time, then use (Class).Has
to test for error type membership.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/96)
=> internal/test: switch errors to error classes

pkg/eestream/rs_test.go, pkg/ranger/grpc_test.go, pkg/ranger/reader_test.go
I did a dumb mistake for some of the table tests, which made some of the test cases not being executed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/106)
=> Use continue instead of return in table tests

pkg/segment/segment.go
Populates the Metadata field in a pointer with the given metadata (bytes) containing encryption and streaming info.
Later for the segmentStore Get method, the metadata stored in the pointer should get returned in the Get method as part of the Meta struct:
```
type Meta struct {
Data []byte
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/142)
=> saves metadata to the pointer in segmentStore Put

cmd/captplanet/main.go, cmd/captplanet/run.go, cmd/captplanet/setup.go, cmd/gw/main.go, cmd/hc/main.go, pkg/process/exec_conf.go
also allows much more customization of services within captain planet,
such as reconfiguring the overlay service to use redis
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/178)
=> cmd/hc, cmd/gw, cmd/captplanet: simplify setup/run commands

pkg/ranger/content.go
* Added nil check for ResponseWriter.
* Modified scanEtag method to get rid of "{}|" char symbols.
* Replaced time check from time.IsZero() to isZeroTime(time) for additional corner case check.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/158)
=> Ranger refactoring

pkg/miniogw/config.go, pkg/storage/segments/peek.go, pkg/storage/segments/peek_test.go, pkg/storage/segments/store.go, pkg/storage/segments/store_test.go
So @kaloyan-raev and I decided that pointerdb does not have to change to accommodate S3 buckets. Instead, when the segment store receives a Put request (e.g. with path `l/my-bucket-name`) and an empty reader, it should put a pointer (of type INLINE) to pointerdb.
Before this PR, segment store does not support putting pointers of type inline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/162)
=> begins adding inline segment support for segmentstore

pkg/kademlia/bucket_test.go, pkg/kademlia/kademlia_test.go, pkg/kademlia/node_id_test.go, pkg/kademlia/routing.go, pkg/kademlia/routing_test.go, storage/redis/client_test.go
In order for test to work next changes should be made in coyle/kademlia package:
func (ht *HashTable) GetBuckets() [][]*NetworkNode {
buckets := ht.RoutingTable
nn := [][]*NetworkNode{}
//Initial length = 0, index outof bound exception
//nn := make([][]*NetworkNode, len(buckets)) or
for _, v := range buckets {
//before: nn[i] = nodesToNetworknodes(v)
nn = append(nn, nodesToNetworknodes(v))
}
return nn
}
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/154)
=> Testcoverage kademlia

pkg/piecestore/rpc/client/client.go
First step in resolving https://storjlabs.atlassian.net/browse/V3-208
If having small erasure shares (e.g. 20 bytes) the piece store client would send each of them in a separate gRPC message, which is not efficient.
This patch uses a bufio.Writer to group erasure shares up to 32 KB before sending them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/210)
=> Group erasure shares before sending them to storage nodes

pkg/miniogw/gateway-storj.go
Now as we have a utility function for properly closing io.Closers with logging of eventual errors, let's use it in the miniogw code too.
This path also fixes a bug in the GetObject where one of the deferred close is eclipsing the actual error that could occur during the download.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/239)
=> Use utils.LogClose for deferred closing in miniogw

pkg/miniogw/config.go
This PR does 2 things:
- Changes the gateway configuration, so instead of `stripe-size` we are now configuring the `erasure-share-size`.
- Increases the size of erasure shares from 20 to 1024 to mitigate the current performance issues with small erasure share sizes. When we improve the performance, we can reduce the default to a lower value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/241)
=> Configure erasure-share-size to 1024 bytes

pkg/miniogw/logging/logging.go, pkg/miniogw/logging/logging_test.go
We want the logging wrapper of miniogw to log only unexpected errors, but not any minio.* errors. The latter are usually created by our code as part of the expected workflow, e.g. BucketNotFound, BucketAlreadyExists, ObjectNotFound, etc.
So far we've added explicit checks in the logging wrapper for each of the expected minio errors, but this turned to be time consuming and error-prone.
It turns out that all minio errors related to the object layer extend the `minio.GenericError` type: https://github.com/minio/minio/blob/master/cmd/object-api-errors.go#L124
This patch will check if the returned error is convertible `minio.GenericError` and will avoid logging it if it is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Avoid logging any minio error in miniogw logging wrapper

pkg/overlay/cache.go, pkg/overlay/config_test.go, pkg/peertls/peertls.go, pkg/peertls/utils.go, pkg/pool/connection_pool_test.go, pkg/provider/certificate_authority.go, pkg/provider/identity.go, pkg/provider/provider.go, pkg/provider/utils.go, storage/redis/client.go
Fixes go1.11 vet warnings.
Cancel on WithTimeout must always be called to avoid memory leak:
```
pkg/provider/provider.go:73: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak
```
Range over non-copyable things:
```
pkg/pool/connection_pool_test.go:32: range var v copies lock: struct{pool pool.ConnectionPool; key string; expected pool.TestFoo; expectedError error} contains pool.ConnectionPool contains sync.RWMutex
pkg/pool/connection_pool_test.go:56: range var v copies lock: struct{pool pool.ConnectionPool; key string; value pool.TestFoo; expected pool.TestFoo; expectedError error} contains pool.ConnectionPool contains sync.RWMutex
pkg/pool/connection_pool_test.go:83: range var v copies lock: struct{pool pool.ConnectionPool; key …
```
=> all: fix govet warnings

pkg/miniogw/gateway-storj.go, pkg/miniogw/gateway-storj_test.go
Fixes  https://storjlabs.atlassian.net/browse/V3-256
The Minio Browser does not call GetObjectInfo when downloading files. It  calls directly GetObject with length = -1. Calling Ranger.Range with length = -1 fails with "negative length" error.
The fix is to check for `length == -1` in the GetObject method and calculate the correct length before calling Ranger.Range.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/264)
=> Fixes downloads in Minio Browser

pkg/peertls/peertls.go, pkg/peertls/peertls_test.go, pkg/peertls/utils.go, pkg/provider/cert_authority_test.go, pkg/provider/certificate_authority.go, pkg/provider/identity.go, pkg/provider/identity_test.go, pkg/provider/utils.go
+ fix `peertls.NewCert` public key issue
+ fix `peertls.verfiyChain` issue
+ fix identity dial option
+ rename `GenerateCA` to `NewCA` and `generateCAWorker` to `newCAWorker` for better consistency/convention
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/270)
=> Identity fixes+:

pkg/eestream/decode.go, pkg/eestream/encode.go, pkg/eestream/piecebuf.go, pkg/eestream/rs_test.go, pkg/eestream/stripe.go
This PR improves the decoding performance of the eestream: ~3.5x faster for 40% less CPU.
The main idea is to switch from using channels to fixed size buffers. The new logic is encapsulated in two new types: PieceBuffer and StripeReader.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/256)
=> Optimize DecodeReader performance

storage/redis/client.go
Redis SCAN may return same item multiple times, add a basic check to avoid issues with.
From https://redis.io/commands/scan#scan-guarantees
> A given element may be returned multiple times. It is up to the application to handle the case of duplicated elements, for example only using the returned elements in order to perform operations that are safe when re-applied multiple times.
Causes very infrequent failures such as  https://travis-ci.org/storj/storj/builds/425316540#L1971
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/318)
=> Fix Redis Iterators

pkg/storage/streams/EOFAwareLimitReader.go, pkg/storage/streams/store.go
For some reason the error doesn't propagate from `segments.Put`, so I added it into stream handling.
This should fix the IO problems when aborting the upload.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/326)
=> Abort trying to upload segments when reader fails

pkg/storage/streams/store.go
The stream store now uses lazy segment ranger. This will avoid eagerly setting up the connections to the pieces of all segments.
=> Lazy segment ranger

pkg/piecestore/pstore.go, pkg/piecestore/rpc/server/psdb/psdb.go, pkg/piecestore/rpc/server/psdb/psdb_test.go, pkg/piecestore/rpc/server/store.go
TTL database writes were originally before data had been saved and this would at the same time check if the id already exists. A second database write would occur after the data is stored to update the database to include the size of the data that has been stored
I created a function for checking if the id exists, and combined the size and id database writes to one function after storing the data
=> Limit to only 1 ttl database write when storing data on storage nodes

cmd/uplink/cmd/cp.go
Path Handling in Windows was broken.
Replaced filepath.Join with path.Join where necessary.
Commands are working now as expected.
=> Fix path handling

cmd/uplink/cmd/cp.go, examples/eestream/serve-collected/main.go, examples/eestream/serve/main.go, internal/pkg/readcloser/multi.go, pkg/eestream/crc_test.go, pkg/eestream/decode.go, pkg/eestream/pad.go, pkg/eestream/pad_test.go, pkg/eestream/rs_test.go, pkg/eestream/transform.go, pkg/eestream/transform_test.go, pkg/miniogw/gateway-storj.go, pkg/miniogw/gateway-storj_test.go, pkg/miniogw/objstore_mock_test.go, pkg/piecestore/pstore.go, pkg/piecestore/rpc/client/client.go, pkg/piecestore/rpc/client/pieceranger.go, pkg/piecestore/rpc/client/readerwriter.go, pkg/ranger/file.go, pkg/ranger/file_test.go, pkg/ranger/reader.go, pkg/ranger/reader_test.go, pkg/storage/buckets/prefixed.go, pkg/storage/ec/client.go, pkg/storage/ec/client_test.go, pkg/storage/ec/mocks/mock_client.go, pkg/storage/ec/psclient_mock_test.go, pkg/storage/objects/store.go, pkg/storage/segments/store.go, pkg/storage/streams/store.go
This change resolves the issue with accumulating connections when downloading or streaming a large file composed of many segments. The connections for a certain segment will be closed as soon as the last byte of the segment is read.
This is achieved by two main changes:
1. The connection is not closed by RangeCloser.Close() anymore, but by the ReadCloser.Close().
2. The MultiReadCloser is modified, so the Read method close the respective reader after reading the last byte from it.
=> ConcatRanger closes segment readers as soon as data is read

.travis.yml
This gets PR checks in travis back down to ~6 minutes. I toyed with some basic optimizations to get checks < 5 minutes, but they didn't buy much. @egonelbre has some good ideas about switching to go 1.11 and caching the modules instead of using the storj-vendor repo, but that's not in this PR.
=> Stop travis from making binaries for now

pkg/eestream/decode.go, pkg/eestream/stripe.go, pkg/piecestore/rpc/client/client.go, pkg/storage/ec/client.go, pkg/storage/ec/client_test.go, pkg/storage/ec/mocks/mock_client.go, pkg/storage/segments/store.go
Fixes https://storjlabs.atlassian.net/browse/V3-230
- ECClient.Put() now returns the list of nodes who successfully got a piece
- The Segment Store puts only these successful nodes into the segment's pointer
- ECClient.Get() and Delete() now tolerate `nil` nodes in the provided list of nodes. A `nil` node represents a piece number which is missing in the storage network, i.e. there is no node storing that piece.
=> Pointer stores only nodes with successfully uploaded pieces

examples/eestream/serve-collected/main.go, examples/eestream/serve/main.go, examples/eestream/store/main.go, pkg/eestream/decode.go, pkg/eestream/encode.go, pkg/eestream/mocks/mock_client.go, pkg/eestream/rs.go, pkg/eestream/rs_test.go, pkg/eestream/stripe.go, pkg/storage/ec/client.go, pkg/storage/segments/store.go, pkg/storage/segments/store_test.go
Renames the following methods of the ErasureScheme interface to make them clearer and avoid confusion:
- `EncodedBlockSize()` is renamed to `ErasureShareSize()`
- `DecodedBlockSize()` is renamed to `StripeSize()`
=> Rename: DecodedBlockSize>StripeSize, EncodedBlockSize>ErasureShareSize

go.mod, go.sum
After piecestore-cli and piecestore-client changes the urfave/cli dependency can be removed.
=> remove urfave/cli from dependencies

README.md
I believe we don't need this anymore since we have #351.
=> Remove multipart threshold config for AWS CLI

pkg/pointerdb/config.go, pkg/pointerdb/pointerdb.go
So it better reflects that we are comparing it against the remote segment size.
=> Rename MinInlineSegmentSize to MinRemoteSegmentSize

README.md
GCC is required for building our repo.
On Windows GCC is not available by default and needs to be added in order to build.
=> Include GCC Hint for Windows

pkg/storj/encryption.go, pkg/storj/metainfo.go, pkg/storj/node.go, pkg/storj/object.go, pkg/storj/path.go, pkg/storj/redundancy.go
This should contain the interfaces and types necessary to describe the metainfo database and information in it.
Currently in package `storj` since the other things will be moving, it's good to have this location as a stable place for interfaces and types used to wire things together.
=> metainfo database: add interfaces and types

pkg/eestream/encryption.go, pkg/pb/meta.pb.go, pkg/pb/meta.proto, pkg/storage/streams/store.go, pkg/storage/streams/store_test.go
We used to encrypt the random encryption key for the segment's content with a fixed nonce equal to the segment's index. But once an object is uploaded, it may be deleted and reuploaded, or just overwritten. This may lead to encrypting different random encryption keys with the same (key, nonce) pair, which would compromise the security.
This PR generates a new random nonce every time the random encryption key is encrypted. This random nonce is now kept together with the encrypted random encryption key in the segment's metadata.
This required a change in the stream meta protobuf. In addition, the protobuf is reorganized for easier encryption of the stream's metadata. This is related to #462. TODO comments are left where the metadata must be encrypted and decrypted.
=> Fix nonce reuse for encrypting the encryption key

pkg/overlay/cache_test.go
I somehow did something weird to my last PR, so I'm just making a new one.
https://storjlabs.atlassian.net/browse/V3-512
The goal was replace Sprintf's involving IP and port w/ net.JoinHostPort().
I searched various for '%s:%' and similar patterns. These were the only Sprintf instances I found.
=> use net.JoinHostPort

Makefile
This is mainly to increase reliability of Jenkins builds.
=> Use GOPROXY, if available

pkg/kademlia/kademlia.go, pkg/kademlia/routing.go, pkg/kademlia/routing_helpers_test.go, storage/boltdb/client.go, storage/boltdb/client_test.go
Use same boltdb for nbuckets and kbuckets.
=> Make kademlia use less file-descriptors

cmd/captplanet/setup.go, cmd/uplink/cmd/setup.go, pkg/miniogw/config.go, pkg/peertls/templates.go
New option for captplanet/uplink setup will use uplink identity key and cert to provide sample TLS certs for Minio GW.
Jira: V3-392
=> Option for generating sample TLS certs for Minio GW

pkg/peertls/peertls.go, pkg/peertls/peertls_test.go, pkg/peertls/templates.go, pkg/peertls/utils.go, pkg/provider/identity.go, pkg/provider/identity_test.go, pkg/provider/provider.go
Adds `--identity.peer-ca-whitelist-path` flag to the identity responsibility; If provided, responsibilities using that identity instance will only successfully verify peers whose identity leaf cert is signed by any of the certs in the file found at the whitelist path.
The CA whitelist is PEM-encoded just like other identity files (certs and keys) and can contain multiple cert blocks.
=> Wait-list gating

cmd/captplanet/run.go, pkg/datarepair/checker/config.go, pkg/datarepair/repairer/config.go, pkg/pointerdb/config.go
Adds the repairer and checker to `Satellite.Identity.Run`
Adds the PointerDB server to the context
=> Add repairer & checker to Satelite

cmd/uplink/cmd/mount.go
It looks that `filepath.Clean` is doing too many additional things and we need only to remove slash.
=> Uplink mount better prefix handling

scripts/test-captplanet.sh
At the moment this test has to fail cause master is broken but the old integration test didn't notice it.
Feel free to add more commits to fix all errors.
=> reproduce interval errors

pkg/kademlia/routing.go
This makes 100 node testplanet setup faster by 0.3s.
=> Disable debug logging for routing table

pkg/kademlia/routing.go, pkg/kademlia/routing_helpers.go, pkg/kademlia/routing_helpers_test.go
This makes testplanet setup with 100 nodes ~1.4s faster.
```
Before:
BenchmarkSortByXOR-8         300           4319301 ns/op
After:
BenchmarkSortByXOR-8        5000            356867 ns/op
```
=> Optimize sortByXOR

scripts/test-captplanet.sh
only GNU sed understands -i with no argument.
=> fix test-captplanet.sh script on MacOS/BSD

scripts/cert-gating.sh, scripts/utils.sh, scripts/waitlist/storj.sh, scripts/waitlist/user.sh
_NB: requires bash 4+_
[Write a script to automatically create identities for storage nodes on the waitlist](https://storjlabs.atlassian.net/browse/V3-548)
```
./scripts/waitlist/user.sh --help
./scripts/waitlist/user.sh batch --help
```
```bash
./scripts/waitlist/storj.sh new storj-alpha-main /path/to/storj-alpha-pems-output /path/to/storj-alpha-ca-whitelist
./scripts/waitlist/user.sh new /path/to/existing/storj-alpha-pems storj-alpha-main username@abc.example /path/to/user-pems-output
./scripts/waitlist/user.sh batch ./emails.txt /path/to/existing/storj-alpha-pems storj-alpha-main /path/to/user-pems-output
```
A user can then take their respective cert and key and use them for `--ca.cert-path` and `--ca.key-path` when generating an identity:
```bash
identity id new \
--ca.cert-path …
```
=> Waitlist script

pkg/miniogw/multipart.go
Fixes https://storjlabs.atlassian.net/browse/V3-493
If the client has slow connection to the storage nodes, some parts that are added to and waiting in the multipart stream may not be read before the socket read timeout on the AWS CLI side is hit. In this case AWS CLI will make another request for these parts, which will result in "Part X already exists" error in the Minio Gateway. The upload will be also broken because the readers of these obsolete parts is already closed.
The solution in this patch is to replace the reader for the reuploaded parts with the new one instead of returning the "Part X already exists" error.
=> Allow S3 clients to reupload stale parts

pkg/eestream/encode.go
Fixes https://storjlabs.atlassian.net/browse/V3-577
While uploading 1 TB failed at some point it fails with:
> successful puts (34) less than repair threshold (35)
All 61 connections (95 - 34) were closed due to slowness. This means that the logic for determining if a channel should be closed due to slowness is not accurate in counting the live fast connections. It should avoid closing connection when we are already at the repair threshold.
I found that when counting the empty channels (fast connection keep their buffer channels empty), the `checkSlowChannel` also checks the channel of the current connection. It's not impossible that the full channel (before invoking `checkSlowChannel`) becomes empty while counting the empty channels. This way the current channel will be counted too and …
=> Don't count current channel when testing for slowness

pkg/audit/service.go
small fix - there was an error when a returned stripe is nil even though there didn't have to be (just means that the auditor was attempting to audit an inline segment)
=> removes error when attempting to audit inline segment

pkg/storage/segments/store.go
When repairing we don't want to add bad nodes back into the pointerDB entry. If the index of a node from the pointerDB entry is equal to a value in lostPieces, set that node equal to nil.
=> remove bad nodes from originalNodes list when repairing

pkg/encryption/examples_test.go, pkg/encryption/path.go, pkg/encryption/path_test.go, pkg/metainfo/kvmetainfo/buckets_test.go, pkg/metainfo/kvmetainfo/objects.go, pkg/miniogw/config.go, pkg/storage/buckets/prefixed.go, pkg/storage/buckets/store.go, pkg/storage/objects/store.go, pkg/storage/streams/store.go, pkg/storage/streams/store_test.go
Implements https://storjlabs.atlassian.net/browse/V3-546
The path encryption type is now stored in the bucket's metadata - in the `PathEncryptionType` field. Whenever an operation on the object store is executed, this value is taken into account for the path encryption.
Users can configure the `path-enc-type` property in the config.yaml, similar to the `enc-type` property for the content encryption. The `path-enc-type` is used only for creating new buckets. From there on, any operation on the bucket uses the `PathEncryptionField` from the bucket's metadata.
=> Configurable encryption type for paths

README.md
Because I think it will help. I wish I could link it to something that easily explains what the alpha is, but I am not sure if there is a specific resource that would answer that question - and only that question - more adequately than the rest of the README.
=> Adding a "Version: Alpha" badge

pkg/eestream/rs_test.go, pkg/eestream/stripe.go
Fixes https://storjlabs.atlassian.net/browse/V3-551
If enough readers have already failed with error (so that there is no chance to reconstruct the stripe), the StripeReader should return an error immediately instead of waiting for the rest (potentially stalled) readers to return their erasure shares.
=> eestream avoids waiting for pending readers if lots of errors

internal/testcontext/context.go, internal/testcontext/context_test.go
1. Added full stack-trace to when test exceeds timeout for debugging.
2. Removed testcase which uses testing.T directly. There's no easy way to start a silent testing.T, so it still prints info to stdout, which makes the output in Travis confusing.
=> testcontext: Add stack-trace and remove testcase with testing

cmd/uplink/cmd/root.go, cmd/uplink/cmd/setup.go, go.mod
This pr detects the user's home directory, so that the uplink's default config directory will be located according to the OS's standards.
One problem though is that some of these directory paths look inconsistent in the help text because of escaped strings, e.g. for ca.cert-path, ca.key-path, identity.cert-path, and identity.key-path, so those still need to be changed.
=> Fix default basepath location

pkg/audit/verifier.go, pkg/audit/verifier_test.go
Fixes https://storjlabs.atlassian.net/browse/V3-841
There were two issues in the code:
1. Accessing a node in the `verify` method via `nodes[pieceNum]` may panic, because the `nodes` slice was not guaranteed to include a node for each piece. If a specific piece was not uploaded successfully to the respective node, then this node is not included in the segment pointer and hence won't be part in the `nodes` slice. The solution is to convert `nodes` from slice to a map with the piece number as its key.
1. The `auditShares` method assumed that the `copies` slice returned by the `makeCopies` method is the same size as the `originals` slice. This assumption is wrong when downloading a share failed with error. In such case `makeCopies` will return a shorter `copies` slice. Therefore, the …
=> Fix panic in Audit service

cmd/uplink/cmd/root.go
Changes the uplink directory base path following these standards:
> $XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
=> fixes Linux default base path for uplink

cmd/overlay/main.go, examples/piecestore-client/main.go, internal/testplanet/node.go, internal/testplanet/planet.go, pkg/accounting/tally/tally_test.go, pkg/audit/verifier_test.go, pkg/datarepair/checker/checker_test.go, pkg/inspector/server.go, pkg/kademlia/config.go, pkg/kademlia/kademlia.go, pkg/kademlia/kademlia_test.go, pkg/overlay/client_test.go, pkg/overlay/server.go
This is minimal code to fix overlay cache to only show storage nodes.
=> Ensure that we only choose storage nodes

pkg/satellite/validation.go, pkg/storj/node.go
- Remove unused `sort.Interface` implementation on `NodeID`
- Fix variadic arg error
=> cleanup and bugfix

pkg/kademlia/config.go
Changed the optional configured publicly published address name for a Kademlia Node from SelfAddr to ExternalAddress.
=> Changed SelfAddr -> ExternalAddress

pkg/statdb/proto/statdb.pb.go, pkg/statdb/proto/statdb.proto, pkg/statdb/statdb.go, pkg/statdb/statdb_test.go
FindValidNodes is an unused function that we thought we needed for node selection. For data repair, we need a very similar function. This PR converts the old, unused function to something more useful to us
=> Change statdb.FindValidNodes to FindInvalidNodes

pkg/node/connection_pool.go, pkg/node/connection_pool_test.go
This fixes races in tests like this one:
```
==================
WARNING: DATA RACE
Write at 0x00c00018bfc0 by goroutine 356:
storj.io/storj/pkg/node.(*ConnectionPool).Dial.func1()
/home/kaloyan/git/storj/pkg/node/connection_pool.go:98 +0x189
sync.(*Once).Do()
/usr/local/go/src/sync/once.go:44 +0xde
storj.io/storj/pkg/node.(*ConnectionPool).Dial()
/home/kaloyan/git/storj/pkg/node/connection_pool.go:97 +0x1e8
storj.io/storj/pkg/node.(*Node).Lookup()
/home/kaloyan/git/storj/pkg/node/node.go:22 +0x174
storj.io/storj/pkg/kademlia.(*peerDiscovery).Run.func1()
/home/kaloyan/git/storj/pkg/kademlia/peer_discovery.go:90 +0x332
Previous read at 0x00c00018bfc0 by goroutine 107:
storj.io/storj/pkg/node.(*ConnectionPool).disconnect()
/home/kaloyan/git/storj/pkg/node/connection_pool.go:77 +0x119 …
```
=> Fix race in connection pool

cmd/captplanet/run.go, cmd/captplanet/setup.go, cmd/uplink/cmd/mb.go, cmd/uplink/cmd/root.go, cmd/uplink/cmd/run.go, cmd/uplink/cmd/setup.go, pkg/miniogw/config.go
This changes the uplink config from looking like this:
```
uplink:
access-key: insecure-dev-access-key
address: 127.0.0.1:7777
api-key: abc123
cert-path: /home/jt/.local/share/storj/capt/uplink/identity.cert
enc-block-size: 1024
enc-key: highlydistributedridiculouslyresilient
enc-type: 1
erasure-share-size: 1024
key-path: /home/jt/.local/share/storj/capt/uplink/identity.key
max-buffer-mem: 4194304
max-inline-size: 4096
max-threshold: 95
min-threshold: 29
minio-dir: /home/jt/.local/share/storj/capt/uplink/minio
overlay-addr: 127.0.0.1:7778
path-enc-type: 1
peer-ca-whitelist-path: ""
pointer-db-addr: 127.0.0.1:7778
repair-threshold: 35
secret-key: insecure-dev-secret-key
segment-size: 64000000
success-threshold: 80
verify-auth-ext-sig: false
```
to this:
```
uplink:
client:
api-key: abc123 …
```
=> clean up uplink config section

.travis.yml
Travis doesn't show anything when it fails in 10min time-limit, ensure that go returns before that.
=> Add time limit to ensure that travis prints something when it fails.

internal/testplanet/node.go, pkg/kademlia/kademlia.go
Test cases running on testplanet may be delayed with 20 seconds due to a deadlock during testplanet shutdown.
These are the two goroutines that take part in the deadlock:
```
goroutine 5 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc0001a26d0, 0x100000002)
/usr/local/go/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc0001a26c0)
/usr/local/go/src/sync/cond.go:56 +0x8e
google.golang.org/grpc.(*Server).GracefulStop(0xc00048d080)
/home/kaloyan/go/pkg/mod/google.golang.org/grpc@v1.15.0/server.go:1362 +0x29e
storj.io/storj/pkg/provider.(*Provider).Close(0xc0001a2700, 0x2, 0x2)
/home/kaloyan/git/storj/pkg/provider/provider.go:112 +0x51
storj.io/storj/internal/testplanet.(*Node).Shutdown(0xc0003421e0, 0x0, 0x0)
/home/kaloyan/git/storj/internal/testplanet/node.go:95 +0x4a6 …
```
=> Fix deadlock on testplanet shutdown

pkg/miniogw/multipart.go
If the bucket does not exist, the multipart upload should fail fast with "NoSuchBucket" error.
Without this fix, the goroutine of the multipart upload starts generating tons of errors on captplanet and returning a confusing "Connection was closed before we received a valid response from endpoint URL" to the S3 client.
=> Verify bucket exists before starting multipart upload

pkg/bwagreement/test/server_test.go, satellite/satellitedb/database_test.go, satellite/satellitedb/satellitedbtest/utils.go, satellite/satellitedb/utils.go
Method `ForEach` was created to move DB creation from specific packages (e.g. bwagreement) and simplify testing with all supported DBs. PR contains also changes in bwagreement package to show how method can be used.
=> Simplify testing with all supported DBs

.travis.yml
Disable windows tests, they are using up quite a lot of resources in Travis, so make them run only on demand.
=> Run windows tests only when windows is in commit message.

pkg/ranger/content_test.go, pkg/ranger/file_test.go, pkg/ranger/http_test.go, pkg/ranger/reader_test.go, pkg/ranger/readerat_test.go
Reduce number of subtests to make the output in tests more concise.
=> Reduce ranger test output

pkg/miniogw/integration_test.go
Skipping TestUploadDownload because it stalling Travis tests.
=> Skip TestUploadDownload

pkg/datarepair/repairer/config.go, pkg/metainfo/kvmetainfo/buckets_test.go, pkg/miniogw/config.go, pkg/miniogw/gateway_test.go, pkg/overlay/client.go, pkg/storage/segments/store.go, pkg/storage/segments/store_test.go
Adds a node selection config to the miniogw config, so that segment store provides minimum values of AuditCount, AuditSuccessRatio, UptimeCount, and UptimeRatio when requesting nodes from the overlay. Bandwidth and disk space are also provided as options when requesting nodes from the overlay.
=> adds node selection config

cmd/captplanet/run.go, cmd/overlay/cache.go, pkg/accounting/db.go, pkg/accounting/rollup/config.go, pkg/accounting/tally/config.go, pkg/accounting/tally/tally.go, pkg/overlay/config.go, pkg/overlay/config_test.go, pkg/pointerdb/config.go, pkg/satellite/satellitedb/db.go, pkg/satellite/satelliteweb/config.go, pkg/statdb/statdb.go, pkg/statdb/statdb_test.go, pkg/utils/utils.go, satellite/satellitedb/database.go, satellite/satellitedb/irreparabledb.go, storage/redis/client.go
Integrate tally service with Captplanet
Acceptance criteria:
- Add a config struct to captplanet so that the tally service starts automatically.
- The Tally service starts when you run captplanet
=> added tally to capt run.go

pkg/datarepair/repairer/config.go, pkg/datarepair/repairer/repairer.go, pkg/datarepair/repairer/repairer_test.go, pkg/storage/segments/repairer.go, pkg/storage/segments/repairer_test.go, pkg/storage/segments/store.go, pkg/storage/segments/store_test.go
With this PR:
- The data repairer no longer needs configuration for redundancy strategy and inline segment threshold
- When repairing a segment the redundancy strategy from the segment's pointer is used instead the one that was configured for the repairer
- A Segment Repairer is extracted from the existing Segment Store to achieve the above
=> Data repairer should use the redundancy strategy from segment's pointer

cmd/captplanet/main.go
[`init` functions don't necessarily run in the order one might expect](https://medium.com/golangspec/init-functions-in-go-eac191b3860a). It is currently the case that main.go's init is run first because its file name is first in lexical order for that package but that may not always be the case.
=> fix `defaultConfDir` initialization

cmd/captplanet/run.go
Different capital letter looks ugly.
```
root@kali:~# captplanet run
starting satellite on 127.0.0.1:7778
Starting s3-gateway on 127.0.0.1:7777
Access key: insecure-dev-access-key
Secret key: insecure-dev-secret-key
starting storage node 8 12KFuJC1Ks6v2uaj254Rx63WVq3d3EdYpcg1utDKLATA3CWWM2s:127.0.0.1:7796 (kad on 127.0.0.1:7796)
```
=> unify logging messages

internal/testplanet/node.go, internal/testplanet/planet.go, pkg/datarepair/repairer/config.go, pkg/metainfo/kvmetainfo/buckets_test.go, pkg/miniogw/config.go, pkg/miniogw/gateway_test.go, pkg/overlay/client.go, pkg/overlay/config.go, pkg/overlay/server.go, pkg/overlay/server_test.go, pkg/storage/segments/repairer.go, pkg/storage/segments/repairer_test.go, pkg/storage/segments/store.go, pkg/storage/segments/store_test.go
- removes node selection config from uplink
- adds node selection config to overlay server config
- removes passing in nodeStats from oc.Choose inside segment Put
- adds min node stats placeholder (all set to zero) to test planet
=> moves node selection config setup from uplink to satellite

cmd/storagenode/main.go
Adds farmer wallet and mail validation during storage node startup.
https://storjlabs.atlassian.net/browse/V3-994
=> Validate farmers wallet and email configuration

pkg/discovery/service.go
Discovery may not find the node we are looking for and this shouldn't be an error.
=> Do not error if Discovery can not find Node

pkg/process/exec_conf.go
Logger is created before values from config.yaml are loaded.
=> Fix ignored config logger settings

pkg/piecestore/psserver/server.go
We log each node's ID on startup in `pkg/server/config.go`. The log statement in piecestore is redundant
=> remove node startup log in piecestore server

cmd/identity/keys.go, pkg/identity/certificate_authority.go, pkg/identity/generate.go, pkg/identity/identity.go, pkg/identity/identity_test.go, pkg/identity/utils.go, pkg/peertls/peertls.go, pkg/peertls/peertls_test.go, pkg/storj/node.go, pkg/storj/node_test.go
this PR includes four commits:
* first commit is a huge change - it changes id generation to be sha256 instead of sha3. keccak (sha3) is not only not asic-resistent, it's asic friendly, which is kind of not what you want for a PoW scheme. let's just use the tried and true thing.
* second commit restructures the id generation code to prepare for the third commit
* third commit is a tool that just generates keys until it's shut down, storing them indexed by their trailing zero count (the minimum difficulty they would pass)
* fourth commit adds more difficulty tests
=> prepare key generation for launch

cmd/captplanet/run.go
It seems that the satellite goroutine somehow trigger the race in uplink, however I'm not completely certain. Might be something due to changing the config. This makes a copy of the configs to avoid this issue.
https://storjlabs.atlassian.net/browse/V3-1063
=> Fix captplanet race

pkg/process/exec_conf.go
Flag overridden in storage node was ignored because it was not from the user flags list. If flag is set by `override` param then it's always set in config file.
=> Fix ignored overridden flag in user config

pkg/node/server.go
instead of ERROR, because errors contacting other nodes in the network
are entirely normal and expected, and they don't need urgent attention.
=> trivial: log "connection to node failed" at DEBUG level

cmd/inspector/main.go
output should look like this now:
```
-------------------------------
Bucket ID: 12wkBET2rRgE8pahuaczxKbmv7ciehqsne57F9gtzf1PVawbBMp
Nodes in Bucket: 1
Node 0:
{
"id": "126DPN9xQmDxKeutWF2iPBZbetwbk9CgCWZSHdnMw5yRvncr3F3",
"address": {
"transport": "TCP_TLS_GRPC",
"address": "0.tcp.ngrok.io:xxxx"
},
"type": "STORAGE",
"restrictions": {
"freeBandwidth": "1073741824",
"freeDisk": "297954123776"
},
"reputation": null,
"metadata": {
"email": "your-email@example.com",
"wallet": "0x0000000000000000000000000000000000000000"
},
"latencyList": [
],
"auditSuccess": false,
"isUp": false,
"updateLatency": false,
"updateAuditSuccess": false,
"updateUptime": false
}
```
=> adds pretty printing for inspector kad dump-nodes

cmd/certificates/auth.go
this avoids getting an "userID cannot be empty" error when using an
emails list that has a newline at the end.
=> fix some email list parsing in certificates tool

bootstrap/peer.go, cmd/bootstrap/main.go, cmd/certificates/main.go, cmd/satellite/main.go, cmd/storagenode/main.go, pkg/server/config.go, storagenode/peer.go
This separates Identity flags from Server. If we have multiple servers per peer, then it doesn't make sense to have identity multiple times.
Note this changes flags:
```
--server.identity.key-path
--server.identity.cert-path
```
Into:
```
--identity.key-path
--identity.cert-path
```
With the exception of certificates server.
=> Separate identity from server config

pkg/accounting/tally/tally_test.go, pkg/bwagreement/bwagreementtest/common.go, pkg/bwagreement/server_test.go, pkg/bwagreement/testbwagreement/common.go, pkg/piecestore/psserver/server_test.go
Don't use 1 sec expiration as it's likely to expire during tests.
=> Improve bwagreement tests

pkg/kademlia/kademlia.go, pkg/kademlia/kademlia_test.go
Decreases the refresh interval and minimum time threshold to start a refresh in Kademlia. 
This is the first in a series of improvements to make Kademlia bootstrapping more efficient.
=> Decreases refresh time per bucket in Kademlia

pkg/storage/ec/client_test.go
The test could fail because it did not take into account that nodes could be cut from upload as a long tail. Hence they won't be present in `successfulNodes`.
=> Fixes intermitent failures in storage/ec TestPut

pkg/accounting/db.go, pkg/accounting/rollup/rollup.go, pkg/accounting/rollup/rollup_test.go, pkg/accounting/tally/tally.go, pkg/accounting/tally/tally_test.go, satellite/satellitedb/accounting.go, satellite/satellitedb/dbx/satellitedb.dbx, satellite/satellitedb/dbx/satellitedb.dbx.go, satellite/satellitedb/locked.go
For generating payment reports, we query the accounting rollup table. We want to make sure that this service functions as expected. Once we refactor QueryPaymentInfo to sum data totals across rollups, we'll need to change what we expect the length of rows to be on line 89
=> Rollup tests

cmd/identity/main.go, pkg/peertls/extensions.go, pkg/peertls/peertls_test.go, pkg/pkcrypto/encoding.go, pkg/pkcrypto/hashing.go, pkg/pkcrypto/signing.go
according to Go docs, the error cases should never happen. change them to panics, just in case, but no need to return error and check it every single time.
NOTE: this change has two commits; the first actually corresponds to #1241. This change is meant to build on top of that one. I don't think Github provides any nice way to do that, so please bear with the awkwardness for now.
=> SHA256Hash() and TBSBytes() needn't return error

cmd/identity/batch.go, cmd/identity/main.go, cmd/storj-sim/inmemory.go, internal/testplanet/gen_identities.go, pkg/auth/signedMessage.go, pkg/bwagreement/server_test.go, pkg/certificates/certificates_test.go, pkg/identity/certificate_authority.go, pkg/identity/identity.go, pkg/identity/identity_test.go, pkg/identity/utils.go, pkg/peertls/peertls.go, pkg/pkcrypto/common.go, pkg/pkcrypto/encoding.go, pkg/pkcrypto/signing.go, pkg/server/options.go
This is another change on the path to unifying the public-key crypto use in storj. All functions that encode and decode public keys, private keys, certificates, cert extensions, etc are now collected and normalized and have (I think) more descriptive names.
NOTE: this change has three commits; the first two actually correspond to #1241 and #1242. This change is meant to build on top of those. I don't think Github provides any nice way to do that, so please bear with the awkwardness for now.
=> Consolidate key/cert/signature encoding and decoding

internal/testplanet/planet.go
Currently revocation databases aren't being closed properly so, disable it for now in testplanet.
=> disable revocation db for testplanet

pkg/kademlia/routing_helpers.go, pkg/pb/bandwidth_utils.go, pkg/storj/node.go, storage/boltdb/client.go, storage/common.go, storage/postgreskv/client.go, storage/redis/client.go, storage/storelogger/logger.go, storage/teststore/store.go, storage/testsuite/test.go, storage/testsuite/test_list.go
Cleanup / simplification in preparation for batched iterators work here:
https://storjlabs.atlassian.net/browse/V3-925
---
KeyValueStore.ReverseList() was only used by the Kademlia routing table buckets list, which is a bounded, _very_ short list that shouldn't need special treatment.
Most KeyValueStores don't support reverse iteration natively, so we had hacks in place instead.  This PR removes those hacks.
=> Removed ReverseList from KeyValueStore interfaces

internal/dbutil/split.go, pkg/certificates/config.go, pkg/identity/revocations.go, pkg/pointerdb/config.go, pkg/utils/utils.go, satellite/satellitedb/database.go
Also rename to `SplitConnstr` since it's actually not a valid URL and it's usually reffered as `connstr`.
=> Move SplitConnstr to a nicer place

pkg/dht/dht.go, pkg/kademlia/dialer_test.go, pkg/kademlia/inspector.go, pkg/kademlia/kademlia.go, pkg/kademlia/kademlia_test.go, pkg/kademlia/routing.go, pkg/kademlia/routing_test.go, pkg/piecestore/psserver/server.go
We realized that the Kademlia FindNear() function was
1) not using XOR distance (AKA _totally broken_)
2) largely a duplicate of the RoutingTable FindNear() function
Changes in this PR:
1) upgraded RoutingTable FindNear() to use iterator and restrictions
2) removed unneeded RoutingTable interface
3) made Kademlia wrap methods that were previously accessed via RoutingTable
4) fixed the tests
=> kad.FindNear fix

cmd/identity/main.go
this bandaid-fixes the identity tool issues (revocation db defaults to /revocations.db due to the missing CONFDIR)
current identity authorize commands on macs are failing because they can't open the revocation db for the tls settings
=> cmd/identity: set default CONFDIR

pkg/piecestore/psclient/client.go, pkg/piecestore/psclient/readerwriter.go, pkg/storage/ec/client.go, pkg/storage/ec/client_test.go, pkg/storage/ec/mocks/mock_client.go, pkg/storage/ec/psclient_mock_test.go, pkg/storage/segments/repairer.go, pkg/storage/segments/repairer_test.go, pkg/storage/segments/store.go
Changes:
* psclient receives storage node hash and compare it to own hash for verification
* uplink sends delete request when hashes don't match
* valid hashes are propagated up to segments.Store for future sending to satellite  
PR is a part of a larger set of changes for:
PointerDB must require signatures from storage nodes on uploads - https://storjlabs.atlassian.net/browse/V3-917
=> Use SignedHash on client/uplink side

cmd/certificates/claims.go, cmd/certificates/main.go, pkg/certificates/config.go, pkg/identity/certificate_authority.go, pkg/identity/identity.go
+ make claims flags consistent with other certificates sub-commands flags
+ move claim commands registration/binding into main
+ prevent overwrite fields on CA/Identity setup-configs from being
written to config.yaml
+ prevent overwtite flag on certificates config from being read from
config.yaml
=> some certificates cmd cleanup:

cmd/satellite/main.go, cmd/satellite/usage.go
Rename the `satellite report payment` command to be more clear that the report is generating node usage data.
=> rename payment command to node usage

web/satellite/src/utils/apolloManager.ts
this default graphql endpoint works whenever the satellite is hosting the npm built assets.
=> web ui: change default graphql endpoint

pkg/accounting/tally/tally.go, pkg/piecestore/psclient/readerwriter.go
This log messages produces Gigabytes of log, that arent super necessary right now
=> Reduce Log Messages on Production Settings

pkg/storage/ec/client.go
This PR ensures that the upload timer of ECClient is always stopped after no more status is expected from uploaded pieces. It also ensures that the "Timer expired" message will be logged only if the context is not already cancelled.
This is to avoid confusing logs where a "Timer expired" message is logged significantly later and mixes with similar messages logged from the upload of the next file segments.
=> Ensure ECClient upload timer is stopped when no more status is expected

pkg/peertls/tlsopts/options.go, pkg/peertls/tlsopts/options_test.go, pkg/peertls/tlsopts/tls.go
+ Rename `options.PCVFuncs` to `options.VerificationFuncs`
+ Separate `ClientTLSConfig` from `ServerTLSConfig` and disambiguate
+ Factor out common stuff
=> tlsconfig refactor / cleanup

satellite/metainfo/metainfo.go, storagenode/inspector/inspector_test.go, storagenode/monitor/monitor_test.go, storagenode/piecestore/endpoint_test.go
Restricts `/` in `metainfo` endpoint bucket name
=> Restrict slash in bucket name

pkg/transport/transport.go
transport.DialNode has a context timeout so I thought DialAddress should too
=> adds context timeout to transport.DialAddress

bootstrap/peer.go, pkg/kademlia/endpoint.go, pkg/kademlia/kademlia_test.go, satellite/peer.go, storagenode/peer.go
- this pr #1545 added a consistent timeout across `transport.dialNode` calls, so the specific timeout setting for pingback is no longer necessary.
- tests to ensure that behavior remains the same were included in #1545 as well (specifically `TestSlowDialerHasTimeout` in pkg/kademlia/dialer_test.go and `TestPingTimeout` in pkg/kademlia/kademlia_planet_test.go).
- removes `pingbackTimeout` field from `kademlia.Endpoint`
- removes `pingbackTimeout` argument from `kademlia.NewEndpoint`
- removes context.WithTimeout call with `pingbackTimeout` since it will come with a timeout built into the dialer.
=> removes pingbackTimeout

internal/testplanet/uplink_test.go, pkg/overlay/cache.go, pkg/overlay/cache_test.go, pkg/storage/segments/repairer_test.go, satellite/metainfo/metainfo.go, satellite/satellitedb/overlaycache.go
The repairer test is flakily passing and failing, so we decided to create `TestDownloadWithSomeNodesOnline` as a "sanity check" type test to preface the repair test.
We found that there was a bug in satellite/metainfo/metainfo.go where the whole download would fail, even if the required number of pieces were still online. This fail was happening because the overlaycache.Get call returned an error, which wasn't properly handled. 
- Adds error handling to ensure that the download would only fail if less than the minimum required number of nodes were online.
- Adds `TestDownloadWithSomeNodesOffline` to internal/testplanet/uplink_test.go, which uploads some data, stops some nodes, then downloads to make sure data is the same.
=> adds test for correct download with non-critical amount of nodes offline

pkg/audit/verifier.go
https://storjlabs.atlassian.net/browse/V3-1459
This PR fixes various problems (eg: "VerifyOrderLimitSignature unable to get signee") associated with a service (usually one that calls another service) timing out.  It does so by fixing a single timeout calculation which was overflowing int32 and leading to very small timeouts.
=> Fix random timeouts related to peicestore

pkg/audit/service.go, pkg/datarepair/checker/checker.go
Audit and repair job can fail. Don't return that error cause that will stop the satellite. Fix for https://storjlabs.atlassian.net/browse/V3-1464
=> Don't crash on audit and repair failures

pkg/audit/cursor_test.go, pkg/audit/newverifier_test.go
When there are no pointers in the pointerdb, this test caused a memory leak because of an infinite loop.
Just makes the NextStripe call 3 times and if it still doesn't have a non-nil stripe, then the test fails. #1616 refactors NextStripe so that a more informative error is returned in the future (i.e. "unable to find pointers after %d attempts").
- Also makes sure that all audit tests use `require` instead of `assert`.
=> fixes infinite loop in audit TestVerifierHappyPath

pkg/accounting/rollup/rollup.go, pkg/accounting/rollup/rollup_test.go, pkg/accounting/tally/tally_test.go
This PR enables the deletion of accounting raws after they are successfully rolled up to decrease load on satellite database
=> Delete accounting raws after rollup

.travis.yml
go 1.12.2 and go 1.11.7 seem to be having issues with compilation so use the previous version
=> Use go 1.12.1 for compiling in Travis

pkg/accounting/projectusage_test.go, pkg/accounting/rollup/rollup.go, pkg/accounting/tally/tally.go, satellite/orders/endpoint.go, satellite/orders/orders_test.go, satellite/orders/service.go, satellite/satellitedb/orders_test.go
This PR addresses the places where we do not convert time to UTC before entering it as a utimestamp in the DB
according to dbx documentation 
> utimestamp (timestamp with no timezone. expected to be in UTC)
=> convert times to UTC before entering as utimestamp

storagenode/inspector/inspector.go
Why:
- storagenode dashboard displayed old disk space for now obsolete pieces (they were deleted during migration)
What:
- We're no longer summing old used space with the new used space. The storagenode dashboard will now only show new used space.
=> no longer includes totalUsedSpaceOld when calculating storagenode used space

Makefile
This should make the `push-images` target complete successfully and push binaries to GCS again.
=> Make tracked branch feature work with multi-arch manifests

cmd/uplink/cmd/setup.go, cmd/uplink/cmd/setup_test.go
We had a neat uplink setup wizard PR and a default satellite addr PR. this PR combines them so the wizard gets the default address functionality. also checks errors because I couldn't help myself
=> uplink setup wizard uses default port, checks errors

cmd/gateway/main.go, lib/uplink/bucket_attrs_test.go, lib/uplink/uplink.go, pkg/miniogw/gateway_test.go, pkg/miniogw/integration_test.go
What: This change moves project-level bucket metadata encryption information to the volatile section, because it is unlikely to remain in future releases
Why: Ultimately, the web user interface will allow bucket management (creation, removal, etc), but not object management as that requires an encryption key for sure and we don't want to have users give the satellite their encryption keys.
At a high level, a (*Project) type should map to all of the things you can do inside the web user interface within a project, which by necessity cannot have an encryption key. So, we really don't want an encryption key in the non-volatile section of this library.
=> libuplink: remove encryption key from project opening

internal/testplanet/uplink.go
What: 
Changes `testplanet.Uplink.GetConfig` in a way to ensure that any of the redundancy properties will be higher than 0, as `0` or lower is not a valid value for them.
Why:
If a test creates test planet with less than 5 storage nodes then `testplanet.Uplink.GetConfig` will return invalid redundancy configuraiton. 
=> Fix RSConfig calculation in testplanet.Uplink.GetConfig

internal/errs2/collect.go, internal/errs2/collect_test.go
`utils` packages tend to end up as kithcen-sinks, move the last func to a more appropriate place remove the utils package entirely.
=> Move collect to a more appropriate package

satellite/peer.go
What: remove internal logging of `pdb` 
Why: Currently the verbose output is really verbose. `pdb` is not that useful.
=> Disable pointer db logging

pkg/process/exec_conf.go
this adds a flag to all pkg/process binaries where if set, will write a process-level trace for all monkit-instrumented functions as an svg to the target path.
usage like:
uplink cp --debug.trace-out=trace.svg file sj://bucket/file
Note that this feature only works with codepaths that are kicked off in a *cobra.Cmd using process.Ctx() as the starting context, and it's important to note that this is much more useful when `defer mon.Task()(&ctx)(&err)` is littered everywhere
=> pkg/process: add --debug.trace-out option to binaries

cmd/storj-sim/network.go
What:  Hardcode the debug ports for storj-sim
Why: The default behavior is to pick a port at random for debug, however this is annoying because if you want to use debug endpoints, you have to go search for what the port is.
=> hardcode debug ports for storj-sim

cmd/bootstrap/main.go, cmd/certificates/main.go, cmd/gateway/main.go, cmd/identity/batch.go, cmd/identity/certificate_authority.go, cmd/identity/identity.go, cmd/identity/main.go, cmd/identity/revocations.go, cmd/overlay/main.go, cmd/satellite/main.go, cmd/statreceiver/main.go, cmd/storagenode/main.go, cmd/uplink/cmd/root.go, cmd/uplink/cmd/setup.go, cmd/versioncontrol/main.go, examples/grpc-debug/main.go, internal/testplanet/uplink.go, pkg/accounting/rollup/rollup.go, pkg/accounting/tally/tally.go, pkg/cfgstruct/bind.go, pkg/cfgstruct/bind_test.go, pkg/miniogw/integration_test.go, pkg/piecestore/psserver/config.go, uplink/config.go
this change makes it so that by default, the flag defaults are chosen based on whether the build was built as a release build or an ordinary build (be sure to check out scripts/release.sh for how release builds work).
release builds by default get release defaults, whereas ordinary builds by default get dev defaults.
any binary can have its defaults changed by specifying
--defaults=dev
or
--defaults=release
Also adds a commit to make release defaults more clear, which extends cfgstruct structs to support either a 'default' tag, or a pair of 'devDefault' and 'releaseDefault' tags, but not both, for added clarity
=> pkg/cfgstruct: tie defaults to releases

satellite/satellitedb/migrate.go
What: 
migrating injured segments fails on real data
Why:
path is not unique.  unique info does not 100% mean unique path
=> fix non-unique path for injured segments

internal/testplanet/uplink_test.go, satellite/satellitedb/repairqueue_test.go
Why:
- I've had to restart Jenkins multitudinously to get my unrelated PR to pass.
What:
- skips TestUploadDownloadOneUplinksInParallel and TestParallel (whose flakiness should be fixed/addressed by #1796 and #1797) but in the meantime I think they need to be skipped.
=> skips TestUploadDownloadOneUplinksInParallel and TestParallel

pkg/datarepair/checker/checker.go, pkg/discovery/service_test.go, pkg/overlay/cache.go, satellite/inspector/inspector.go, satellite/orders/service.go
What: 
Rename Online to IsOnline, VettedFor to IsHealthy.  added IsNew.
Made node IsOnline, IsNew, IsHealthy tests part of overlay
Wired IsHealthy up to configs
Why:
I liked those names better.  :P
IsOnline, IsNew, IsHealthy need to be config driven
Valid IsHealthy configs required for checker to produce valid results.
What is not included:
IsOnline is still hard-coded amd not wired up to configs, will accomplish in another PR
=> wired up IsHealthy to config

storagenode/trust/service.go, storagenode/trust/service_test.go
The logic for caching was correct, however not the reading of the value in the cache. Simplify the implementation using a mutex per cert.
=> storagenode: getting signee cert always asked the kademlia network

internal/testplanet/planet.go, pkg/accounting/rollup/rollup.go, pkg/accounting/rollup/rollup_test.go
What: sets satellite and testplanet delete-tallies config to false to avoid forgetting to update the config values
Why: safety precaution until we make sure we want to turn deletes back on
=> set delete-tallies default to false

Makefile
The pod name was changed, this is why jenkins has been failing master builds.
=> Fix deploys to the dev site

uplink/config.go, uplink/config_test.go
What: 
For avoiding the false sense of security the LoadKey method of the
encryption configuration must return an error when the key file path is
empty, however for not breaking other existing tests on different
packages the GetMetainfo must skip to load the key when path it's empty
and use the zero value key.
Why: show another solution to the worry expressed in the review of PR #1782 (https://github.com/storj/storj/pull/1782#discussion_r278416351)
=> uplink: return error on load key when no key filepath

pkg/overlay/cache.go, pkg/overlay/cache_test.go, satellite/satellitedb/locked.go, satellite/satellitedb/overlaycache.go
What: 
Removed unused .List() method
Why:
Less is more
=> removed unused .List() method

satellite/inspector/inspector.go
What: 
Only consider "healthy" nodes in inspector segment health check.
Why:
It strongly appears like inspector intends to measure what checker / repairer cares about.  Previously, inspector measured segment health only by what was "online", while checker also cares about if the node uptime, if it has failed too many audits, etc.  This change makes them care about the same thing.
=> made inspector segment health care about healthy nodes

pkg/datarepair/repairer/repairer.go
What: 
Repair previously timed out in 1 minute.  We made that 10.
Why:
Stefan was seeing repair exit after exactly 1 minute quite often in his logs.
It was timing out before it could complete.
=> longer repair window

storagenode/monitor/monitor.go
What: Adds the already used space to the allocation sum
Why: Failed Checks, even if space is available ( #1839 )
Special Thanks to @ReneSmeekes for his troubleshooting. I was able to reproduce the issue and the Change fixes it.
=> Update Calculation to include the already used space for the diskspace allocation

cmd/uplink/cmd/root.go
Fixes https://storjlabs.atlassian.net/browse/V3-1713
What: 
Removes the identity from the uplink configuration.
Why:
Because it is not required to have a designated identity anymore. Libuplink will internally generate a disposable identity with difficulty 0 whenever the uplink CLI is used.
=> Uplink CLI should not require identity

cmd/gateway/main.go, pkg/miniogw/gateway_test.go, pkg/miniogw/integration_test.go
What: 
Same as #1920, but for the S3 Gateway.
Why:
Because the S3 Gateway should not require designated identity anymore. Libuplink will internally generate a disposable identity with difficulty 0 whenever the gateway is started.
=> Gateway should not require identity

Jenkinsfile.public
What: Decrease timeout from 30 to 10 minutes.
Why: Normal builds are done in less than 5 minutes, no need to wait more than twice as that.
=> Shorten timeout for stalled builds

Makefile
What: 
* Clarifies that the test-satellite-cfg-change is for being run by
Jenkins as others are.
* Move the target for updating the satellite configuration lock file to
a new Makefile group, called "Tooling".
* Change how it's run the script update-satellite-cfg-lock.sh for
ensuring that the outcome is the same when running from different
machines.
Why: It wasn't clear that one of the targets is for running it from Jenkins and the other one didn't produce the same outcome from different machines.
@mobyvb this should be fixed what you spotted and commented in https://github.com/storj/storj/pull/1898#pullrequestreview-234701092
@wthorp removing it was an easy solution and if I wouldn't have come up with this solution I would do it, but this solution should be better than removing it.
Thanks …
=> v3-1660: improvement of test-satellite-cfg-change and related things

scripts/test-sim.sh
Currently it's easy to forget that network needs to work stable with multiple satellites, hence start multiple satellites in integration tests.
Later improvements could try to upload to both satellites.
=> jenkins: run two satellites in integration tests

pkg/kademlia/dialer_test.go, pkg/transport/transport.go
The timeout tests were configured to use very short timeouts but
for some reason they took many seconds to complete. This commit
fixes two issues:
1. The transports were always using the default timeout rather than
the timeout specified.
2. The tests were possibly calling t.FailNow inside of the non-test
goroutine which causes it to exit, possibly losing an error from
the error group. Additionally, it didn't seem to be testing that
the error came back as a deadline wrapped in a transport error.
The tests run in ~3s instead of ~60s now.
=> pkg/kademlia: fix timeout test slowness

internal/sync2/cycle.go, internal/sync2/cycle_test.go, internal/sync2/doc.go
What: minor improvements in internal/sync2 package.
Why: 
* Avoid that Close method hang if Start/Run has not been called.
* Ensure that internal ticker is always stopped.
* Add clarifications when methods calls panic.
* Add a package level docs following current conventions.
=> internal/sync2: Cycle minor impl & docs improvements

cmd/gateway/main.go, cmd/storj-sim/network.go, lib/uplink/uplink.go
What: 
- Removes `UseIdentity` and `IdentityVersion` from libuplink `Config.Volatile`. We shouldn't have aby use case for these two anymore.
- storj-sim does not generate identity for gateway anymore
- Gateway properly closes the libuplink project when verifying the satellite config
Why:
These changes address additional comments left in #1920 and #1921.
=> Remove UseIdentity and IdentityVersion from libuplink volatile config

internal/testplanet/uplink.go, pkg/kademlia/dialer_test.go, pkg/kademlia/kademlia_planet_test.go, pkg/transport/transport.go, uplink/config.go
A previous change reused the same timeout for dialing as well as
requesting in order to speed up some tests. This change introduces
a distinct timeout so that the different operations can have different
timeouts.
Discussed some previously at https://github.com/storj/storj/pull/1545#discussion_r268168062
---
**Note to reviewers:** I changed a config struct. I assume there's something I have to do about flags or whatever, but I don't know.
=> transport: separate dial from request timeouts

pkg/audit/newverifier_test.go
What: 
In newverifier_test.go, upload to a specific number of nodes, and check that the result returned by verifier.Verify determines the correct number of successful/failed/offline nodes
Why:
We should add more test cases for using the verifier over testplanet, and this test should be a basis for the others
=> check results in verifier test

pkg/eestream/decode.go
What: 
Fixes the calculation of error threshold during download. Before this change, `required+1` number good nodes were required for a successful download, whereas only `required` number of nodes are really necessary.
Why:
This issue failed downloads of files with lower RS scheme (like 2/4/6/8). If only one storage node was problematic, those downloads would fail.
=> Fix download error threshold

pkg/datarepair/checker/checker.go, pkg/datarepair/repairer/repairer.go, pkg/overlay/cache.go, pkg/storage/segments/repairer.go, pkg/storage/segments/repairer_test.go
What: 
Reassess what pieces needs to be rebuilt in repair just before repairs, so newly built pieces are not just overlap and also not sent to the same storagenode. 
Why:
There is a possibility that a piece is built and sent to already existing storagenode, causing info.db UNIQUE error
https://storjlabs.atlassian.net/browse/V3-1650
=> repair segment reassess it missing pieces just before repair

storage/postgreskv/client.go
Reverts storj/storj#1988
My own tests are showing the opposite; using 10000 is faster than 1000 with the setup I have (with PostgreSQL running on the same machine, macOS, and connecting to PG over a unix domain socket).
But as far as I can tell, defaultBatchSize _shouldn't_ affect these tests, so whether this change makes it faster or slower, I want to understand why before we commit the change.
=> Revert "storage/postgreskv: use batch size 1000"

pkg/storage/ec/client.go, pkg/storage/segments/repairer.go
What: 
1. Repair job should not cutoff longtail.
2. Commit repair pieces even if not hitting the success threshold
3. Remove useless condition.
Why:
1. Main objective for the repair job is file durability and not upload speed.
2. If we managed to upload to 79 instead of 80 nodes we should still write it back to the database. There is no reason to throw an error.
3. `healty > min && healty > success` is a bit useless. `healty > success` will produce the same results because `success > min`
=> Store repaired Segments and improve Repair Condition

pkg/storage/segments/repairer.go
What: 
reuse previous call to pointer.GetRemote().GetRemotePieces()
Why:
slightly better
=> call GetRemotePieces once

pkg/datarepair/checker/checker.go, pkg/storage/ec/client.go, satellite/metainfo/metainfo.go, satellite/metainfo/metainfo_test.go
What: Bugfix for the pair service.
Why: With v0.11.5 we removed an important counter. All repair tasks are failing at the moment.
=> v0.11.6 bugfix repair service

satellite/satellitedb/repairqueue.go
What: 
Use only database time in repair queue
Why:
Trying to track down a mystery bug, this will rule out one potential
=> using DB time only

cmd/uplink/cmd/setup.go
What: `uplink` CLI interactive `setup` returns an error when `--config-dir` flag is set.
Why: because the `--config-dir` value wasn't considered for creating the encryption key file and the default one was used, so if the directory didn't exist the file couldn't be stored and if it would have existed then the encryption file was not going to be stored where the user indicates.
**NOTE** commit message provides relevant information of the changes, please consider to read them if you have any doubt on it, before commenting/asking.
=> cmd/uplink: Fix error on interactive setup when --config-dir flag is used.

pkg/audit/verifier.go, pkg/audit/verifier_test.go
What: The `Verifier` type of the `pkg/audit` had a test which was totally ignored
due to a +build tag.
Why: Ignoring test using a `+build` is confusing because it isn't clear that
the test is fully ignored and the test doesn't get compiled anymore so
all the breaking changes in the implementation don't warm to update the
test.
This changes remove the +build tag and resuscitate the tests which
haven't required that much changes, the rest of them have been deleted.
=> pkg/audit: Readdress ignored Verifier tests

satellite/metainfo/metainfo.go, satellite/peer.go
What: Make sure pendingAudit entries associated with deleted segments are also deleted from ContainmentDB
Why: So that we don't audit nodes on deleted segments
Jira task: https://storjlabs.atlassian.net/browse/V3-1763
=> Delete pending audit entries from containment DB when files get deleted

internal/memory/size.go, internal/memory/size_test.go
What: 
Currently code checks whether size is larger than the threshold set for the unit used. Because negative numbers are always smaller, they are always displayed in bytes. Using absolute numbers when comparing ensures negative numbers are displayed in the appropriate unit. To be consistent when "0" is returned it should say "0 B" as well.
Why:
This issue causes strange negative numbers to appear on the storagenode dashboard when used space goes slightly over the available space on full nodes. And might appear in other places as well.
This change will display negative sizes numbers in a compact format, similar to positive ones.
This is a fix for minor issue #2055 
=> Use absolute size for unit calculation to account for negative numbers

pkg/process/exec_conf.go, pkg/process/exec_conf_test.go
What: fixes a bug introduced by #2068
Why:
when the code was changed to directly load values into the config
structs, it was missed that some configuration is only defined
through flags, but can be loaded from config files still.
so, we need to propogate the settings to the flag only values.
=> fix bug for setting flag only values in process setup

pkg/cfgstruct/bind.go, pkg/process/metrics.go, scripts/testdata/satellite-config.yaml.lock
What: this will make it so release binaries default to whatever-release instead of whatever-dev in metrics collection
Why: So we can monitor release binaries with default configuration without getting drowned out by dev binaries
=> process/metrics: have metrics suffix default to dev/release status

satellite/satellitedb/overlaycache.go
What: Transactions require calling either Rollback or Commit, otherwise the tx will be leaked.
Why:
=> satellitedb/overlaycache: avoid tx leak in case of error

internal/dbutil/defaults.go, internal/dbutil/pgutil/db.go, satellite/satellitedb/database.go, scripts/testdata/satellite-config.yaml.lock, storage/postgreskv/client.go, storagenode/storagenodedb/infodb.go
This sets the postgres connection limit. Currently during tally runs we're seeing spikes of 20k connections concurrently, which is bad. This doesn't fix the root cause but maybe helps us find it.
This also makes these values configurable, which is important for debugging and tuning. We'll need to clean up the configuration so it's not in flags and in our config system later.
=> db: set max open conns, conn max lifetime, add db stat monitoring

pkg/macaroon/serialize.go
What: monitor macaroon parsing/serialization
Why: validateAuth can take almost a second, but none of the other monitored subcalls take that long?
=> monitor macaroon parse/serialization perf

pkg/audit/service.go
What: Remove named result parameters
Why: because our coding style conventions
which for named result parameters follows the "Go Code Review Comments"
See: https://github.com/golang/go/wiki/CodeReviewComments#named-result-parameters
=> pkg/audit: Fix code style named result parameters

internal/testplanet/planet.go, pkg/datarepair/datarepair_test.go, pkg/discovery/service.go, pkg/discovery/service_test.go, pkg/kademlia/kademlia.go, pkg/kademlia/lookup_test.go, pkg/kademlia/routing.go, pkg/kademlia/routing_helpers_test.go, scripts/testdata/satellite-config.yaml.lock
What: remove the node graveyard and the kad seen map.
Why: the node graveyard is taking significant resources trying to ping dead nodes, which will almost certainly time out. the graveyard wasn't part of the whitepaper or spec anyway, and the other refresh and discovery processes will help find recovered nodes already (all the tests should continue to pass). the kad seen map is unnecessary entirely.
=> discovery: remove graveyard

satellite/peer.go
What: Fix `satellite/Peer.Run` method doc comment.
Why: It was copied and pasted from SN
=> satellite: Fix Peer.Run method doc comment

pkg/kademlia/kademlia.go
Fix a bug related with shadowing the assigned variable to the range loop
due to the reference is used rather than the value.
It was ignore by the _scopelint_ linter due to it was mistakenly marked as `nolin:`
=> pkg/kademlia: Fix bug using ref of var range loop

internal/testidentity/identity.go, lib/uplink/uplink.go
What: Set difficulty for libuplink and testplanet larger than 8
Why: We use last byte in the node id to store the version number, so the difficulty must be larger than 8.
=> Always use difficulty larger than 8 for identites

pkg/audit/verifier.go, pkg/audit/verifier_test.go
What: 
Audit service will download erasure shares in parallel (each share in a separate goroutine) instead of serially (one-by-one).
Why:
Better performance.
=> Audit service should download erasure shares in parallel

bootstrap/peer.go, pkg/discovery/service.go, pkg/overlay/cache_test.go, satellite/peer.go, storagenode/peer.go
What: 
Fixes https://storjlabs.atlassian.net/browse/V3-1901 by making sure nodes include the configured email in their self node info.
Why:
The satellite missed the email in the DB, because storage nodes were not returning it node info response..
=> Add email to self node info

cmd/uplink/cmd/share.go, lib/uplink/apikey.go
The APIKey Restrict method should be in lib/uplink so people can find it
=> lib/uplink: expose restrict on api keys

pkg/dht/dht.go, pkg/kademlia/endpoint.go, pkg/kademlia/inspector.go, pkg/kademlia/kademlia.go, pkg/kademlia/kademlia_test.go, pkg/kademlia/replacement_cache_test.go, pkg/kademlia/routing.go, pkg/kademlia/routing_helpers.go, pkg/kademlia/routing_helpers_test.go, pkg/kademlia/routing_integration_test.go, pkg/kademlia/routing_test.go, pkg/kademlia/testrouting/testrouting.go, pkg/kademlia/testrouting/utils.go
This makes monkit.Task trees look properly filled out, where routing calls now have correct ancestor information due to the context passing
=> kademlia/routing: add contexts to more places so monkit works

cmd/uplink/Dockerfile
We were building the uplink again for the container image. We should just copy in the release binary we've already built, like the other container images.
=> Use release build of uplink for container image

cmd/gateway/Dockerfile
Stop building the binaries inside the image and instead build them outside once then just package them in a container image.
=> Fix the gateway image build process

pkg/overlay/benchmark_test.go, pkg/overlay/cache.go, pkg/overlay/statdb_test.go, satellite/satellitedb/overlaycache.go
What: 
Remove Ratios from NodeCriteria
Simplified some inner select SQLs
Added missing Uptime criteria to one SQL statement.
Why:
NodeCriteria previously cared about AuditSuccessRatio and UptimeSuccessRatio. These need to go away away as part of the reputation refactor w/ alpha and betas.
Found some small things to clean up along the way.
=> removed fields

lib/uplinkc/convert.go, lib/uplinkc/uplink_definitions.h
What: Fix this error on osx when doing things like `go install`:
```
lib/uplinkc/convert.go:16:17: could not determine kind of name for C.time_t
```
Why:
=> fix `C.time_t` error

internal/testplanet/dir.go, internal/testplanet/planet.go
What: testplanet was missing config for address which was trying to open public ports.
Why:
- Test 1:
- Test 2:
=> internal/testplanet: add missing consoleserver.Config

pkg/encryption/password.go, pkg/encryption/password_test.go
This commit adds two functions that implement the algorithms
described in the password key derivation design document. They
will be used during setup to derive bucket level root keys or
default passwords to use when buckets do not have their own
independent key.
The code is not yet used, so there is no testing or performance impact.
=> add functions for password/root key derivation

pkg/discovery/service.go
What: 
The discovery refresh service won't ping disqualified nodes.
Why:
Satellites are not interested in maintaining up-to-date info and stats for disqualified nodes. So it can save the resources for pinging them too.
- Test 1:
- Test 2:
=> Stop pinging disqualified nodes

internal/testplanet/uplink_test.go, pkg/datarepair/datarepair_test.go
What: TestDataRepair and TestUplinksParallel are being flaky there is https://github.com/storj/storj/pull/2335 to fix the flakiness in DataRepair. Disable for now to prevent merging other changes.
Why:
- Test 1:
- Test 2:
=> Skip TestDataRepair and TestUplinksParallel, because they are flaky

pkg/audit/disqualification_test.go, web/satellite/src/components/referral/ReferralStats.vue
What: Take the disqualified storage node and give it a high uptime and audit rate. 
Why: To check that disqualification is permanent
- Test 1:
- Test 2:
=> [v3-1952 test 6] Disqualification is a one way ticket. Storage Node can't get around it.

internal/testplanet/uplink.go, pkg/audit/verifier.go, pkg/storage/ec/client.go, uplink/piecestore/client.go
What: Connection was passed into piecestore.NewClient, however it was internally closing the connection. The expected behavior usually is that the caller is responsible for closing things. Rename the method to `Dial` and dial the connection internally, such that the behavior is clearer.
Why:
- Test 1:
- Test 2:
=> Make piecestore.Dial handle the connection completely.

internal/errs2/ignore.go, pkg/kademlia/kademlia.go, pkg/kademlia/peer_discovery.go, storagenode/piecestore/verification.go, storagenode/trust/service.go, storagenode/trust/service_test.go, storagenode/vouchers/verification.go
What: `context.Canceled` was not being propagated from peer discovery to `GetSignee`.
Why:
- Test 1:
- Test 2:
=> Fix TestGetSignee flakiness

Jenkinsfile.gerrit, Jenkinsfile.public, cmd/uplink/cmd/cp_test.go, internal/testrand/rand.go, pkg/kademlia/peer_discovery.go
What: previously during start of the test it was creating random data
Why:
- Test 1:
- Test 2:
=> cmd/uplink/cmd: don't create benchmark data on init

Dockerfile.jenkins, Jenkinsfile.gerrit, Jenkinsfile.public, pkg/kademlia/peer_discovery.go
What: Previously docker containers were left running for some reason. Add an explicit timeout to the container itself to ensure it gets shutdown.
Note the limit for Jenkins is still 10min, but if it doesn't properly cleanup after 10min, it will fallback to stopping the main process at 18min and killing at 20min.
Also removes some test code from kademlia.
Why:
- Test 1: manually tested the `timeout -k20m 18m` part.
- Test 2:
=> jenkins: Stop docker container after 18m

lib/uplink/project.go
What: Sets the default erasure share size in libuplink to 256 bytes.
Why: The value was 1 KiB, which was out of sync with default uplink settings, and the validation config on the satellites. This way bucket created with libuplink had invalid redundancy configuration and all uploads were rejected by the satellite with `provided redundancy scheme parameters not allowed`.
- Test 1:
- Test 2:
=> Set correct default erasure share size for libuplink

go.mod
What: Add go 1.12 release to go.mod, so that it doesn't automatically change when using go 1.13.
Why:
- Test 1:
- Test 2:
=> go.mod: enforce go 1.12

pkg/storage/segments/repairer_test.go
What: 
Abort the repairer test when asserting results which are required later
on by the test for being able to continue.
Why:
Asserting the results for results which are required later on by the test can provoke test panics whose shows uglier and less understandable test failure messages. Also a failed test will ends earlier.
Please describe the performance impact: In case that the test fails, it will finish earlier, so there could be some gain on the total amount of time that the test run takes in such specific case.
=> pkg/storage/segments: Abort repaired test unmet requirements

pkg/audit/reporter_test.go, pkg/audit/reverify_test.go, pkg/audit/verifier_test.go
What: A few things are cleaned up in audit tests:
- Existing Cursor and Verifier are reused from the satellite instead of always creating new ones. New Verifier is created only if necessary to pass a custom config in the constructor.
- Some test code used `zap.L()` instead of testplanet's logger.
- Some tests used 6 storage nodes where only 4 would be enough
- Some tests upload 1 MiB of test data where only 8 KiB would be enough
Why: Housekeeping, faster test execution and easier maintenance
- Test 1:
- Test 2:
=> Audit tests cleanup

storagenode/console/service.go, storagenode/nodestats/service.go
What:  Storagenode nodestats client add daily space usage 
Why: To display daily disk space usage on dashboard
- Test 1:
- Test 2:
=> Storagenode nodestats client add daily space usage

internal/testplanet/satellite.go
What: Set `MinDownloadTime` audit config to 5s in testplanet.
Why: It was `0` until now, so the calculated timeout applied, which was too low (few ms) and some test may fail due to this.
=> Set MinDownloadTimeout to 5s in testplanet

scripts/protobuf.go
Regenerating protobuf keeps adding godebug to go.mod, remove the dependency by using command-line diff instead.
- Test 1: manually running things
- Test 2:
=> scripts/protobuf: use command-line diff

satellite/metainfo/metainfo.go, satellite/metainfo/metainfo_test.go
What:
Bug fix
https://storjlabs.atlassian.net/browse/V3-2001
Why:
Root cause:
The expiration time when set, was checked at the user’s uplink or libuplink end. If the user changes the code to accept it, the satellite should also check the validity of the time before segments are created. Per the problem stated and upon looking at the satellite’s metainfo createsegment() I see satellite accepts ANY expiration date. The root cause is the satellite should filter invalid expiration times before it goes any further. Changing just the error is not the root cause.
Test 1:
TestExpirationTimeSegment()
Test 2:
=> adding expiration date check on satellite's CreateSegment

pkg/discovery/service.go
this will reduce the amount of network operations and roundtrips in successful cases by a factor of 2
still todo: combine the db updates
Please describe the performance impact: have to hit the node only once instead of twice
=> discovery: use fetch info to ping

internal/testplanet/storagenode.go, storagenode/collector/service_test.go, storagenode/piecestore/verification.go
What: Use the smaller of the two expiration times in the piecestore for the order limits 
Why: So that the database is much smaller.
- Test 1:
- Test 2:
Please describe the performance impact: Should help with database load.
=> storagenode: use minimum time in the order for expiration

storagenode/collector/service_test.go, storagenode/pieces/db_test.go, storagenode/piecestore/serials_test.go, storagenode/storagenodedb/bandwidthdb.go, storagenode/storagenodedb/pieceinfo.go, storagenode/storagenodedb/usedserials.go
this way comparison happens on the actual time rather than the
string representation of the time which may change depending on
the time zone.
What: Wraps timestamp columns with `datetime()` in queries 
Why: So that sqlite does the right comparison
- Test 1:
- Test 2:
Please describe the performance impact: Minimal?
=> storagenodedb: use datetime functions in sqlite queries

pkg/storage/segments/store.go
otherwise, api key restictions will fail because we look like we're
asking to put to the bucket metadata path.
What: Puts the object path in every CreateSegment request
Why: So that we can accurately apply macaroon caveats
- Test 1:
- Test 2:
=> segments: send in the object path to the initial CreateSegment call

mobile/apikey.go, mobile/encryption.go, mobile/libuplink_android/app/src/androidTest/java/io/storj/mobile/libuplink/LibuplinkInstrumentedTest.java
this exposes a way to have keys deeper than the bucket root
What: Adds a new EncryptionAccess constructor that takes paths
Why: To allow keys to exist deeper than at the bucket level
- Test 1:
- Test 2:
=> mobile: add a way to get an encryption access at some path root

storagenode/piecestore/endpoint.go, uplink/piecestore/upload.go
What: 
ensure uplink is sending correct size with PieceHash
Why:
If we verify that the size matches reality, we can then expect to use the actual piece _file_ size to store the piece size as given in the signed `PieceHash` from the uplink. Otherwise, the uplink might send a garbage size value, leaving the storagenode with no good way to verify the uplink signature on the PieceHash at a later date, unless we explicitly track what the uplink *sent* as the piece size, which seems like just a waste of bytes and a potential source of confusion when we have multiple sources of truth.
This was motivated by ongoing work to move pieceinfo data into piece files and out of the sqlite database.
Also fix the code in `uplink/piecestore/` so that it sends a valid size, because it was being rude and …
=> ensure uplink is sending correct size with PieceHash

satellite/gc/piecetracker.go, satellite/gc/service.go
What: Fix a data race in the current garbage collector open PR (look at the branch where this PR should be merged which is **NOT MASTER**)
Why: Because otherwise we may have a data race in production
Please describe the tests: Unfortunately none. I wrote a test which showed the data race however once it was fixed the test was sometimes crashing because it was finished before an internal goroutine used by the implementation ended, causing a panic error. We decided not to spend much time in trying to have a test which could detect the data race but it was not flaky at the same time.
=> satellite/gc: Fix data race with last piece counts map

internal/testcontext/context.go, pkg/datarepair/checker/online.go, pkg/datarepair/checker/online_test.go
What: Make the reliability cache safe for concurrent access. We make it so the fast path does not have any contention when the cache state isn't stale.
Why: It's used concurrently.
- Test 1:
- Test 2:
=> repair: fix data race in reliability cache

storagenode/storagenodedb/utcdb.go, storagenode/storagenodedb/utcdb_test.go
What: see pr title
Why: so that we have better coverage of passing utc timestamps
- Test 1:
- Test 2:
=> enable utccheck in all tests by default

storagenode/storagenodedb/bandwidthdb.go, storagenode/storagenodedb/infodb.go, storagenode/storagenodedb/pieceinfo.go
What: Move the fields to the top of the struct
Why: So that 64 bit alignment is easier to audit
- Test 1:
- Test 2:
=> remove struct to ensure 64bit alignment for atomics

cmd/storj-sim/network.go, cmd/storj-sim/process.go, internal/testplanet/storagenode.go, pkg/transport/fetchidentity.go, pkg/transport/slowtransport.go, pkg/transport/transport.go, storagenode/peer.go, storagenode/piecestore/endpoint.go, storagenode/piecestore/endpoint_test.go, storagenode/trust/service.go
Ensure that we directly dial the whitelisted satellites instead of going through kademlia.
To implement, it sets up a custom credentials which captures the auth info during the initial handshake, this avoids the necessity for a separate Endpoint for fetching information.
As a consequence it also removes ability to trust all satellites, which was a bad idea in the first place.
Why: Currently kademlia lookups keep failing, however it's much faster and reliable to dial directly.
- Test 1:
- Test 2:
=> storagenode/trust: implement fetching peer identity without kademlia and endpoint

storagenode/peer.go, storagenode/storagenodedb/storagenodedbtest/run_test.go
What: 
Disable storagenode bandwidth rollups
Why:
Duplicate rollups causing issue with some storagenodes
Bandwidth usage will still be reported correctly b/c the queries UNION the bandwidth_usage and bandwidth_usage_rollup tables.
- Test 1:
- Test 2:
=> Disable bandwidth rollups until duplicate data issue is resolved

satellite/satellitedb/migrate.go
What: Use var block and remove some spaces at the end of lines.
Why: To have more consistent godoc format
Before this change the godoc format is rendered as
While in other packages we have used blocks for a single var declaration at package level. For example
I consider that when there is more than block of error variables, it's easier to read that all the different variables declared in different files of the same package be defined in blocs.
=> satellite/satellitedb: Use var block for single variable declaration

cmd/identity/main.go
What: Disables the PeerCAWhitelist config to let our identity tool reach out to the CA properly.
Why: Its refuses the identity tool to sign identities -> Chicken-Egg Problem
Solves https://github.com/storj/docs/issues/98
=> Ensure we dont enforce a signed Peer Identity during the Authorize command

lib/uplink/uplink.go
What: 
If cfg.Volatile.Log is nil we pass a global Logger instead of a no op logger
Why:
If the satellite doesn't provide a logger, we still want to be able to debug the system 
- We see logs again
=> Swaps NO OP logger for Global Logger

internal/testplanet/storagenode.go, storagenode/piecestore/endpoint.go, storagenode/piecestore/endpoint_test.go
What: 
Make it possible for SNOs to configure retain requests to be enabled, disabled, or in debug mode.
The default setting for RetainStatus is "disabled", which will ignore retain requests from the satellite.
Why:
In the future, we will want to enable garbage collection on the satellite. But we may want to be more careful before we fully enable garbage collection everywhere. With this change, we will be able to set retain requests on the storagenode to "debug", which will log the pieces to be deleted and the number of pieces to be deleted, without actually deleting them. It should allow us to verify that garbage collection works as intended before doing it for real.
https://storjlabs.atlassian.net/browse/V3-2232
- Test 1:
- Test 2:
Please describe the …
=> Add RetainStatus to storagenode config

cmd/gateway/main.go, cmd/uplink/cmd/setup.go
What: Fixes a regression introduced with #2637.
Starting with #2637, the `uplink setup` and `gateway setup` commands contact the satellite for the generation of the salted encryption key from the configured passphrase. The libuplink was not initialized with the correct TLS settings and the call to the satellite may fail with `transport: authentication handshake failed: tls peer certificate verification error: not signed by any CA in the whitelist: CA cert`.
Why:
- Test 1:
- Test 2:
=> Initialize correctly libuplink for `uplink setup` and `gateway setup`

storagenode/peer.go
What: 
Fix the nil check before close
Why:
Causes issue if Bandwidth service wasn't created
- Test 1:
- Test 2:
=> Check nil against Bandwidth service not DB before calling Bandwidth

storagenode/piecestore/endpoint.go
What: Make an exported method of the endpoint to be unexported
Why: because there is no need for being exported and keeping unexported ease refactorings.
Please describe the tests: There is no need for them if everything compiles.
Please describe the performance impact: None.
=> storagenode/piecestore: Make method unexported

bootstrap/peer.go, cmd/bootstrap/main.go, cmd/gateway/main.go, cmd/identity/main.go, cmd/satellite/main.go, cmd/storagenode/main.go, cmd/uplink/cmd/root.go, examples/eestream/serve-collected/main.go, examples/eestream/serve/main.go, examples/eestream/store/main.go, internal/version/service.go, lib/uplink/uplink.go, pkg/certificates/config.go, pkg/kademlia/routing_helpers_test.go, pkg/process/debug.go, pkg/process/metrics.go, pkg/server/config.go, pkg/telemetry/client.go, pkg/telemetry/client_test.go, pkg/telemetry/example_test.go, pkg/telemetry/tm_test.go, satellite/peer.go, storagenode/peer.go, uplink/ecclient/client.go, uplink/eestream/decode.go, uplink/eestream/encode.go, uplink/eestream/piecebuf.go, uplink/eestream/rs_test.go, uplink/eestream/stripe.go, versioncontrol/peer.go
What: Don't use global loggers to ensure that the messages are properly scoped and silenced (when requested).
Why:
- Test 1:
- Test 2:
=> don't use global loggers

storagenode/bandwidth/db_test.go
What: 
Test was using local date instead of UTC
Why:
Test fails at offset at the end of the month
- Test 1: Change clock to be within offset of UTC the last day of the month and execute test
- Test 2:
=> Fix TestCachedBandwidthMonthRollover test

docs/design/TEMPLATE.md
What: remove _"title"_ word from the title header. 
Why: because there is no need to mention that's the title of the document.
=> docs/design: Remove "Title" word from title header

cmd/satellite/main.go
What: Add 24 hours to the end day to account properly
Why: It is weird to account from 01st to 01st of the next month.
=> Add 24 hours to account for the entire rest of the end day when do accounting exports

lib/uplinkc/testdata/require.h
What: Add a new line the require macros' print statements.
Why: So that the shell prompt starts on a new line when a require assertion fails.
N/A
N/A
=> C require macros improvements

storagenode/pieces/store.go, storagenode/piecestore/endpoint.go, storagenode/piecestore/endpoint_test.go, storagenode/storagenodedb/pieceinfo.go, storagenode/storagenodedb/pieceinfo_test.go
What:
Update `pieceInfo.GetPieceIDs` to use a cursor rather than a numeric offset to allow us to more easily iterate when deleting pieces during retain requests.
Why:
- Test 1:
- Test 2:
=> Fix retain request iteration in debug mode

satellite/overlay/combinedcache.go, satellite/overlay/keylock.go, satellite/overlay/keylock_test.go, satellite/overlay/service.go, satellite/overlay/statdb_test.go, satellite/peer.go
What: We frequently call UpdateAddress in the overlaycache. This is causing issues with database performance. This is a quick fix that reduces those calls.
It adds an in-memory cache that checks whether the address has changed from before in the UpdateAddress call.
Why: Database performance is suffering due to so many UpdateAddress calls.
- Test 1: New unit tests confirm that the caching mechanism works as designed.
Please describe the performance impact: This should great improve database performance by greatly reducing UpdateAddress calls.
=> satellite/overlay: reduce calls to UpdateAddress

.github/CODEOWNERS
specify architecture owners for design doc reviews
=> architecture-owner codeowners for design docs

pkg/identity/identity.go, pkg/identity/identity_test.go
What: Updates the Identity packet to support encoding/decoding of the peer Identity to/From bytes, which can be used to save the whole chain of peer identities in database that stores these information. 
Why:
This PR  is a sub task of the a big feature as described in V3-1992 epic. The V3-1992 will be divided into 6 PRs. This is the first of the 6 PRs.
**The 6 PRs would be as shown below:**
1.  make the encode /decode changes  into the pkg/identities ( PR #2754 )
2. remove certdb (because the design changed quite drastically)
3. implement new certdb (dbx and interface and tests)
4. fix those bootstrap error outputting debug info
5. fix the segment debug outputing info (edited) 
6. wire up the new certdb (edited) 
- Test 1:adds test function to encode
- Test …
=> Updates the pkg/identity support encode and decode functionality of Peer Identity information

satellite/gc/service.go, scripts/testdata/satellite-config.yaml.lock
What: Enable garbage collection on the satellite side. Don't enable it on the storage node.
Why: Garbage collection is working great on the satellite side. We don't see any performance impact. We can go ahead and enable it on all satellites. On the storage node side we can't because there is an annoying timeout issue.
- Test 1:
- Test 2:
=> satellie/gc: enable garbage collection on the satellite

internal/testplanet/uplink.go, lib/uplink/bucket.go, lib/uplink/list_test.go, lib/uplink/object.go, lib/uplinkc/object.go, mobile/bucket.go, storagenode/piecestore/endpoint_test.go, uplink/metainfo/kvmetainfo/objects_test.go, uplink/stream/download.go
We currently don't support an efficient Seek interface, so it is better to not expose it for the time being. This PR removes support for Seek.
Supersedes #2299, however, the object information addition would be a separate PR.
- Test 1:
- Test 2:
=> lib/uplink: remove Seek method

storagenode/orders/db_test.go, storagenode/piecestore/endpoint_test.go
What: Add more test cases for empty piece ID.
Why:
Because we have a reported issue from one Storage Node Operator which cannot list the unsent order limits and it looks that the issue is that there is one order limit in the DB which has an empty piece ID.
The new tests pass without any change in the implementation but it's good to have them.
The goal was trying to find out the root of the problem of the ticket [V3-2400](https://storjlabs.atlassian.net/browse/V3-2400) but I ended up also adding a bit more assertions not related to it.
Please describe the tests: Added more assertions to current tests, there is no change in the implementation so there are no new tests.
Please describe the performance impact: none.
=> storagenode: Add more test assertions

satellite/orders/orders_test.go, uplink/piecestore/download.go
What: Handle errors better such that we can call close without context cancellation problems. This should also get rid of the potential double closing of download.
Why:
- Test 1:
- Test 2:
=> uplink/piecestore: handle Download errors better

cmd/certificates/main.go, pkg/cfgstruct/bind.go
What: certificates binary was panicking due to private field.
Why:
- Test 1:
- Test 2:
=> cmd/certificates: ensure we can bind config values

satellite/satellitedb/overlaycache.go
What: Add missing audit and uptime success count to `overlay.NodeStats` struct while filling `overlay.NodeDossier` struct in `overlay.DB`
Why: That info is missing even thought it is defined. It is needed for displaying audit and uptime success ratio on SNO dashboard.
- Test 1:
- Test 2:
=> satellite/overlaycache: add missing audit and uptime success count

lib/uplinkc/testdata/object_test.c
The download driver code loops through the downloaded_data buffer
but doesn't ensure that it always passes a valid pointer to the
Go side. In particular, if the malloc'd memory ends against an
unmapped page, and the test passes a pointer one past the end
of the memory region, and since the Go side always dereferences
the pointer when creating a slice, it will attempt to read
unmapped memory, causing a segfault.
This bug doesn't always present. Indeed, it depends on the details
of your system's memory allocator. I validated that this could be
a cause of observed crashes on OS X by using mmap and mprotect
to do the allocations ensuring that the page directly after the
memory we use was unmapped/protected. The crash happened exactly
as seen, and was fixed by changing this condition in the …
=> lib/uplinkc: fix flaky download test

storagenode/orders/db_test.go, storagenode/orders/sender.go, storagenode/storagenodedb/orders.go
What: A new method on the ordersDB to delete items in the archive that are older than a specific time.Duration
Why: Currently there is no deletion from the order_archive_ table. It will continue to grow indefinitely unless the user manually deletes items 
https://storjlabs.atlassian.net/browse/V3-1979
- Test 1:
- Test 2:
=> storagenode/orders: add ordersDB method CleanArchive

Dockerfile.jenkins, Makefile
I've tested a 6x speed up of the identity tool aarch64 vs arm32v6 on the same hardware. The current raspberry pi build using rasbian can't get this same speed up. This does provide a binary and contianer images for when a aarch64 upgrade path for the current build is in place.
=> build: update to go 1.12.9, build everything for aarch64

satellite/repair/repair_test.go
What: `testplanet.Run` is running concurrently and hence there might be concurrent writes to `repairMaxExcessRateOptimalThreshold`.
Why:
- Test 1:
- Test 2:
=> satellite/repair: fix data race in tests

storagenode/nodestats/cache.go, storagenode/nodestats/cache_test.go
What: time.Duration is an int64, so casting it down to an int can cause it to become negative, causing a panic.
Why: We have panics on arm :(
- Test 1:
- Test 2:
=> storagenode/nodestats: fix issue on 32 bit platforms

satellite/marketingweb/server.go
What: WriteHeader should only be called once, see https://golang.org/pkg/net/http/#ResponseWriter
Why:
- Test 1:
- Test 2:
=> satellite/marketingweb: WriteHeader should only be called once

satellite/console/usercredits_test.go, satellite/repair/queue/queue2_test.go
What: Database tests are about the interface that things provide and less about the database internals. Move tests near the interface.
Why:
- Test 1:
- Test 2:
=> satellite/satellitedb: move tests near the interface

cmd/bootstrap/main.go, cmd/gateway/main.go, cmd/satellite/main.go, cmd/storagenode/main.go
What: Changes the Log Level from Error to Warn for disabled telemetry sending.
Why: Its makes error finding much harder when spammed with Error Messages
- Test 1: N/A
- Test 2: N/A
Please describe the performance impact: _Improves Debug Speed_
=> cmd/*: Change loglevel from error to warn

satellite/gc/service.go
What: Monkit must be called on chore `Run` functions
Why: Because it causes only a little overhead, the opposite that I thought and I reported in the review of the GC, so it was removed due to my fault.
See conversation in https://storj.slack.com/archives/CAQV0AE2Z/p1566923238294400
=> satellite/gc: Service run must call mon.Task

pkg/process/debug.go
what: take prometheus help messages out
why: the current prometheus help messages have enough unexpected characters that they are breaking prometheus parsing. they may also be triggering prometheus to expect more from us (type annotations) than we have to offer.
we're really not adding a lot of value with these help messages, so just take them out
Please describe the tests: no tests, because i don't want to import prometheus as a dependency just to test this one thing.
=> pkg/process: remove prometheus help

storagenode/orders/service.go
What: Reduce orderarchive TTL from 45 to 7 days.
Why: Because we reduced the order expire date from 45 to 7 days on the satellite side and storing it for 45 days is wasting too much space (info.db)
- Test 1:
- Test 2:
=> storagenode/orderarchive: Reduce TTL from 45 to 7 days

pkg/process/debug.go
what: add the type to prometheus messages
why: im trying to export prometheus metrics to stackdriver but it keeps erroring with an untyped error.
Please describe the tests: no tests, because i don't want to import prometheus as a dependency just to test this one thing.
=> add type to prometheus metrics

web/satellite/.gitignore, web/satellite/package-lock.json, web/satellite/package.json
What: pin all of our npm versions
Why: typescript released a new version and broke us. https://devblogs.microsoft.com/typescript/announcing-typescript-3-6/#dom-updates
- Test 1:
- Test 2:
=> web/satellite: downgrade typescript and pin stuff

pkg/process/debug.go
What: also allow digits during metric name sanitation
Why: cause they're totally valid to allow
Please describe the tests: don't want to include prometheus in tests just for this
=> pkg/process prometheus: forgot digits

storagenode/orders/service.go, storagenode/peer.go
What: Workaround for issue with sending orders from storage node to satellite. Orders service is getting custom transport with request timeout configured via new flag `--storage2.orders.sender-request-timeout duration`.
Why: https://storjlabs.atlassian.net/browse/V3-2558
- Test 1: none
=> storagenode: Increase order sending request timeout

pkg/server/interceptors.go
What: Replace the usage of the Sugared logger by the normal one.
Why: Sugared logger performs worse and it isn't structured.
Please describe the tests: N/A 
Please describe the performance impact: Not measured, but it should perform faster when logging the messages.
=> pkg/server: Don't use Sugared logger

docs/design/storage-node-downtime-tracking.md
What: Adapt Storage Node Downtime tracking design document to be a blueprint
Why: Because we have agreed to swap design documents for blueprints and this document has been recently merged and its implementation has not started.
Please describe the tests: N/A 
=> docs/design: Adapt Storage Node Downtime tracking to be a blueprint

storagenode/orders/service.go, storagenode/peer.go
What: Set custom dial timeout for storage node orders sending (default changed from 20s to 1m). Also parameter for configuring this timeout added - ` --storage2.orders.sender-dial-timeout` .
Why: Some storage nodes are not able to send orders because 20s of dialing to the satellite is not enough for them.
- Test 1: none
=> storagenode: add custom dial timeout for orders sending

Jenkinsfile.public, go.mod, go.sum, scripts/test-sim-backwards.sh
What: 
Adds a `replace` directive to `go.mod` which causes Go to use the Apache Thrift module from github instead of the one at git.apache.org (which is no longer reachable).
Why:
I got really tired of the errors with Go being unable to fetch git.apache.org/thrift.git. Apparently, Thrift development officially moved to Github quite some time ago anyway. See:
https://github.com/apache/thrift/commit/9ee29516c419b7eaa95ed89a93b135ea1c683576
So this `replace` directive causes opencensus.io/foo to use the correct url for the thrift module. Until opencensus.io fixes its dependencies:
https://github.com/census-instrumentation/opencensus-go/issues/1158
this might be the only recourse.
- If Jenkins can build at all, this functionality is working.
Please describe the …
=> jenkins: work around git.apache.org failures

satellite/satellitedb/orders.go
What: Always release savepoints and wrap errors.
Why: Not releasing a savepoint can cause nasty deadlocks and not wrapping errors make difficult to identify from where they are generated.
Please describe the tests: No new tests. I haven't found a way how to have a test which could reproduce the problem of not releasing the savepoint. 
Please describe the performance impact: Wrapping errors always produce some performance impact, but it's necessary and the impact should be negligible.
=> satellite/satellitedb: always release savepoint in process orders

bootstrap/peer.go, satellite/peer.go, storagenode/contact/service.go, storagenode/peer.go
What: 
Adds contact services and endpoints as necessary to satellite and storagenode.
Why:
We will need these once we remove kademlia.
- There is not really any new behavior to test right now; if anything works at all once we start using these facilities, then this change works.
None
=> satellite,storagenode,bootstrap: add contact service to peer

satellite/repair/repair_test.go
What: 
Decrease the maximum threshold for uploads during repair tests.
Why:
We recently merged a PR which now only requires the minimum threshold number  of pieces to properly repair. However, we didn't update other values in the test, which means in some circumstances when the total number of pieces are uploaded to, there are not enough remaining nodes to repair on.
- Test 1:
- Test 2:
=> Fix flaky repair tests

pkg/process/exec_conf.go, pkg/process/metrics.go, pkg/telemetry/client.go
What: Currently both failing to start telemetry and failing to start debug ports displays huge messages about not being able to start. This disables stack trace for these messages since it's cleaner. 
There shouldn't be a problem in trying to figure out where the error came from since there's only one place where it can happen for a given process.
Why:
- Test 1:
- Test 2:
=> pkg/process: reduce noise in storj-sim

internal/migrate/versions.go, internal/migrate/versions_test.go, satellite/satellitedb/migrate.go, satellite/satellitedb/migrate_postgres_test.go, storagenode/storagenodedb/database.go, storagenode/storagenodedb/migrations_test.go
What: This PR makes our migration code support separate dbs for each migration step.
Why: Now that we are splitting the storagenodedb into various databases, we need a way to migrate separate dbs on each step.
- Test 1: Existing tests are updated to ensure it works to embed the db in the step.
=> migrate: Allow work on separate dbs

satellite/metainfo/service.go, satellite/repair/repair_test.go, uplink/storage/streams/store_test.go
What: 
When we initially commit a segment (`satellite/metainfo/metainfo.go`), we iterate over all the pieces in the pointer and set `piece.Hash = nil` for each one before storing them in the database. This is to reduce overhead, since we only need the piece hashes for initial verification of the upload.
When we repair, it does not look like we are doing this anywhere. This PR sets those hashes to nil before replacing the pointer in metainfo.
**Unfortunately, this probably means that there are many pointers in metainfo that have been repaired that contain unnecessary piece hashes. We may want to run a migration at some point to get rid of these.**
This PR also removes a flawed check which compares `existingPiece.Hash` (which should always be `nil`) to `piece.Hash` (which will not …
=> satellite/metainfo: make piece hashes nil before storing pointer in metainfo.UpdatePieces()

satellite/repair/repair_test.go, satellite/repair/repairer/ec.go, satellite/repair/repairer/segments.go
What: 
delete corrupted piece from pointer during repair.
Why:
If a piece failed piece hash verification, we should remove it from pointer
- Test 1:
- Test 2:
=> satellite/repair: delete pieces that failed piece hashes verification from pointer

storagenode/storagenodedb/database.go, storagenode/storagenodedb/satellites.go
**What:** Add business object placeholders for the new satellite tables `satellites` and `satellite_exit_progress`. This adds an empty placeholder object for the data access to the new tables and hooks it up to the initialization logic.
**Why:** I'm adding this before @VinozzZ has worked on the data access code because I have a parallel PR that splits up the storage node sqlite3 databases and it's going to be a lot less painful and easier for both of us to merge having this wired up ahead of time.
- Test 1:
- Test 2:
=> Add satellites database business objects.

satellite/audit/worker.go
What: 
- set devDefaults for ChoreInterval and QueueInterval to 1m
Why:
- they were respectively set to 24h and 1h in storj-sim which led to some unhelpful testing
- Test 1:
- Test 2:
=> satellite/audit: set devDefaults for ChoreInterval and QueueInterval to 1m

internal/dbutil/sqliteutil/migrator.go, internal/dbutil/sqliteutil/migrator_test.go
What: Add a function `MigrateTablesToDatabase` to migrate from one `*sql.DB` to another, able to specify which tables you want to keep.
Why: To support splitting storagenodedb into multiple sql databases, we need a simple way to migrate from one db to another.
- Test 1: `TestMigrateTablesToDatabase` ensures we are migrating properly.
- Test 2: `TestKeepTables` ensures that function is working as expected.
=> internal/dbutil/sqliteutil: add MigrateTablesToDatabase

pkg/transport/common.go
What: It seems that under load the go scheduler can get a bit unfair. Increase the request timeout to 10 minutes, to avoid potential issues.
Why:
- Test 1:
- Test 2:
=> pkg/transport: set default timeout to 10 minutes

pkg/kademlia/endpoint.go
What/Why:
We are removing kademlia, but in the meantime, the debug log is becoming noisy and its not useful info so we are removing it.
n/a
n/a
=> rm noisy debug logs that we dont need

satellite/metainfo/loop.go, satellite/metainfo/metainfo.go, satellite/repair/checker/checker.go, satellite/repair/checker/checker_test.go, scripts/test-backwards.sh, scripts/test-uplink.sh, uplink/storage/segments/store.go
What: With migration to new metainfo API I missed a case when the last segment can be inline segment. For example, there is such a case when file size is multiplication of max segment size. 
Why: We had a bug where files uploaded with old uplink were not accessible because new uplink was not able to get redundancy scheme values.
- Test 1: backward compatibility test and test-sim tests updated
- Test 2: to test manual try upload file with the previous release and download with master/this branch
Please describe the performance impact: overhead should be minimal
=> uplink/satellite: fix for case when inline segment is last one

satellite/audit/reverify_test.go, satellite/audit/verifier.go
What: 
Make sure we are auditing contained nodes for the share stored in the containment db rather than from the path passed into Reverify()
Why:
Containment mode is not currently auditing the piece that a node was contained for when audit reverify occurs. Instead, it appears to be auditing the piece for the contained mode associated with the segment picked up for the audit worker.
- Test 1:  Add a test that does the following:
* Upload two files to storj-sim
* Pick a node that contains a piece for both files
* Create a pending audit entry for the storagenode for file 1
* Delete the piece the selected storagenode is storing for file 1
* Call audit.Reverify with file 2
* Expect that the storagenode fails the audit even though it would have passed if audited for …
=> satellite/audit: fix containment mode

satellite/metainfo/metainfo.go
What: Fix metainfo.GetObject method to catch `storage.ErrKeyNotFound` in correct way. The issue was with older inline uploads where number of segments were encrypted. 
Why: Without this fix we are not able to download old inline files.
- Test 1: TBD
=> satellite/metainfo: fix GetObject method

cmd/storagenode-updater/main.go
What: Rename `auto-updater` to `storagenode-updater`. 
Why: Because old name is not storage node specific.
- Test 1: none
=> cmd: rename auto-updater to storagenode-updater

internal/testplanet/uplink_test.go
What: Reenable TestUplinksParallel hoping it won't cause "transport is closing" flakiness again with the improved timeouts.
Why:
- Test 1:
- Test 2:
=> internal/testplanet: enable TestUplinksParallel

cmd/certificates/auth.go, scripts/test-certificates.sh
What: Fix certificates auth export switch logic.
Why: `--emails-path` wasn't working correctly.
Please describe the tests: None. This command is partially tested in scripts/test-certificates.sh but that script is currently disabled as it's flaky with plans to re-implement in go.
=> fix certificates auth export command

Jenkinsfile.public
What: test-certificates tests are flaky. Disable since they cause failures and will be eventually rewritten in Go, which will show better the reasons.
Fixing is tracked in https://storjlabs.atlassian.net/browse/V3-2621
Why: https://build.dev.storj.io/blue/organizations/jenkins/storj/detail/PR-3103/2/pipeline
- Test 1:
- Test 2:
=> jenkins: disable flaky test-certificates

internal/version/service.go, scripts/testdata/satellite-config.yaml.lock
What: changes the service to ask version.storj.io instead of version.alpha.storj.io
Why: It allows autoupdating
=> internal/version: Change default endpoint to query

Makefile
This change makes binaries smaller by stripping some debug information from go binaries. I'm not 100% sure this is going to work for us as I'm not 100% sure on how monkit gathers debug information during crashes.
=> Make binaries smaller

installer/windows/Storj/CustomAction.cs
What: Windows installer always uses US locale when parsing numbers from user input.
Why: To make it work for users with another default locale, like German.
=> Fix locale to "en-US" when parsing numbers

scripts/check-large-files.go
What: .build will contain different artifacts, so they might exceed the 650KB limit.
Why:
- Test 1:
- Test 2:
=> scripts: ignore .build directory for size checks

pkg/rpc/rpcstatus/status_drpc.go
What: Fix return of rpcstatus.Code.
Why: I believe StatusCode used to be a type alias, and now it is its own type. This lets it compile.
=> pkg/rpc/rpcstatus: Fix return type

cmd/storagenode/dashboard.go, pkg/kademlia/endpoint.go, storagenode/console/service.go, storagenode/contact/contact_test.go, storagenode/contact/endpoint.go, storagenode/inspector/inspector.go, storagenode/inspector/inspector_test.go, storagenode/peer.go, storagenode/piecestore/endpoint.go, web/storagenode/src/app/store/modules/node.ts
What: Update online status on incoming download, upload and delete requests. Increase the online windo to 2 hours. This is a quick and dirty solution that we should replace doing the kademlia removal.
Why: At the moment the storage node dashboard is showing offline. Removing it is also a bad idea because that will remove the feedback for the storage nodes and they wouldn't be able to detect if something is wrong with the storage node.
Teamwork with @stefanbenten.
- Test 1:
- Test 2:
=> storagenode/dashboard: update online status

satellite/console/consoleweb/server.go, web/satellite/src/utils/authToken.ts
What: Remove domain prefix from token cookie key
Why: It seems that browsers doesn't share cookies between different subdomains of one domain by default
- Test 1:
- Test 2:
=> satellite/console: remove domain prefix from token cookie key

.gitignore, Makefile, mobile/build.sh
What: Add building libuplink-android.aar to `Makefile`.
Why: We need to automate libuplink-android and this change is part of larger task.
- Test 1: none
=> mobile: build libuplink aar

storagenode/console/service.go
What: Use bandwidth monthly summary for `storagenode` bandwidth usage instead of all time summary
Why: To be consistent with CLI dashboard
- Test 1:
- Test 2:
=> storagenode/console: use bandwidth monthly summary

satellite/repair/repairer/ec.go
What: add defer close piecestore in downloadAndVerifyPiece
Why: we are leaking connections and it is causing the satellite to crash
- Test 1:
- Test 2:
=> satellite/repair: defer close piecestore in downloadAndVerifyPiece

satellite/repair/checker/checker.go
What: Remove an old error message in repair checker.
Why: The audit job will remove bad pieces from pointer. As a result the repair checker will find pointers that contain only valid pieces but less than repair threshold. The repair checker will throw an error. I removed that error and executed the same test again. Now the repair checker will add the segment to the repair queue and the repair job will upload new pieces to new storage nodes. Everything works fine without that error validation.
- Test 1:
- Test 2:
=> satellite/repair: remove deprecated error message

satellite/repair/repairer/segments.go
What: 
Calculate segment age before modifying the "last repaired" timestamp on the segment.
Why:
The `segment_time_until_repair` metric is not reporting what it should be, because we are updating the "last repaired" timestamp right before calculating "segment age", which is dependent on the previous last repaired timestamp to be accurate.
- Test 1:
- Test 2:
=> satellite/repairer: move segment age calculation

satellite/audit/verifier.go
What: Add piece hash verified to log messages.
Why: Depending on piece hash verified the audit job will behave different. Storage nodes can get disqualified but they are unable to tell which piece count towards that. With this PR we are able to double check that the disqualification was correct and we could give the storage node operator a list of pieceIDs they can hunt down.
- Test 1:
- Test 2:
=> satellite/audit: Add piece hash verified to log messages

satellite/audit/verifier.go
What: 
Add a mutex to use around writes to the `pieceHashesVerifiedMap` so that we don't ever concurrently write to it.
Why:
There is a chance we can do concurrent writes to the map, which could result in memory issues on the satellite.
- Test 1:
- Test 2:
=> satellite/audit: add mutex to pieceHashesVerified map

satellite/audit/disqualification_test.go, satellite/audit/reporter.go, satellite/audit/reporter_test.go, satellite/audit/verifier.go, satellite/audit/worker.go
What: 
Use `Report` instead of `*Report` in the audit service so we do not have to worry about nil-pointer-exception behavior in the event of an empty report.
Why:
https://build.dev.storj.io/blue/organizations/jenkins/storj/detail/PR-3017/19/tests
- Test 1:
- Test 2:
=> satellite/audit: fix audit panic

web/storagenode/src/app/utils/chartUtils.ts
What: added conditions to make charts be displayed on first day of the month
Why: charts were not displayed on first day of the month
- Test 1:
- Test 2:
=> web/storagenode: charts on first day of the month updated

installer/windows/Product.wxs
What:  default value in the Identity Folder dialog of the Windows Installer points to %APPDATA%\Storj\Identity\Storagenode
Why: because it is the default location for identity tool to generate new storage node identity. Currently, the default is set to the root of the largest drive, which requires the user to always navigate to the location of their identity.
Acceptance criteria:
- The Identity Folder dialog displays %APPDATA%\Storj\Identity\Storagenode as the default value, where %APPDATA% is expanded to the actual location for the current user, e.g. C:\Users\IEUser\AppData\Roaming\Storj\Identity\Storagenode.
Please describe the tests: no test
=> Installer: identity directory defaults to %APPDATA%\Storj\Identity\Storagenode

internal/testplanet/storagenode.go, storagenode/contact/chore.go, storagenode/contact/service.go, storagenode/peer.go
What: remove `randomDurationSleep` on storagenode `contact.Run`
Why: it's harder for SNOs to diagnose connection issues when they must wait up to 45 minutes to attempt to contact satellites on start. We are implementing staggered updates anyway, which will solve the problem of potentially overloading the satellite with incoming requests
- Test 1:
- Test 2:
=> storagenode/contact: remove random sleep on run

satellite/metainfo/config.go, scripts/testdata/satellite-config.yaml.lock, storagenode/piecestore/endpoint.go
What: Increase the time window for uploads and downloads from 1h to 24h on the storage node side and 48h on the satellite side. Increase garbage collection time buffer to 48h as well.
Why: It turns out halve of the network doesn't agree on correct timestamps. 930 storage nodes are rejecting uploads and downloads. Some of them with a wrong clock and some of them with a wrong timezone. This PR will increase the time window to a point where we don't need to worry about timezones anymore. The time windows should still protect storage nodes against malicious uplinks. Orders are valid for 7 days.
- Test 1:
- Test 2:
=> OrderLimit/GracePeriod: Increase time window from 1h to 24h

pkg/rpc/dial.go, storagenode/piecestore/endpoint.go
**What:** This PR adds the ability to ignore io.EOF's that come wrapped or not wrapped.
**Why:** gRPC gives us an unwrapped io.EOF error but dRPC givers us a wrapped one. Since we weren't ignoring the EOF when using dRPC it was causing this error for both uplink and satellite audit downloads.
```
storagenode/6    12F3yR1nJU 21:09:02.714 | INFO	piecestore	piecestore/endpoint.go:440	download failed	{"Piece ID": "PYXQ6IBKHGDH6PWGX3ZZH5SIQAU6BNKLI7QTIYBCYS3U7Y3V2HIQ", "SatelliteID": "1ZNd6Cz8h5Q1NUSesmYXcANd7CwJgcuVVfTGkYof4LQbfzEhrG", "Action": "GET", "error": "piecestore: piecestore protocol: EOF", "errorVerbose": "piecestore: piecestore protocol: EOF\n\tstorj.io/drpc/drpcstream.(*Stream).MsgRecv:242\n\tstorj.io/storj/pkg/pb.(*drpcPiecestoreDownloadStream).Recv:910\n\tstorj.io/storj/storagen …
```
=> storagenode/piecestore: Fix to ignore both gRPC and dRPC EOF errors.

storagenode/piecestore/endpoint.go
The upload code currently updates the usage in a deferred call to saveOrder().
The consequence is that in the success case, the RPC is completed before
the usage has been updated.
This change repurposes the deferred call to update usage in the
failure case, while explicitly updating the usage before completing the
RPC.
This fixes some test flakiness when using dRPC. gRPC waits until the final status is written before a `Recv` call completes, and the final status is written by the server after the handler function has exited. In practice this means that the client is blocked until the `defer` call is also finished. So this change will not change performance at all.
It has two advantages:
(1) It fixes test flakiness
and, more importantly:
(2) reduces the chances that someone will …
=> piecestore: update usage before completing upload

satellite/metainfo/metainfo.go, uplink/piecestore/verification.go
What: Increase the time window from 2h to 24h
Why: Because 930 storage nodes have problems to get the correct timezone. Most likely a docker issue. We should replace the timestamp with https://storjlabs.atlassian.net/browse/V3-2936 but while waiting on that fix I would like to cherry pick this workaround to buy us time.
- Test 1:
- Test 2:
=> Satellite/PieceHashValidation: Increase time window from 2h to 24h to avoid timezone issues

.clabot
Change-Id: I10a498233d181706a8b3149b18c015d20a101b8d
What: 
Why:
- Test 1:
- Test 2:
=> add mykola siedov to clabot

satellite/repair/repairer/ec.go, satellite/repair/repairer/repairer.go, satellite/repair/repairer/segments.go
What: Improve the logging around failed repair.
```
satellite/0      12fbck97kq 01:36:35.511 | ERROR	repairer	repairer/repairer.go:95	repair worker failed:	{"Segment": "ZDY0Zjg1MDEtMjJkMC00YjI0LWI1YjItNmIyYzllZGIxOTRhL2wvcmVsZWFzZS1hbHBoYTE3LwI2ebiX+gjbGB9ZJFHU5/T0tgfN5zH9/f4B1GBDk9j9Vg==", "error": "repairer error: repairing injured segment: repairer error: couldn't download enough pieces, number of successful downloaded pieces (1) is less than required number (4)"
```
Why: At the moment the satellite prints out the encrypted path. It is hard to grep a logfile for the encrypted path. My hope is that with the new logging will allow us to grep, sort and count the binary value instead of the encrypted path. There is still one line that prints out the encrypted path so that we still have it …
=> satellite/repair: improve logging

cmd/storj-sim/main.go
What: Make storj-sim to read `STORJ_SIM_POSTGRES` environment variable, which makes it easier to setup defaults handling.
Why:
- Test 1:
- Test 2:
=> cmd/storj-sim: make postgres default to STORJ_SIM_POSTGRES

cmd/satellite/main.go, internal/testplanet/planet.go, internal/testplanet/run.go, internal/testplanet/satellite.go, satellite/metainfo/metainfo_test.go, satellite/satellitedb/database.go, satellite/satellitedb/satellitedbtest/pgschema.go, satellite/satellitedb/satellitedbtest/run.go
Changes to switch to using only Postgres in tests. There are multiple changes to allow `testplanet` to connect to the default database defined by `STORJ_POSTGRES_TEST`.
This only changes the default behavior to run against postgres. The follow-up https://github.com/storj/storj/pull/3296 will remove the dead sqlite code.
- Test 1:
- Test 2:
=> satellite/satellitedb: switch to postgres only

README.md
What: Replace any reference to Rocket chat by our forum.
Why: Rocket chat is deprecated and currently it's in read-only mode. Our
current official channel is our forum.
Please describe the tests: N/A 
=> README: Replace reference Rocket chat to forum

lib/uplink-gomobile/bucket.go, lib/uplink-gomobile/libuplink_android/app/src/androidTest/java/io/storj/mobile/libuplink/LibuplinkInstrumentedTest.java
What: `Reader.Read` in gomobile accepts `offset` and `length` params. 
In addition, this PR fixes a bug in the usage of `length` in `Writer.Write` method.
Why: This allows more optimal usage from Java code. Java does not have slices like in Golang, but achieves the same on byte arrays with the usage of offset and length.
- Existing tests adapted
=> gomobile Reader.Read should take offset and length params

installer/windows/Product.wxs
What: Add `--config-dir` flag to the storagenode-updater service arguments.
Why: So the updater can correctly locate the storagenode config file.
N/A
=> installer/windows: add config dir flag to windows installer

Makefile
What: 
Change Makefile so that things still work when one has no `$GOPATH` environment variable, because that's what I have.
Also, use `$(CURDIR)` in place of `$(shell pwd)`.
Why:
- Because I have no `$GOPATH` environment variable here. The default works for me, and (I suspect) other people too
- The change to `$(CURDIR)` saves a fork+exec, is more readable, and is more idiomatic. The only case where it should have different value from `$(shell pwd)` is when someone's configured `$SHELL` is badly broken, and I'd argue that even then `$(CURDIR)` is preferable.
- automated tests and checks already exercise Makefile to some degree; additional behavior had to be tested manually
- minimal
=> Makefile: handle empty/default $GOPATH

storagenode/pieces/store.go
What:
Remove part of a comment that is no longer correct. The reservedSpace member it's talking about was removed in 022f5d2e.
Why:
Confusion avoidance
- I have probably not sufficiently tested that changes to comments do not affect correctness
- none
=> storagenode/pieces: just a tiny comment update

web/satellite/src/components/account/billing/AccountBalance.vue, web/satellite/src/components/account/billing/CardDialog.vue, web/satellite/src/components/account/billing/PaymentMethods.vue, web/satellite/src/views/DashboardArea.vue
What: 
Why:
- Test 1:
- Test 2:
=> web/satellite: temporarily removing payments api calls

installer/windows/Product.wxs
What: The installer now passes to `storagenode setup`:
- `--operator.wallet` instead of `--kademlia.operator.wallet`
- `--operator.email` instead of `--kademlia.operator.email`
- `--contact.external-address` instead of `--kademlia.external-address`
Why: The old kademlia argument are not persisted in config.yaml anymore and this breaks the installation on Windows.
- Test 1: N/A
=> installer/windows: Use new wallet, email and external-address args in storagenode setup

installer/windows/Product.wxs
What: Fixes the Windows Installer to pass the correct args to the storagenode-updater service configuration.
Why: The changes in the auto-updater were not reflected in the Windows installer. Hence, the storagenode-updater service fails to start after installation.
=> Fix args passed to the storagenode-updater service

storagenode/gracefulexit/worker.go
What: Fix the drpc build of the graceful exit package
Why: Somehow #3371 was merged even though it no longer compiled under `-tags=drpc`.
- Test 1:
- Test 2:
=> gracefulexit: fix build for drpc

satellite/gracefulexit/endpoint.go
What: 
There are some parts of the graceful exit satellite endpoint where we block and do not handle canceled contexts. This PR fixes that.
Why:
- Test 1:
- Test 2:
=> satellite/gracefulexit: handle context cancelled in satellite graceful exit endpoint

cmd/storagenode-updater/main.go, installer/windows/Product.wxs
What: Renames the `--log-path` argument of storagenode-updater back to `--log`.
Why: We need to keep config args consistent between release to avoid issues with upgrade. The rename from `--log` to `--log-path` was introduced with #3276. It is already planned to rename it back to `--log` with #3338. But we want this change to happen in this separate PR, so it can be included in the next 0.24.x release for storagenodes.
=> Rename --log-path back to --log for storagenode-updater

cmd/storagenode-updater/main.go
What: Print "... version is up to date" message to storagenode-updater log if rollout status determines that it shouldn't update.
Why: In the case where the rollout does not apply, this log message was missing.
=> cmd/storagenode-updater: add "...up to date" log line if shoudn't update

cmd/storj-sim/network.go, cmd/storj-sim/process.go, internal/sync2/fence.go, internal/sync2/fence_test.go, internal/version/checker/service.go, storagenode/console/service.go, storagenode/contact/chore.go, storagenode/contact/contact_test.go, storagenode/contact/service.go
What: Currently there wasn't a way to use `sync2.Fence` such that it waits for context to be completed. Ensure that it can detect context closing. Also update `storagenode/contact` to use `sync2.Fence`.
Why:
- Test 1:
- Test 2:
=> internal/sync2: make Fence accept context

cmd/storj-sim/network.go
What: Use smaller port range for storj-sim.
Why:
- Test 1:
- Test 2:
=> cmd/storj-sim: use less ports

satellite/gracefulexit/chore.go, storagenode/gracefulexit/chore.go
"running graceful exit chore" makes it sound like the storagenode/satellite is gracefully exiting and confusing people. Also lower the level to debug.
https://forum.storj.io/t/changelog-v0-24-5/2420/16
- Test 1:
- Test 2:
=> {satellite,storagenode}/gracefulexit: clearer log messages

satellite/repair/repairer/ec.go, satellite/repair/repairer/segments.go, storagenode/gracefulexit/worker.go, uplink/ecclient/client.go
What: 
- remove expiration arg from ecclient PutPiece method
Why:
- it was unused
- Test 1:
- Test 2:
=> satellite/repair, uplink/ecclient: remove expiration arg from PutPiece method

cmd/satellite/api.go, cmd/satellite/main.go, cmd/storj-sim/network.go, satellite/peer.go, scripts/test-sim-backwards.sh
What/Why:
Now that the Satellite API is separated from the peer and deployed to production separately, this PR remove the duplicate API code from the peer.go file.
This PR also moves the database migration into the `satelllite run api` command in order to work better with storj-sim.  Additionally this might be best for the production deploy, we may want all the other split satellite services to wait on the API to complete the migration then they can start up after.
- updates storj-sim to pass the integration and backwards compatibility tests
n/a
=> satellite: remove satellite API code from peer

certificate/authorization/service.go
What: Fixes the problem of potentially returned an already claimed token
Why: It currently could return a claimed token, which causes confusion
=> cmd/certificates: Ensure we dont return already claimed token again

storagenode/contact/chore.go
`resp` might be nil when the check in fails.
- Test 1:
- Test 2:
=> storagenode/contact: fix panic in ping satellites

cmd/storj-sim/main.go, cmd/storj-sim/network.go
What: Adds storj-sim support for --redis flag
Why: Allows users to run and configure their own redis server to use with storj sim. Defaults to environment variable $STORJ_SIM_REDIS. If not set, storj-sim will spin up the needed redis servers automatically.
=> cmd/storj-sim: add --redis flag

satellite/gracefulexit/endpoint_test.go
What: 
Allow error in graceful exit disable test to be `rpcstatus.Unknown` or `rpcstatus.Unimplemented`
Why:
grpc returns `Unimplemented` and drpc returns `Unknown`
- Test 1:
- Test 2:
=> satellite/gracefulexit: check for unkown error in graceful exit disable test

internal/testcontext/compile_drpc.go, internal/testcontext/compile_nodrpc.go, pkg/rpc/common_drpc.go, pkg/rpc/common_grpc.go, pkg/rpc/compat_drpc.go, pkg/rpc/compat_grpc.go, pkg/rpc/dial_drpc.go, pkg/rpc/dial_grpc.go, pkg/rpc/rpcpeer/peer_drpc.go, pkg/rpc/rpcpeer/peer_grpc.go, pkg/rpc/rpcstatus/status_drpc.go, pkg/rpc/rpcstatus/status_grpc.go
What: changes the default to use drpc instead of grpc
Why: so we can start using drpc by default
- Test 1:
- Test 2:
=> drpc: enable by default

Makefile
What:  Have satellites make outgoing grpc connections
Why: Storage nodes don't have https://review.dev.storj.io/c/storj/storj/+/129 yet
- Test 1:
- Test 2:
=> satellite: make outgoing connections with grpc

cmd/storagenode-updater/main.go, cmd/storagenode-updater/main_test.go
What: Disables the self-autoupdate of storagenode-updater service. Related to https://storjlabs.atlassian.net/browse/V3-2882
Why: The recovery/rollback mechanism in case of bad update of the storagenode-updater does not work as expected. Hence, we need to disable the self-autoupdate to avoid the risk of deploying bad updates to too many storage nodes. We will enable it back when we have a reliable recovery mechanism.
- Test 1: `TestAutoUpdater_unix` is disabled
=> storagenode/updater: disable self-autoupdate

satellite/audit/worker.go, scripts/testdata/satellite-config.yaml.lock
What: Increase the audit timeout to 5 minutes.
Why: We are removing the concurrency limit. We don't want to disqualify storage nodes for getting overloaded with too many requests. Lets give them 5 minutes for audits.
Note: This change might decrease our audit throughput. We can increase the number of audit worker if needed.
- Test 1:
- Test 2:
=> satellite/audit: increase timeout to 5 minutes

Makefile
What: Some of the calls in the `Makefile` were weird and duplicating
work during rebuilds.
Why: speed!
Please describe the tests: existing tests
=> Rebuild faster by removing weird make calls

internal/testplanet/uplink.go, satellite/audit/reverify_test.go, satellite/audit/verifier.go, satellite/audit/verifier_test.go
What: 
* When a segment is audited, if it has already expired, do not audit nodes for that segment and delete the segment. Do this for Verify as well as Reverify
* When a node is audited for data in containment mode, if the data it was contained for has expired, delete the segment and remove the node from containment mode
Why:
This case was not carried over during an audit refactor: https://github.com/storj/storj/pull/1559
- Test 1: Select a segment to call `audit.Verify` on. Update it to have an expired timestamp. Expect that `audit.Verify` returns an "expired" error, and deletes the segment from metainfo.
- Test 2: Select a segment to call `audit.Reverify` on. Update it to have an expired timestamp. Expect that `audit.Reverify` returns an "expired" error, and …
=> satellite/audit: do not audit expired segments

Makefile
What: Add [goversioninfo](https://github.com/josephspurrier/goversioninfo) to `build-dev-deps` make target.
Why: The windows installer now requires proper version information in the storagenode binary to build; therefore, this is now a development dependency.
=> makefile: add goversioninfo to build-dev-deps

satellite/api.go, satellite/console/consoleweb/server.go, satellite/core.go, satellite/peer.go, scripts/testdata/satellite-config.yaml.lock
What: Add payments config to satellite peer config.
Why: To add the ability for satellite owner to set API keys for `stripe` and `coinpayments`
- Test 1:
- Test 2:
=> satellite/peer: add payments config

Makefile
our best tested configuration is only clients issuing with drpc, so this makes most binaries build with grpc mode.
What:
- add the `-tags=grpc` build tag to more binaries
- fix binary-check to look for `.exe` when host os isn't windows
- use `/usr/bin/env echo` instead of `/bin/echo` for people on wacky linux distributions
Why: Makes the release safer.
=> release: opt more binaries in to grpc

certificate/endpoint.go, cmd/storagenode/gracefulexit.go, satellite/contact/endpoint.go, satellite/gc/service.go, satellite/gracefulexit/endpoint.go, satellite/gracefulexit/pathcollector.go, satellite/metainfo/metainfo.go, satellite/repair/repairer/ec.go, storagenode/collector/service.go, storagenode/contact/chore.go, storagenode/gracefulexit/chore.go, storagenode/gracefulexit/endpoint.go, storagenode/gracefulexit/worker.go, storagenode/pieces/store.go, storagenode/piecestore/endpoint.go, storagenode/retain/retain.go, uplink/ecclient/client.go, uplink/storage/streams/store.go
What: Print out the pieceID when deleting expired pieces. While I was on it I unified the log messages around satelliteID, nodeID, pieceID and switched to zap.Stringer when possible.
Why: Everything that deletes a piece from a storage should print out the pieceID so that the storage node operator can open a support ticket if something is wrong.
- Test 1:
- Test 2:
=> logging: unify logging around satellite ID, node ID and piece ID

scripts/test-sim-backwards.sh
What: `sed` expression was the wrong way around causing the port not be replaced.
Why:
- Test 1:
- Test 2:
=> test/backwards-compatibility: fix port change

satellite/audit/reverify_test.go, satellite/audit/verifier.go, satellite/audit/verifier_test.go, satellite/gc/gc_test.go, satellite/gracefulexit/endpoint_test.go, satellite/metainfo/metainfo.go, satellite/metainfo/service.go, satellite/repair/checker/checker_test.go
Calling `Delete` directly is usually very dangerous, because the pointerdb is changing all the time. Any time we call directly delete we must ensure that there are no changes.
Hence:
1. Rename `Delete` to `UnsynchronizedDelete` to make it more obvious that it's dangerous.
2. Add new method `Delete` that takes the old pointer bytes as an argument.
- Test 1:
- Test 2:
=> satellite/metainfo: fix some uses of metainfo.Delete

pkg/rpc/dial_grpc.go
What:  add a timeout above the grpc dial because that's the documented way that grpc expected to be canceled.
Why: grpc doesn't exit dials right away if the context dialer returns an error. since that's the only spot where we were enforcing dial timeouts, dials could just leak for an unknown amount of time.
=> pkg/rpc: fix grpc dial timeouts

certificate/peer.go, cmd/identity/batch.go, pkg/identity/certificate_authority.go
What:  After increasing the default difficulty of the `identity create` command (see #3428) and released the new version, we are now increasing the minimum required difficulty in the certificate signing service.
See: https://storjlabs.atlassian.net/browse/V3-2848
Note, this PR also increases the min required difficulty in the `identity batch` command for the sake of consistency.
Why: We want to raise the bar of Proof of Work for new storage nodes.
Please describe the tests: Existing tests should still be enough
=> certificate/signing: increase min required difficulty to 36

web/satellite/src/components/apiKeys/SortingHeader.vue
What: 
API keys sorting header was misaligned
Why:
- Test 1:
- Test 2:
=> web/satellite: api keys sorting header styles fixed

pkg/process/rand.go
What: 
Seeds the default source in the math/rand package for processes using `pkg/process`.
Why:
Default source is used throughout the codebase. Not seeding the source will cause it to produce the same sequence, meaning the only variability will be based on the order of calls (maybe from different goroutines) on the default source.
N/A
None
=> Initialize math/rand default source

Jenkinsfile, Makefile
What: Unhook jenkins from the dev cluster
(Accidentally closed https://github.com/storj/storj/pull/3331)
Why: The dev cluster is undergoing renovations. Jenkins should fail
master builds while this is happening.
- No tests, just removing unused code.
- The whole build pipeline is slightly faster!
=> Unhook jenkins from the staging (dev) cluster

storagenode/storagenodedb/database.go
What: Currently logging `opened database` ends up being multiplied too many times making it hard to review the log. This will remove about 28 lines per storage node from test output. Total test json output goes from 30MB to 25MB.
Why:
- Test 1:
- Test 2:
=> storagenode/storagenodedb: don't log opening of each database

satellite/metainfo/metainfo.go
What: Suppress large conditional block.
Why: Because large conditional blocks are hard to read.
When the conditional block only has one branch it's easy to understand
the logic of the function to early return switching the condition.
Please describe the tests: the change is about code readability, there aren't functional changes, hence the current tests are expected to pass.
=> satellite/metainfo: avoid large conditional block

cmd/storagenode-updater/main.go, cmd/storagenode-updater/main_test.go
What: We are re-enabling the self-auto-updating of stragenode-updater after we fixed the issue with the recovery mechanism.
Why: See https://storjlabs.atlassian.net/browse/V3-2882
- Test 1: The auto-updating part of the storagenode-updater is re-enabled in TestAutoupater.
=> storagenode-updater: re-enable auto-update storagenode-updater

docs/blueprints/deletion-performance.md
What: Replace a sentence which indicates that we're creating and new endpoint
in the storage node side rather than adapting the current one.
Why: I forgot to apply that change after it was discussed in the arch meeting and we agreed to create a new one.
=> docs/blueprints: Change adapt endpoint by creating

monkit.lock, storagenode/monitor/monitor.go
What: Add storage node bandwidth metrics
Metrics:
- allocated_bandwidth
- usage_bandwidth
- available_bandwidth
Why: Requested by DS team
1 - Create a pipeline.lua file to run the statreceiver locally:
```lua
source = udpin("127.0.0.1:9000")
destination = parse(print())
deliver(source, destination)
```
2- Change at least one storage node configuration to be captured locally
Ex: `../storagenode/0/config.yaml`
Uncomment and change the following keys:
```yaml
metrics.addr: "127.0.0.1:9000"
metrics.interval: "5s"
```
3- `statreceiver --input pipeline.lua | grep -E "allocated_bandwidth|usage_bandwidth|available_bandwidth"`
4 - `storj-sim network run`
_You should see something similar from **stareceiver** :_
=> storagenode: add bandwidth metrics

storagenode/gracefulexit/worker.go
What: Improve logging.
Why: The graceful exit node was transfering a lot of pieces but didn't print out any log messages.
- Test 1:
- Test 2:
=> storagenode/gracefulexit: improve logging

installer/windows/PublicAddressConfig.wxs
What: Change "your opened" to "you opened"
Why: because it's how it should be
- Test 1:
- Test 2:
=> installer/windows: fix minor typo

satellite/satellitedb/satellitedbtest/run.go
What:
Add a flag that makes it so CockroachDB-using tests aren't skipped.
Why:
This will make it so we don't need to comment out those lines every time
we want to enable the cockroachdb tests during development.
Once it's ready this flag can go away.
- No tests exercise this behavior, because it only affects tests and shouldn't affect production use of code in any way.
- None
=> satellite/satellitedb/satellitedbtest: flag to run cockroach tests

satellite/console/service.go, satellite/console/usercredits_test.go
What: Comment out code that creates user credit in satellite console service CreateUser and skip TestUserCredits
Why: We are trying to make sure all of our queries are cockroach compatible. The sql query in `usercredits.Create` is not. In the interest of time, and on the advice of the person who wrote the usercredits system, we are simply bypassing the user credits issue for now, as it is not being used in production
- Test 1:
- Test 2:
=> satellite/console : remove code for creating user credit in CreateUser, skip TestUserCredits

satellite/metainfo/metainfo.go, satellite/metainfo/validation.go
What: Improve the piece hash validation 
The commit also improves the documentation of an internal `metainfo`
method and rename the parameters of 2 methods for clarifying what they
are.
Why: Because we should filter out pieces which don't have an associated original order limit.
Please describe the tests: The current test must pass
=> satellite/metainfo: Improve piece hash validation

satellite/audit/verifier.go, satellite/metainfo/metainfo.go, satellite/metainfo/service.go, satellite/repair/repairer/segments.go
What: Currently packages were directly using `storage.ErrKeyNotFound` to check for errors from `metainfo.Service`, however `storage` package is an implementation detail for `metainfo`. Users of `metainfo.Service` shouldn't use `storage` package for checking errors. `storj.ErrObjectNotFound` is slightly better, however maybe not perfect.
Why:
- Test 1:
- Test 2:
=> satellite/metainfo: don't leak error implementation detail

Jenkinsfile, scripts/test-sim-versions.sh
What: Make `test-sim-versions.sh` work on jenkins
Why: We have to use jenkins.
- Test 1:
- Test 2:
=> Work with @VinozzZ to make this work on jenkins

Jenkinsfile
Change-Id: If55105fa99ebb32fa84dd595258f83838d3150f1
What: Only highlight the build team
Why: @channel is too noisy.
Please describe the tests: none
=> Slack the build team instead of everyone

storagenode/orders/service.go
'receiving' was 'receiveing'
'a' was used instead of 'an'
'settlement' was misspelled
=> Typos in log messages

web/satellite/src/components/common/PasswordStrength.vue
Typo for text `website` shown as  `websities`
=> web/satellite: Fixing typos in website pages

satellite/metainfo/metainfo.go
What: 
Why:
- Test 1:
- Test 2:
=> satellite/metainfo: remove RS validation for bucket creation

satellite/accounting/projectusage.go, satellite/accounting/projectusage_test.go
What: Remove the expansion factor from the download traffic limit.
Why: Once upon a time we created up to 80 GET orders and they all count against the project limit. We had to factor in the expansion factor. Later we reduce the number of GET orders but we missed to remove the expansion factor.
- Test 1:
- Test 2:
=> accounting/projectlimit: remove expansion factor

scripts/tag-release.sh
What: Fix regex error in tag-release script.
Why: ? means 0 or 1 + means at least 1 or more. The combination ?+ was a mistake that works on linux but doesn't work on osx. This fix should make it so that it works on all OS.
- Test 1:
- Test 2:
=> script/release: fix error in regex

scripts/tests/rollingupgrade/test-sim-rolling-upgrade.sh
What: This time the rolling upgrade test was working as long as we are pushing only -rc tags. The second exclude was not working as expected.
Why:
```
root@kali:~/storj# echo $(git describe --tags `git rev-list --exclude='*rc*' --exclude=$current_release_version --tags --max-count=1`)
v0.35.2
root@kali:~/storj# echo $(git describe --tags `git rev-list --exclude='*rc*' --exclude=$current_release_version* --tags --max-count=1`)
v0.34.10
```
- Test 1:
- Test 2:
=> test/rollingupgrade: fix stage 1 release version

cmd/storj-sim/network.go, satellite/accounting/rollup/rollup.go
What: Sets the default max-alpha-usage to 200GB, from a default of 25GB.
Why: Tests can take require more than 25GB.
=> cmd/storj-sim: Increase storj-sim max-alpha-usage

storagenode/nodestats/cache.go
Change-Id: I11920b54736e7e548f5638a9ba5f6380a94d99c4
What: 
An accidental change got merged that was probably for debugging, but now its causing the prod databases to be a 100% cpu use. This PR fixes it.
Why:
- Test 1:
- Test 2:
=> revert to use the config for storagesync

storagenode/piecestore/endpoint.go
Change-Id: I3dd0f44226e7b946a2b30c3d0f30f28749ca6e88
What/Why:
Remove the stack trace from log "upload canceled" since it creates a lot of not helpful noise for SNOs.
For details see: https://github.com/storj/storj/issues/2802
n/a
n/a
=> storagenode/piecestore: fix annoying info log for upload canceled

Makefile
What: The `Makefile` target was wrong
Why: I typoed it.
Please describe the tests: No tests, obviously.
Please describe the performance impact: Makes builds work again?
=> Call the right make target for the segment-reaper

storagenode/piecestore/endpoint.go
What: Add a missing log message about audit errors.
Why: We have implemented suspension mode but on the storage node log the audit errors are missing.
- Test 1:
- Test 2:
=> storagenode/piecestore: add missing log message about audit errors

satellite/overlay/benchmark_test.go
Change-Id: I0259af155f9151cc2c7830d10f8907634c5e494f
What/Why: 
Make modifications to the benchmarks for select node cache.  Changes include:
- add a benchmark that selects both new nodes and reputable nodes, with new nodes being newnodefraction amount of new nodes, this simulates how the code is used in production
- add separate bencmarks for `FindStorageNodesWithPreference` and also `GetNodesNetwork` since this will be helpful to understand performance of the selected nodes cache from this [PR](https://github.com/storj/storj/pull/3859)
same as what/why above
```
count = 5
-benchtime 5s
$ benchstat master.txt benchbranch.txt
name                                                               old time/op  new time/op  delta …
```
=> satellite/overlay: add changes to selected node benchmarks

satellite/accounting/projectusage_test.go, satellite/satellitedb/projectaccounting.go
What: Changes the DB Queries to just return data for buckets that still exist to be displayed in the Satellite UI
Why: Currently we return all buckets for the current period, even when deleted.
Please describe the performance impact: slightly quicker, due to smaller table/information amount
=> satellite/satellitedb: Ensure we just return bucket usage for buckets that exist

satellite/metainfo/piecedeletion/dialer.go
What: Moves the Info Logging to Debug
Why: We do not need to know if individual deletes to storagenodes failed.
Please describe the performance impact: slightly less CPU overhead for logging... lol
=> satellite/metainfo: move logging to debug for piece deletion

satellite/admin/README.md
What: Update documentation for admin interface
Why: To make it obvious that the admin interface expects a project name and not an id.
- Test 1:
- Test 2:
=> satellite/admin: obvious project name in documentation

cmd/satellite/stripe.go
What: changes the SQL query to not generate stripe customers for users that are not activated.
Why: It currently does the opposite
=> cmd/satellite: ensure we only create stripe customers for activated users

satellite/admin/README.md, satellite/admin/project.go, satellite/admin/project_test.go, satellite/admin/server.go, satellite/admin/user.go, satellite/admin/user_test.go
What: adds user creation endpoint
Why: It allows mass creation of users
- Test 1: added test for creation
=> satellite/admin: add user creation endpoint

satellite/contact/service.go
Change-Id: I74dc29f18969250fa6838fed9bec8ba7ea160b77
What/Why:
Remove the verbose logging of the contact service ping back errors since it makes up at 99% of the production logs atm and it is not useful.
n/a
n/a
=> satellite/contact: rm unhelpful verbose logging

satellite/overlay/nodeselectioncache.go, scripts/testdata/satellite-config.yaml.lock
What: Enable node selection cache on all satellites.
Why: We have tested it on europe north, fixed it, and are now ready to enable it by default on all satellites.
- Test 1:
- Test 2:
=> satellite/overlay: enable node selection cache on all satellites

cmd/satellite/Dockerfile
What: Adds curl as preinstalled binary to our docker image.
Why: Its handy to do requests on the new admin API pods.
=> cmd/satellite:  Install curl per default to docker image

satellite/accounting/live/redis.go
What: Bugfix infinite storage usage increase.
Why: With the last release we have added bandwidth usage to the redis DB. The cache was confused by that and on every tally run the value was increasing.
- Test 1:
- Test 2:
=> satellite/accounting: bugfix infinit storage usage increase

private/dbutil/defaults.go, scripts/testdata/satellite-config.yaml.lock
As we currently do not use even near to that many connections actively, we are just wasting resources.
Reducing the number does not have any  negative effect on performance and in fact might speed things up
=> private/dbutil: reduce db connection defaults

Jenkinsfile, Makefile
What: Update to latest Go
Why: Updates are good
Please describe the performance impact: Non expected or tested.
=> build: Go 1.14.7

storagenode/monitor/monitor.go
Its not "allocating" any space but rather shows "service.allocatedDiskSpace"
What: Fixing typo and make it more readable.
Why: It suggested that more space was being allocated by using word "allocating".
- Test 1:
- Test 2:
=> Fixed typo in log for allocated space

web/storagenode/src/storagenode/satellite.ts
What: 
I suggest raising the warning minimum score a lot (0.95 in this example) to ensure SNO's actually get an early warning.
Why:
Any score dropping below 0.95 is already a good indication something is wrong. If you want to be conservative I can imagine going with 0.90, but 0.76 means you're already 2/3rds of the way towards serious consequences for the node. This is especially important since the suspension threshold for down time is likely to go up in the future as well.
- Test 1: NA
- Test 2: NA
=> Raise warning to ensure early notification

Makefile, cmd/storj-sim/network.go, scripts/tests/rollingupgrade/test-sim-rolling-upgrade.sh
What: 
We need to revert some changes to storj-sim and gateway testing.
Why:
When adding multi-tenant (for stargate) features to gateway we changed some stuff with storj-sim. Now that we moved the stargate into its own repo, we need to revert these changes so that storj-sim tests can still work with the gateway without stargate multi-tenant functionality.
For reference, this PR started over in [gerrit](https://review.dev.storj.io/c/storj/storj/+/2837), but moved to github because it was easier to branch off the release branch.
Reverted the stargate support for multi-tenant.
n/a
=> cmd/storj-sim: fix gateway changes

satellite/repair/checker/checker.go, scripts/testdata/satellite-config.yaml.lock
What: Move the repair override from config into the default value
Why: We are going to change the repair override behavior in the future. Because the value is currently specified on all of our satellite configs this means some extra coordination to make sure we don't mess up the release. With this PR we can split that work into 2 steps. First get rid of the override in the satellite configs without the risk to mess up production and in a following release the new implementation with a new default value will get released without having to touch the satellite configs or risk that we forget to update it.
- Test 1:
- Test 2:
=> satellite/config: move repair override from config to default

scripts/tests/rollingupgrade/test-sim-rolling-upgrade.sh
What: Sleep 5 seconds between old api startup and database migration
Why: Currently we start storj-sim almost in parallel. If the api endpoint takes more time to start than storj-sim needs to run the database migration the old api endpoint will error out with a database version missmatch. The sleep statement will allow the old api endpoint to come up and we can continue the rolling upgrade test.
- Test 1:
- Test 2:
=> jenkins/rollingupgrade: sleep 5 seconds between old api startup and database migration

cmd/satellite/admin.go, cmd/satellite/api.go, cmd/satellite/billing.go, cmd/satellite/compensation.go, cmd/satellite/gc.go, cmd/satellite/gracefulexit.go, cmd/satellite/main.go, cmd/satellite/repairer.go, cmd/satellite/reports/attribution.go, cmd/satellite/usage.go, cmd/segment-reaper/delete.go, cmd/segment-reaper/detect.go, multinode/multinodedb/database.go, private/dbutil/pgutil/db.go, satellite/metainfo/config.go, satellite/satellitedb/database.go, satellite/satellitedb/migrate_test.go, satellite/satellitedb/satellitedbtest/run.go, storage/cockroachkv/client.go, storage/postgreskv/client.go, storage/postgreskv/client_test.go
Change-Id: I5f3a1a7fc7caeefdb777cd588ac1b0d7333241ed
What: 
Adds ability to allow for DB application names per process
Why:
This will allow us to know which process is executing a query.
- Test 1:
- Test 2:
=> Allow for DB application names per process.

Makefile
What: Currently the wasm files were built for every satellite binary running on 64bit kernels.
This change makes sure we only build it once, when the binary for linux amd64 is built.
=> Makefile: build wasm files only once

cmd/storagenode/Dockerfile, cmd/uplink/Dockerfile
What: Ensures that the passed in arch is used for creating the container.
Why: The storagenode containers were build unsuccessfully all with amd64 instead of the requested arch.
=> cmd: ensure proper arch is used for docker container

Makefile, scripts/deploy-storagenode.sh
What/Why: It turns out that alpine dropped support/updates for the aarch64 image.
Instead they have been using the arm64v8 notation for quite a while,
which resulted in breaking our recent aarch64 builds due to missing
dependencies/updates.
Both arches are exactly the same, aarch64 was created originally by Apple
and arm64 by GNU. The backends have been merged by now and the arm64 became
the de facto standard.
=> Makefile,scripts: move from aarch64 to arm64v8

Jenkinsfile.public
What/Why: Docker build defaults to the master branch, when specifying a git repo.
With this change, it should be smart enough to use the proper main branch.
=> Jenkinsfile.public: specify main branch for docker build

web/satellite/src/components/team/ProjectMembersArea.vue
What: We want to make the Project Owner in Team tab pinned to the top of the list of team members 
Why: More convenience for the user
- Test 1:
- Test 2:
=> Pin Project Owner in Team tab to top of members list

Makefile
What/Why: Downgrade to go v1.15.7 as v1.16 causes build failures for OSX binaries.
=> Makefile: downgrade to go v1.15.7

Jenkinsfile, Makefile, cmd/uplink/cmd/access_test.go, cmd/uplink/cmd/import.go, go.mod, go.sum
What: windows uplink binaries are broken
Why: this is a bump of the release for just uplink binaries. we don't need new deploys.
=> Jt/release v1.27

README.md
Update README.md to reference the latest PDF whitepaper.
The existing link navigates to a 404.
=> Fix link to whitepaper in README.md

satellite/accounting/rolluparchive/rolluparchive.go
What: Remove the 24h devDefault and use the 90d prod default instead.
Why: The 24h devDefault makes it hard to test billing locally. The traffic gets moved into an archive before we can generate any invoices.
- Test 1:
- Test 2:
=> satellite/rolluparchive: archiveAge use 90d prod default for storj-sim

satellite/metabase/metaloop/service.go, scripts/testdata/satellite-config.yaml.lock
When using a system time too far in the past, the query gets slower.
Change-Id: I7014d13a16b1ec44391549f829e7a57942f1fea7
What: 
Why:
- Test 1:
- Test 2:
=> Point release v1.31.2

go.mod, go.sum, satellite/metabase/metabasetest/test.go, satellite/metabase/metadata.go, satellite/metabase/metadata_test.go, satellite/metainfo/endpoint_test.go, satellite/metainfo/metainfo.go
What: The UpdateObjectMetadata endpoint requires StreamID for updating the objects metadata.
Why: This avoids corrupting objects if reuploads and metadata updates happen
concurrently.
- Test 1: `TestEndpoint_UpdateObjectMetadata` is updated.
=> satellite/{metabase,metainfo}: require StreamID for UpdateObjectMetadata

satellite/audit/reporter.go, satellite/audit/reverify_test.go
When a node gets enough timeouts, it is supposed to be removed
from pending_audits and get an audit failure. We would give them
a failure, but we missed the removal. This change fixes it.
Change-Id: I2f7014e28d7d9b01a9d051f5bbb4f67c86c7b36b
What: 
Why:
- Test 1:
- Test 2:
=> satellite/audit: fix containment bug where nodes not removed

storage/filestore/store_test.go
What: Add test steps to make sure VerifyDirWriteable doesn't create the file for VerifyDirReadable. Even if the write test gets executed first the read test should still throw an error.
Why: There was a question in the community. What happens if the storage node drive gets unmounted and the storage node continues with an empty directory instead. Wouldn't the VerifyDirWriteable check create the file and the VerifyDirReadable pass after that? The answer is no. They use different files. This unit test will double-check that.
- Test 1:
- Test 2:
=> storage/filestore: test interaction between VerifyDir Readable and Writeable

satellite/audit/reporter.go, satellite/audit/verifier.go, satellite/audit/verifier_test.go
Since we are sharing the reporting logic between repair and audit. We
need to remove metric reporting logic in reporter.
Change-Id: Ib87295ab19079329e7438327d785a7f5c21d3b21
What: 
Why:
- Test 1:
- Test 2:
=> Point release-v1.39.6

private/date/utils.go, storagenode/payouts/estimatedpayouts/estimatedpayouts.go, storagenode/payouts/estimatedpayouts/estimatedpayouts_test.go
- Use minutes instead of days in earning estimation monthly
To fix https://github.com/storj/storj/issues/4056
- Currently, the interpolation unit is day. This is largely inaccurate, as described in issue https://github.com/storj/storj/issues/4056
- Moreover, the estimation monthly is using full months. For example, if a node joined on 15th of March, it is still estimated to earn from 1st of March to the end of March, while actually it should be estimated only from 15th of March to the end of March.
`TestCurrentMonthExpectations` is already doing the job well. We need however to change the expected value to reflect better estimation accuracy
It should only impact the visualization of the earning estimation.
=> storagenode/payouts: Fix monthly earning estimation

satellite/repair/repair_test.go, satellite/repair/repairer/segments.go
If satellite can't find enough nodes to successfully download a segment,
it probably is not the fault of storage nodes.
Change-Id: I681f66056df0bb940da9edb3a7dbb3658c0a56cb
What: 
Why:
- Test 1:
- Test 2:
=> satellite/repair: only record audit result if segment can be downloaded

web/satellite/src/components/objects/BucketItem.vue, web/satellite/src/components/objects/BucketsView.vue
User could confirm delete bucket action without entering bucket name.
fix for this issue https://github.com/storj/storj/issues/4296
Change-Id: Ic76f59885fd5bd812609f831f8887c07f02360a8
What: 
Why:
- Test 1:
- Test 2:
=> web/satellite: fix delete bucket issue

storagenode/reputation/service.go
Missing space in the suspended message
What: minor code esthetic change
Why: missing space in message
- Test 1:
- Test 2:
=> storagenode/reputation: fix missing space in suspension message

docs/testplan/README.md, docs/testplan/TEMPLATE.md
add README and TEMPLATE for testplan
What: Added a testplan folder in docs, with a README and TEMPLATE for testplan
Why: We want community involvement with testplans, since we believe that testplans written as early as possible before implementation starts work like a checklist and as soon as we finish the implementation we can compare it to the test plan to check for any bugs. Also even before implementation is finished, if a developer can read a test plan beforehand they can prevent most bugs, hence why we believe that the earlier we write a test plan the more bugs we can prevent.
=> docs: Adding a testplan folder with a README and TEMPLATE for testplan

web/satellite/src/components/browser/FileShareModal.vue
This change fixes the social media sharing links for the object browser. More detail on this outdated PR: https://github.com/storj/storj/pull/4275
=> web/satellite: Fix social media sharing links

private/server/server.go, storagenode/console/service.go, storagenode/peer.go, web/storagenode/src/app/components/SNOContentTitle.vue, web/storagenode/src/app/store/modules/node.ts, web/storagenode/src/storagenode/api/storagenode.ts, web/storagenode/src/storagenode/sno/sno.ts, web/storagenode/tests/unit/components/DiskStatChart.spec.ts, web/storagenode/tests/unit/components/payments/EstimationPeriodDropdown.spec.ts, web/storagenode/tests/unit/store/node.spec.ts
This reverts commit 589c82f23e5630ccb7f26f36eb00511b2ba417d8.
What: 
Why: On storagenode dashboard user sees Misconfigured QUIC status which might confuse them
- Test 1:
- Test 2:
=> Revert "storagenode: display quic status on SNO dashboard"

satellite/metainfo/config.go, scripts/testdata/satellite-config.yaml.lock
Currently the rate limit has kept per satellite api endpoint.
Since we run 9+ api endpoints in production, we do not need
a limit of 1000, since the intention was to allow 1000 total.
This change reduces the effective limit given 9 instances
down to 900, which should be close enough.
Change-Id: Ia579149ccc3a12e8febe0cfd5586b8a39de40f55
What: 
Why:
- Test 1:
- Test 2:
=> satellite/metainfo: reduce default user rate limit to 100

Makefile, cmd/multinode/Dockerfile, cmd/multinode/README.md, cmd/multinode/entrypoint
Resolves https://github.com/storj/storj/issues/4547
We do not build an docker image for the multinode dashboard,
which makes monitoring for docker-focused environments harder.
This adds the basic image and ties it into CI/CD.
Change-Id: I14c01a7f1f0019f6f5c1b8fd75dc424fc362b18d
=> cmd/multinode,Makefile: build docker image for multinode dashboard

cmd/multinode/README.md
The text has been expanded a bit to clarify that it is necessary to create identity files with an example before using the Docker image.
Changed the <identity-dir> placeholder to <multinode-identity-dir> so no one confuses them with the storagenode identity files.
Changed the <storage-dir> placeholder to <multinode-config-dir> so no one confuses them with the storagenode 'config' folder.
fixed #4547
=> cmd/multinode: Add further documentation

private/testplanet/reconfigure.go, satellite/audit/verifier_test.go, satellite/nodeselection/uploadselection/criteria.go, satellite/orders/service.go, satellite/overlay/service.go, satellite/overlay/service_test.go, satellite/repair/checker/checker_test.go, satellite/repair/repair_test.go, satellite/repair/repairer/segments.go, satellite/satellitedb/overlaycache.go
For nodes in excluded areas, we don't necessarily want to remove them
from the pointer, but we do want to increase the number of pieces in the
segment in case those excluded area nodes go down. To do that, we
increase the number of pieces repaired by the number of pieces in
excluded areas.
Change-Id: I0424f1bcd7e93f33eb3eeeec79dbada3b3ea1f3a
What: 
Why:
- Test 1:
- Test 2:
=> satellite/repairer: handle excluded countries

scripts/draft-release.sh
It seems that the github API is a little slow/laggy with regards to propagation of whether a release tag has been made or not.
This sleep should fix it and avoid having to retrigger builds.
=> scripts/draft-release: add sleep to avoid race condition on uploading the binaries

cmd/uplink/cmd_ls.go, cmd/uplink/cmd_ls_test.go
With this change users can use the uplink cli in
scripts (ie. bash) more easily, since the output
can be switched to an easier processable json format.
It keeps the default of tabbed output.
Change-Id: I37e2c55f75c2250c3119fd8df8b66a766ff9096b
What: 
Why:
- Test 1:
- Test 2:
=> cmd/uplink: adding output flag for ls command

web/multinode/src/app/router/index.ts
What: The `MyNodes` section of the sidebar is not correct
Why: It is currently spelled as `MyNodes` when it should be `My Nodes` to match the rest of entries in the menu.
There are no tests for this, as it is a change in a string literal of the UI and there were no previous tests regarding this.
It has no performing impact, as it is an UI change.
=> web/multinode: Fix `My Nodes` sidebar item spelling

web/satellite/src/views/DashboardArea.vue
Fixed main content width to be appropriate.
In case of very long access grant name (100+ symbols) main content gets overlapped with window border. That's an unhandled edge case.
Change-Id: I42ef709edc8454f054baa52231c605afadc471e2
What: 
Why:
- Test 1:
- Test 2:
=> Release v1.56.2

satellite/console/emailreminders/chore.go, scripts/testdata/satellite-config.yaml.lock
What: Disable account activation reminder email.
Why: In the early days customers had to create multiple accounts (fill out signup form) with the same email address in order to resend the activation email. At the end the customer activated one account. The other accounts are still in the satellite DB and would now trigger an account activation reminder email. We have to disable the reminder email for the moment and cleanup the satellite DB first.
- Test 1:
- Test 2:
=> satellite/console: disable account activation reminder email

satellite/metabase/iterator.go
This change reverts satellite/metabase/iterator.go of 7390f389c to the
previous version (without optimization) but leaves added benchmarks in
place.
We noticed that this optimization doesn't work and actually elevates
listing times for most buckets, hence the revert until we come up with a
better idea.
Benchmarks:
name                                                old time/op new time/op delta
NonRecursiveListing/Postgres/listing_no_prefix-8    1.30ms ± 4% 4.52ms ± 4% +246.92% (p=0.008 n=5+5)
NonRecursiveListing/Postgres/listing_with_prefix-8  3.26ms ± 3% 4.44ms ± 2%  +36.19% (p=0.008 n=5+5)
NonRecursiveListing/Cockroach/listing_no_prefix-8    618µs ± 3% 2225µs ± 2% +259.94% (p=0.008 n=5+5)
NonRecursiveListing/Cockroach/listing_with_prefix-8 1.81ms ± 5% 2.60ms ± 5%  +43.96% (p=0.008 …
=> satellite/metabase: revert non-recursive listing optimization

satellite/payments/stripecoinpayments/service.go
When a customer has no pending line items, an invoice will not be generated for them and the Stripe client method responsible for creating new invoices returns nil. This change adds a nil check to account for this possibility to ensure that no panics are caused by attempted processing of the invoice.
Change-Id: Id184d027d7447f0ef876db58601ab6cf63927fc5
What: 
Why:
- Test 1:
- Test 2:
=> point release 1.66.4 - do not reference nil invoice

satellite/audit/chore.go, satellite/audit/queue.go, satellite/audit/worker.go, satellite/satellitedb/verifyqueue.go, satellite/satellitedb/verifyqueue_test.go, scripts/testdata/satellite-config.yaml.lock
What: 
Why:
add help performance of pushing to audit queue
- Test 1:
- Test 2:
=> point release v1.68.2

satellite/metabase/rangedloop/provider.go, satellite/metabase/rangedloop/rangedlooptest/countobserver.go, satellite/metabase/rangedloop/rangedlooptest/providermock.go, satellite/metabase/rangedloop/service.go, satellite/metabase/rangedloop/service_test.go, satellite/rangedloop.go, scripts/testdata/satellite-config.yaml.lock
Minimal implementation of the ranged (=parallel) segment loop
service, to improve performance over the exiting loop.
Has tests with a an inmemory segment database
and example observer.
Does not have yet: database link, observer duration tracking,
suspicious processed ratio guard, rate limiting, minimum execution
interval per observer, etc.
Part of https://github.com/storj/storj/issues/5223
=> satellite/metabase/rangedloop: minimal loop

satellite/metabase/rangedloop/observerstats.go, satellite/metabase/rangedloop/service.go
Only review last commit, the preceeding commits have their own PR's
Wire up duration measurement of observers with monkit.
Tested by attaching a SleepObserver, starting the rangedloop in storj-up
and navigating to http://<container>:11111/mon/stats. It reports the
following statistic:
completed-observer-duration,observer=*rangedlooptest.SleepObserver,scope=storj.io/storj/satellite/metabase/rangedloop duration=10.000117
=> satellite/metabase/rangedloop: monkit durations

satellite/metabase/rangedloop/observerstats.go, satellite/metabase/rangedloop/rangedlooptest/callbackobserver.go, satellite/metabase/rangedloop/rangedlooptest/infiniteprovider.go, satellite/metabase/rangedloop/service.go, satellite/metabase/rangedloop/service_test.go
Only review the last commit, preceeding commits have their own PR's. First review https://github.com/storj/storj/pull/5350
Support interruption of the ranged segment loop through context.
Part of https://github.com/storj/storj/issues/5223
=> satellite/metabase/rangedloop: cancellation

satellite/metabase/streamstat.go
Previous version of SQL query was causing full table scan.
Output of EXPLAIN:
---
distribution: local
vectorized: true
• lookup join
│ table: segments@segments_pkey
│ equality: (?column?) = (stream_id)
│ pred: remote_alias_pieces IS NOT NULL
│
└── • union
│
├── • values
│     size: 1 column, 1 row
│
└── • scan
missing stats
table: segment_copies@segment_copies_pkey
spans: [/'\xff135285155378d980b8c49148cef3ca' - /'\xff135285155378d980b8c49148cef3ca']
---
=> satellite/metabase: fix GetStreamPieceCountByNodeID full table scan

cmd/storagenode/cmd_dashboard.go
Cherry picked commit to cut a new release with a fix to https://forum.storj.io/t/error-dashboard-sh-v1-77-2/22374/4
=> cmd/storagenode: flag to configure identity dir for dashboard config

cmd/storagenode/main.go, cmd/storagenode/service_nonwindows.go, cmd/storagenode/service_windows.go
I am proposing to create a v1.78.3 which includes an important fix for windows based Storagnodes.
This commit changes only the Storagenodes binary, and I tested the new binary in a windows environment.
=> cmd/storagenode: use the right subcommand for restarting windows services

Makefile, cmd/satellite/Dockerfile
… files
the inspector tool of satellite is removed recently. We need to remove it from the build/docker files.
Change-Id: Icd75474ea64fe5f9dd4ed76d8597982108f93536
What: 
fix for Jenkins job
Why:
- Test 1:
- Test 2:
=> point release 1.80.1-rc

cmd/satellite/entrypoint
What: 
satellite/entrypoint: Ignore unset variable errors while checking for VALID_EXECUTABLE
Otherwise core and ranged loop fail at startup with "/entrypoint: line 94: $1: unbound variable"
- Test 1:
- Test 2:
=> cherry-pick satellite/entrypoint: ignore unset variable

satellite/console/consoleweb/server.go, scripts/testdata/satellite-config.yaml.lock
What: Enable gallery view and limits area in production by default
Why: It looks good on the QA satellite. Enabling it by default will simplify the UI tests.
- Test 1:
- Test 2:
=> satellite/console: Enable gallery view and limits area by default

satellite/metabase/commit.go, satellite/metabase/commit_test.go, satellite/metainfo/endpoint_object_test.go
With pending_objects table support enabled we missed passing correctly expiration time from pending object to committed object. This change updates commit query to take into account expiration time.
Change-Id: I67146d5b2f7f0bda02925d16275fbc59acb705bd
What: 
fix for expiration
Why:
- Test 1:
- Test 2:
=> point release v1.88.1

web/satellite/src/types/browser.ts
What: 
Add .md .json .xml as text preview types.
Add .webp format for image preview.
Add .ogv format for video preview.
Add .aac .flac for audio preview.
Add all these plus more extensions to show the correct icons in the browser.
Why:
Enabling more file types for preview in the browser.
=> web/satellite: update preview types and icons

satellite/buckets/db.go, satellite/metainfo/endpoint_object.go
For now we would like to use metabase.ListObjects only for buckets with versioning state Versioned or Suspended. By accident buckets with VersioningUnsupported state were also on that list.
Change-Id: If2068c722d7e775b5f014a87f7afdee4267c7f32
What: 
Why:
- Test 1:
- Test 2:
=> satellite/metainfo: fix listing for VersioningUnsupported buckets

satellite/nodeselection/config.go, satellite/nodeselection/selector.go, satellite/nodeselection/selector_test.go
Cherry-pick of #66d6b2e66
```
We have a node selection strategy to choose randomly from different groups (like last_net).
But we have a specific case for Storj Select program (and private installs),
where we have smaller groups (like different providers), but the number of groups might be limited (let's say a few dozens).
The proposed algorithm is the following.
* let's iterate over the groups in random order
* from each group, select one node randomly
* nodes which are already selected will be ignored
* at the end of the iteration we will start to check each group again (if not enough groups)
Change-Id: I207ccb6e70122fd4e7b9d9acc0667a809492372e
```
=> satellite/nodeselection: new node selection for balancing between small groups

storagenode/blobstore/blob.go, storagenode/blobstore/filestore/dir.go, storagenode/blobstore/filestore/store.go, storagenode/blobstore/filestore/store_test.go, storagenode/blobstore/testblobs/bad.go, storagenode/blobstore/testblobs/slow.go, storagenode/pieces/cache.go, storagenode/pieces/cache_test.go, storagenode/pieces/deleter.go, storagenode/pieces/store.go, storagenode/pieces/store_test.go, storagenode/piecestore/endpoint_test.go, storagenode/retain/retain.go
What: 
Use the timestamp for which a bloom filter was generated to start measuring 7 days of a piece's stay in the trash directory, as opposed to the time of moving the file.
Why:
If a given bloom filter was generated at a specific date, and a piece uploaded before that date is not matching it, this means the satellite already expects the piece to be trashed. Yet given that the garbage collection procedure may take a lot of time, some pieces will effectively stay on a node for far longer than the 7 days expected by the satellite. This patch corrects this behavior.
- Test 1:
- Test 2:
=> storagenode: trash with Bloom filter's generation timestamp

satellite/metainfo/endpoint_bucket_test.go, satellite/metainfo/endpoint_bucket_test_placement.yaml, satellite/overlay/service.go
…cements
we tried to be backward compatible, and placement.GetAnnotation("location") can return with the name from the YAML based , but code was not prepared for placement.NodeFilter.GetAnnotation("location")
Easy fix is using the new placement struct instead.
Change-Id: I10f814b46a3564207d01628796d205f676847dbe
What: 
Why:
- Test 1:
- Test 2:
=> cherry pick v1.98.2

satellite/satellitedb/dbx/billing.dbx, satellite/satellitedb/dbx/satellitedb.dbx.go, satellite/satellitedb/dbx/satellitedb.dbx.pgx.sql, satellite/satellitedb/dbx/satellitedb.dbx.pgxcockroach.sql, satellite/satellitedb/migrate.go, satellite/satellitedb/migratez.go, satellite/satellitedb/testdata/postgres.v261.sql
Due to a mismatch in the primary key name of the storjscan_payments table, the migration of the primary key is being rolled back.
What: 
Why:
- Test 1:
- Test 2:
=> cherry-pick fix migration v261

Jenkinsfile.public
Match arguments passed to `golangci-lint` and `go-licenses` from Jenkinsfile.premerge and Jenkinsfile.verify.
These changes were made recently, e.g. by 82b05dc1be58eac, 67e397d68ff265, but not in Jenkinsfile.public.
What: 
Why:
- Test 1:
- Test 2:
=> Jenkinsfile.public: Fix lint stage

satellite/gc/piecetracker/observer.go, satellite/gc/piecetracker/observer_test.go, satellite/gc/piecetracker/piecetracker.go, satellite/satellite-config.yaml.lock
Single SQL query to update all nodes pieces found by piece tracker is an exhausting operation. It become problematic after updating CRDB version to 23.4.  This change puts all update operation into batches.
https://github.com/storj/storj/issues/6922
What: 
fix emergency 2024-04-17
Why:
- Test 1:
- Test 2:
=> point release v1.102.4

satellite/overlay/config.go, satellite/satellite-config.yaml.lock, storagenode/piecestore/endpoint.go
What: Increase the free space buffer from 500MB to 5GB
Why: The satellite is caching the node information for 5 minutes. Ideally the free space buffer is large enough so that the node can keep accepting uploads for additional 5 minutes. If the buffer is too small the customer will get a higher number of error messages on uploads. In order to avoid these error messages and give the customer best possible service even in times with high upload activity we need to increase the buffer. At 100MBit/s that would be 3.75GB. I rounded it up to 5 GB. It is very unlikely that a storage node will ever be hit by such an upload speed. With our recent performance improvements it is now possible so lets make sure the customer could hit the nodes with 100MBit/s each without getting errors in return. …
=> satellite/overlay: increase free space buffer to 5GB

satellite/metabase/commit.go, satellite/metabase/commit_test.go, satellite/metabase/db.go, satellite/metabase/metabasetest/run.go, satellite/metainfo/config.go, satellite/satellite-config.yaml.lock
What: Cherry pick to updates to commit object to help minimize query contention
Why: Performance gains
- Test 1:
- Test 2:
=> cherry pick commit object changes into release v1.104

storagenode/collector/service_test.go, storagenode/pieces/cache.go
We want to make sure that the used space cache is updated when expired pieces are deleted.
Refs: https://github.com/storj/storj/issues/7025
Change-Id: I85eac606157d730832090cd7a79240e8854c3f5b
What: 
Why:
- Test 1:
- Test 2:
=> point release v1.107.3

storagenode/pieces/cache.go, storagenode/pieces/filewalker_test.go, storagenode/pieces/filewalkerdb_test.go, storagenode/storagenodedb/gcprogress.go
The query was missing the values keyword which results in a syntax error. The basic db test couldn't catch that because it was only hitting the cache.
This patch fixes the query and also adds some basic tests to the filewalker.
Change-Id: Iab108025ca9f38c0074ce0576e09ed76e40a8b45
What: 
Why:
- Test 1:
- Test 2:
=> storagenode/storagenodedb: fix query in gcprogress.Store

Makefile
What: 
Go 1.21+ requirese at least Windows 10 or Windows Server 2016. The previous Windows versions have reached EOL, however we want to give Storage Node Operators time to upgrade their systems.
Why:
- Test 1:
- Test 2:
=> cherry-pick v1.108

Jenkinsfile.public
These env vars were originally added to Jenkinsfile.premerge, (3bd94df9c7762f000408) but they need to be in Jenkinsfile.public to fix Github builds.
=> Jenkinsfile.public: fix backwards compatibility tests

satellite/metabase/db.go, satellite/metabase/db_test.go, satellite/metainfo/config.go, satellite/metainfo/config_test.go
Using ExtendedConfig its hard to process ids list in every place. It's easy to miss adding extended config in needed place. With custom flag it will be processed always without need for adding it manually everywhere.
We can replace other []string for UUIDs with new type with subsequent changes.
=> satellite/metainfo: add UUIDsFlag for uuids list

satellite/metabase/list_segments.go
PlacementConstraint implements spanner decode already and spannerutil.Int doesn't work for nullable columns.
Change-Id: Ia8465241893b1f7e9602a7e3fb0d7e6a7d51ddba
=> satellite/metabase: fix ListSegments argument

scripts/release.sh
it has come to my attention that we do release.sh
for binaries other than storagenode and they may
not have been built on a tag with tag-release.sh
so they may not be set as release builds.
this changes release.sh to just always do a release build because it's release.sh.
Change-Id: Ia3bad5d5fc4e6e079820f8b91774f07609701f53
What: 
Why:
- Test 1:
- Test 2:
=> cherry-pick scripts/release.sh: add back better ldflags

scripts/release.sh
it has come to my attention that we do release.sh
for binaries other than storagenode and they may
not have been built on a tag with tag-release.sh
so they may not be set as release builds.
this changes release.sh to just always do a release build because it's release.sh.
Change-Id: Ia3bad5d5fc4e6e079820f8b91774f07609701f53
What: 
Why:
- Test 1:
- Test 2:
=> cherry pick v1.116.5

satellite/satellitedb/invoiceprojectrecords.go, satellite/satellitedb/overlaycache.go
Using an extra `v IN (SELECT x FROM UNNEST(?))` makes the query planner perform suboptimally. Using `v IN UNNEST(?)` should be sufficient.
Change-Id: I2e321134a05bab0a7ee73b3b38454c0dc3cc0c95
What: 
Why:
- Test 1:
- Test 2:
=> satellite/satellitedb: optimize unnest queries

testsuite/rolling-upgrade/start-sim.sh
When using:
git tag -l --sort -version:refname | grep -v rc | head -1
The head may stop before grep has processed all the data, hence it will end up writing to a closed pipe. Causing a "exit code 141" failure.
The fix is to consume the full output from grep to avoid the failure.
{ head -1; cat >/dev/null; }
An alternative would be to disable pipefail, but that may hide other errors.
Change-Id: I6918eac14e8df39dc4d702531ed011a9c6354662
What: 
Why:
fix for jenkins pipeline
- Test 1:
- Test 2:
=> cherry-pick v1.118.7

satellite/metainfo/endpoint.go, satellite/metainfo/endpoint_bucket.go, satellite/metainfo/endpoint_object.go, satellite/metainfo/endpoint_segment.go
Main reason for this change is to handle Spanner context cancellation errors correctly but at the same time it makes more sense to improve error handling in general.
This change wraps all places where we were returning internal error with utility function that will try to convert received errors into correct rpc error.
We are reusing error conversion method for metabase because it also covers some general errors like context cancellation, context deadline exceeded, etc.
Change-Id: I8fe87d578d9ed431e81acaa3f83f043af7908180
What: 
Why:
- Test 1:
- Test 2:
=> satellite/metainfo: improve error handling

satellite/analytics/service.go, satellite/analytics/service_test.go, satellite/console/consoleweb/consoleapi/analytics.go
HubSpot appears to send the 'x-hubspot-request-timestamp' value in Unix timestamp format instead of RFC 3339. This change updates the approach used to validate this header.
Change-Id: I5454f20031e20bc87f8a501aa201c02d50acd7d9
What: 
fix for timestamp format
Why:
- Test 1:
- Test 2:
=> cherry pick v1.123.2

cmd/satellite/delete_data.go, cmd/satellite/delete_data_test.go, cmd/satellite/main.go, satellite/gc-bf.go, satellite/metabase/adapter.go, satellite/metabase/rangedloop/observerstats.go, satellite/metabase/rangedloop/providerdb.go, satellite/metabase/rangedloop/service_test.go, satellite/metabase/stats.go, satellite/metabase/stats_test.go
The main goal for this change is to compare number of segments processed by loop and number of segments in DB before and after loop. This comparison make sense only if all parts are using the same stale read timestamp. This should give us the answer if the loop is skipping segments or not.
Implementation is similar to `LiveCountObserver` but for now I wanted to keep this only for GC bloom filter generation process.
This change has only basic tests, as it would require more work and I'm not sure if this code will live long.
Change-Id: Ic4d6cfc123adb1dc0141410dd6151ee7690702d8
What: 
Why:
- Test 1:
- Test 2:
=> v1.123.3-rc

satellite/metabase/list_objects.go
Change-Id: If05eee16ee0604042dd1d638e58f53f5efd705f7
What: 
given these queries are read-only it seems
more prudent to return an error and keep the
process running than to panic.
Why:
- Test 1:
- Test 2:
=> cherry-pick v1.124.3

web/satellite/src/components/InputCopyButton.vue, web/satellite/src/components/dialogs/ShareDialog.vue
We recently added direct download links to the share dialogs in the UI, which added some confusion as to which link the users should copy. This change improves the explanation of the shared links, including additional information about each link. As well as organizing the dialogs with tabs, links, social, and embed, and adding icons. Using only one line input fields for the links for a more compact UI. The copy link button changes to Copy Code for the embed tab. Added a "default" chip tag for the preview link if there is also a direct link available.
=> web/satellite: improve the share dialogs

satellite/metabase/adapter.go, satellite/metabase/commit.go, satellite/metabase/copy_object.go, satellite/metabase/raw.go
This change was made to overcome Spanner mutations limit for transactions. Our limit 10k of segments for server side copy was too big for single Spanner transaction. With this update everything except getting version for new object and committing new object is outside transaction.
New logic have some big implications. With this approach we may have segments detached from object if last step (commit object) will fail. We will need a process to find and remove such segments.
Change-Id: I0869a610c4f2d6774b53684c6e055cf1997f31ad
What: 
Why:
- Test 1:
- Test 2:
=> Point release v1.135.5
