- .gitignore
- Makefile
- pkg/overlay/overlay.go
- pkg/overlay/service.go
- protos/google/duration.proto
- protos/overlay/overlay.proto
- scripts/build-protos.sh
This is the proposed proto definition for the overlay network
> overlay proto file

- examples/eestream/serve/main.go
- pkg/ranger/file.go
- pkg/ranger/file_test.go
- pkg/ranger/reader.go
implement a Ranger based on an *os.File
> pkg/ranger: FileRanger

- pkg/ranger/content.go
This is another performance improvement for the eestream library when working with http rangers. It's independent from https://github.com/storj/storj/pull/22.
The `ServeContent` function had a premature content type detection. This detection requires check of the first 512 bytes of the content, which led to an additional `Range(0, 4096)` call to each of the farmers.
However, detecting the content type at this point is only useful for processing multi-range requests, which is not the usual use case for content streaming.
This PR moves the content type detection to the code block related to multi-range requests, to avoid the extra `Range` request for the content streaming use case.
Note that the content type will still be properly detected and included in the response at a later moment, …
> Avoid extra Range requests for content type detection

- pkg/telemetry/client.go
- pkg/telemetry/common.go
- pkg/telemetry/server.go
- pkg/telemetry/tm_test.go
- pkg/telemetry/utils.go
for sending metrics to and from things
> pkg/telemetry: telemetry package using zeebo/admission

- cmd/minio/main.go
- pkg/miniogw/gateway-storj.go
- scripts/travis-deps.sh
@aligeti I figured out how to get this into our repo. might take some setup locally, but the test should pass here on travis
> pkg/miniogw: a minio-based s3 gateway for storj. just stubs right now

- cmd/minio/main.go
- cmd/netstate/main.go
- cmd/piecestore/main.go
- pkg/piecestore/pstore.go
> minio/netstate/piecestore: integrate with pkg/process for telemetry reporting

- pkg/ranger/grpc.go
Leftover from https://github.com/storj/storj/pull/72
> Fix the position of offset and length in gRPC Ranger

- examples/udp-forwarder/forwarder.go
* server udp communication
* goimports
* goimports
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/84)
> udp-forwarding: demo week work!

- internal/pkg/readcloser/lazy.go
- pkg/eestream/decode.go
- pkg/eestream/encode.go
- pkg/eestream/pad.go
- pkg/eestream/pad_test.go
- pkg/eestream/rs_test.go
- pkg/eestream/transform.go
- pkg/eestream/transform_test.go
- pkg/piecestore/pstore.go
- pkg/ranger/content.go
- pkg/ranger/file_test.go
- pkg/ranger/grpc.go
- pkg/ranger/grpc_test.go
- pkg/ranger/http.go
- pkg/ranger/http_test.go
- pkg/ranger/reader.go
- pkg/ranger/reader_test.go
- pkg/ranger/readerat.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/90)
> Add error to the return values of Ranger.Range method

- cmd/piecestore-cli/main.go
- examples/eestream/serve-collected/main.go
- examples/eestream/serve/main.go
- examples/piecestore/rpc/client/main.go
- pkg/eestream/decode.go
- pkg/eestream/encode.go
- pkg/eestream/pad.go
- pkg/eestream/pad_test.go
- pkg/eestream/rs_test.go
- pkg/eestream/transform.go
- pkg/eestream/transform_test.go
- pkg/piecestore/pstore.go
- pkg/piecestore/pstore_test.go
- pkg/piecestore/rpc/client/client.go
- pkg/piecestore/rpc/server/server.go
- pkg/ranger/content.go
- pkg/ranger/file_test.go
- pkg/ranger/grpc.go
- pkg/ranger/grpc_test.go
- pkg/ranger/http.go
- pkg/ranger/http_test.go
- pkg/ranger/reader.go
- pkg/ranger/reader_test.go
- pkg/ranger/readerat.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/99)
> Add context to Ranger.Range method

- cmd/overlay/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/111)
> hardcode version

- examples/paths/main.go
- pkg/paths/paths.go
- pkg/paths/paths_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/101)
> Define Path type

- Gopkg.lock
- cmd/overlay/Dockerfile
alpine uses musl, debian uses glibc, they're API compatible, but not filename compatible
so the binary was looking for /lib/x86_64-linux-gnu/libc.so.6 and not finding it in alpine
@brimstone
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/118)
> docker image issue fixed

- .clabot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/121)
> clabot file added

- .clabot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/123)
> added team memebers

- .clabot
clabot leave them alone!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/136)
> adds Alex and Nadine to clabot

- Jenkinsfile
- Makefile
- This PR fixes Jenkins so it starts building Docker images again.
- It doesn't do everything that Travis does.
- Next PR is to move the action of running tests into a container in order to control the environment Jenkins uses while running tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/139)
> Fix jenkins

- .clabot
adding Kiev team to CLA:
rikysya
crawter
NikolaiYurchenko
Barterio
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/149)
> adding Kiev team to CLA

- pkg/segment/segment.go
Get:
- requests pointer from pointerdb
- requests associated node IPs from overlay
- requests ranger from ecclient
Delete:
- requests pointer from pointerdb
- uses ecclient to request piece deletes
- deletes pointer from pointerdb
List:
- requests a page of pointers from pointerdb
Other notes:
* all API keys given to PointerDB are nil
* List function takes startingPath and endingPath as arguments, even though the PointerDB List function currently requires a StartingPath and Limit. So SegmentStore List will have to be updated when PointerDB List is updated.
* the function in overlayHelper needs to run parallel (and needs to be done by pointerdb)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> adds segmentStore Get, List, Delete

- pkg/process/exec.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/151)
> don't require a config file

- .travis.yml
- Jenkinsfile
- Makefile
- docker-compose.yaml
- internal/test/storage.go
- test/Dockerfile
This is mainly in response to https://github.com/storj/storj/pull/157 failling. If this is an accepable approach to testing, then #157 will need to be rebased once this is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/161)
> Add files for testing builds in docker

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/170)
> fix docker makefile

- pkg/telemetry/client_test.go
Unit tests added for telemetry package
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/152)
> Unit tests added for telemetry package

- .clabot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/171)
> updating github user to personal account 

- pkg/miniogw/config.go
- pkg/miniogw/gateway-storj.go
- pkg/storage/streams/passthrough.go
this doesn't implement streamstore, this just allows us to try and
get the june demo working again in the meantime
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/176)
> streamstore: add passthrough implementation

- cmd/hc/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/179)
> overlay: correct dockerfile db

- pkg/process/exec.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/177)
> pkg/process: don't require json formatting

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/183)
> add workaround for error "multiple registrations for /debug/requests"

- pkg/kademlia/config.go
- pkg/overlay/cache_test.go
- pkg/overlay/config.go
- pkg/overlay/config_test.go
- pkg/overlay/service_test.go
unit tests for service.go in overlay package added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/155)
> unit tests for service.go in overlay package added

- pkg/storage/ec/client.go
- pkg/storage/ec/client_test.go
Fixes https://storjlabs.atlassian.net/browse/V3-173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/186)
> Fixes V3-173 - ECClient check if given nodes are unique

- examples/pointerdb-client/main.go
- pkg/miniogw/config.go
- pkg/pointerdb/client.go
- pkg/pointerdb/client_test.go
- pkg/storage/segments/store.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/194)
> Move api key from pdb client method calls to pdb client constructor

- cmd/captplanet/setup.go
- pkg/miniogw/config.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/195)
> captplanet: configure api key

- pkg/provider/provider.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/196)
> log grpc server errors

- cmd/captplanet/run.go
- pkg/miniogw/config.go
- pkg/miniogw/mockoverlay.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/197)
> miniogw: make a Config.NewGateway helper, bypass overlay for now

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/207)
> Updating service names for docker tags

- pkg/process/exec_conf.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/206)
> fix env vars

- cmd/hc/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/208)
> Fixing docker entrypoint for satellite

- pkg/eestream/encode.go
- pkg/piecestore/rpc/client/client.go
- pkg/piecestore/rpc/server/server.go
Fixes https://storjlabs.atlassian.net/browse/V3-205
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/211)
> PSClient handles io.ErrUnexpectedEOF

- cmd/piecestore-farmer/entrypoint
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/212)
> Fixing Docker entrypoint for storage node

- pkg/storage/ec/client.go
- pkg/storage/ec/client_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/214)
> Improved error message in ECClient

- .clabot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/220)
> add phutchins to clabot

- cmd/farmer/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/202)
> captplanet standalone farmer setup

- cmd/captplanet/setup.go
- pkg/provider/certificate_authority.go
- pkg/provider/provider.go
unfortunately, we can't enable server-side tls yet because client-side tls hasn't been implemented
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/224)
> fix services after identity merge

- cmd/captplanet/setup.go
- cmd/gw/main.go
- cmd/hc/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/225)
> fix gw and hc

- Jenkinsfile
- scripts/deploy.staging.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/219)
> Adding auto deploy to staging in kube

- .travis.yml
- Makefile
- scripts/test-captplanet.sh
- scripts/travis-deps.sh
Tests running `captplanet setup`, `captplanet run`, uploading and downloading a file via the aws cli, and verifying that the uploaded file matches the downloaded file.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/226)
> Test captplanet with travis

- Gopkg.lock
- Gopkg.toml
- Makefile
- cmd/farmer/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/230)
> Fix the sha3 error with the build

- CODE_OF_CONDUCT.md
adding bullet points in "Our Standards" section
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/234)
> styling changes to the code of conduct

- cmd/farmer/Dockerfile
- cmd/farmer/entrypoint
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/237)
> Updating entrypoint and dockerfile

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/243)
> readme updates (Storj CLI)

- pkg/piecestore/rpc/client/client.go
- pkg/piecestore/rpc/client/pieceranger.go
- pkg/storage/ec/client.go
- pkg/storage/ec/client_test.go
- pkg/storage/ec/psclient_mock_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/247)
> Make PSClient a Closer, so it can be closed with utils.LogClose()

- pkg/piecestore/rpc/server/psdb/psdb.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/250)
> piecestore: only check ttl db every hour instead of every 300 nanoseconds

- pkg/dht/dht.go
- pkg/kademlia/routing.go
- pkg/kademlia/routing_helpers.go
- pkg/kademlia/routing_helpers_test.go
- pkg/kademlia/routing_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/249)
> implements connection success and fail on kad routing table

- Jenkinsfile
- Makefile
- cmd/farmer/Dockerfile
- cmd/hc/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/260)
> Attempt to fix jenkins builds

- cmd/gw/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/262)
> gw: support standard configuration via cmdline

- Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/265)
> Adding some logging to Jenkinsfile for debug

- Jenkinsfile
- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/277)
> Fix staging deploy of satellite and storage-node

- Jenkinsfile
- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/278)
> More fixes to the staging deploy process

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/288)
> go 1.11! woohoo! simplify readme

- cmd/captplanet/run.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/284)
> captplanet: customizable mock overlay host

- examples/grpc-debug/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/283)
> grpc-debug tool

- .gitignore
- Gopkg.lock
- Makefile
- go.mod
- go.sum
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/293)
> cross-compilation: fix darwin

- Makefile
- cmd/identity/certificate_authority.go
- cmd/identity/identity.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/297)
> Reduce linter concurrency

- .gitignore
- pkg/eestream/rs_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/307)
> add reed-solomon encoding benchmark

- pkg/miniogw/config.go
Extract code to get bucket store from NewGateway in order for storj cli to use bucketstore API instead of minio gateway methods
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/300)
> extract bucketstore code from NewGateway into helper

- cmd/uplink/main.go
uplink handle invalid or more than needed arguments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/305)
> uplink handle invalid or more than needed arguments

- pkg/eestream/pad.go
- pkg/ranger/reader.go
- pkg/ranger/reader_test.go
- pkg/storage/ec/client.go
- pkg/storage/streams/store.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/308)
> storage/ec: fix some Get socket leaks

- Makefile
- cmd/satellite/Dockerfile
- cmd/storagenode/Dockerfile
- cmd/uplink/Dockerfile
- scripts/fix-mock-overlay
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/306)
> Fix the binaries and Docker Images

- cmd/uplink/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/316)
> check for unsupported flags while running uplink

- cmd/uplink/main.go
@kaloyan-raev @littleskunk this is working. If you look at uplink ~/.storj/uplink/config.yaml, you'll see the newly generated aws creds. Update aws configuration with those creds, and it should work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/309)
> Create secret key

- internal/test/storage.go
- pkg/overlay/cache_test.go
Automatically selects a free port and sets up a clean instance for each test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/310)
> Use better Redis server setup with fallback

- pkg/kademlia/kademlia.go
- pkg/node/node_test.go
- pkg/overlay/client_test.go
- pkg/overlay/overlay_test.go
- pkg/overlay/service_test.go
- pkg/piecestore/rpc/server/server_test.go
Other ports may be blocked or require allowing ports when running tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/311)
> Use correct test ports

- pkg/piecestore/rpc/client/readerwriter.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/317)
> using throttle

- Makefile
- cmd/satellite/Dockerfile
- cmd/satellite/entrypoint
- cmd/storagenode/Dockerfile
- cmd/storagenode/entrypoint
- cmd/uplink/Dockerfile
- cmd/uplink/entrypoint
- docker-compose.yaml
- scripts/fix-mock-overlay
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/325)
> Normalize the Docker Bits

- pkg/piecestore/rpc/client/client.go
- pkg/storage/ec/client.go
- pkg/storage/ec/client_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/321)
> [WIP] Piece Rangers should connect lazily to storage nodes (second approach)

- pkg/piecestore/rpc/server/psdb/psdb.go
- pkg/piecestore/rpc/server/psdb/psdb_test.go
- pkg/piecestore/rpc/server/server.go
- pkg/piecestore/rpc/server/server_test.go
Improve psdb performance and cleanup code. About 5x speedup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/324)
> Safer and faster psdb

- go.mod
- go.sum
- pkg/piecestore/rpc/server/server.go
- pkg/piecestore/rpc/server/server_test.go
Validate incoming ID
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/322)
> Prevent sql injection for farmer

- pkg/miniogw/gateway-storj.go
- pkg/miniogw/gateway-storj_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/327)
> Non-recursive listing in Minio Gateway

- cmd/captplanet/run.go
- cmd/uplink/cmd/run.go
- pkg/miniogw/config.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/330)
> miniogw: simplify output

- pkg/miniogw/gateway-storj.go
- pkg/miniogw/gateway-storj_test.go
- pkg/pointerdb/pointerdb.go
- pkg/pointerdb/pointerdb_test.go
- pkg/storage/buckets/prefixed.go
- pkg/storage/streams/store.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/328)
> Filter prefix from list results

- pkg/miniogw/gateway-storj.go
- pkg/miniogw/gateway-storj_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/333)
> Fix recursive listing and deletion in S3 gateway

- .clabot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/storj/storj/332)
> thepaul signed the cla

- .travis.yml
- Jenkinsfile
After this PR goes through, Jenkins needs to be setup to only handle pushes to the master branch.
Jenkins and Travis should both pass this PR.
> Clean up Travis and Jenkins

- cmd/uplink/cmd/ls.go
- cmd/uplink/cmd/run.go
- pkg/storage/buckets/store.go
> check uplink setup

- pkg/miniogw/gateway-storj.go
Fixes https://storjlabs.atlassian.net/browse/V3-286
> MinioGW should return ObjectNotFound if non-existing file is deleted

- pkg/eestream/encode.go
Fixes https://storjlabs.atlassian.net/browse/V3-332
> Fix data race in eestream

- examples/piecestore-cli/main.go
Reducing the number of different cli API-s and formats we are using.
> examples: piecestore-cli use cobra directly

- cmd/satellite/main.go
- pkg/datarepair/checker/checker.go
- pkg/datarepair/checker/checker_test.go
- pkg/datarepair/repair.go
- pkg/datarepair/repairer/repairer.go
- pkg/datarepair/repairer/repairer_test.go
Begin setting up repairer structure
> setup repairer loop

- pkg/eestream/stripe.go
Fixes https://storjlabs.atlassian.net/browse/V3-473
This is a regression caused by #390 
The `StripeReader.pendingReaders` check was not adjusted to the change that now the given map of readers does not include readers for all Total N pieces, but just those who have successfully got a piece.
> Fix check for pending readers in StripeReader

- pkg/kademlia/config.go
- pkg/kademlia/kademlia.go
- pkg/kademlia/kademlia_test.go
- pkg/overlay/cache_test.go
The db directory is not being created while running storj in staging on kademlia.
This PR checks if the directory exists and if not creates it.
> create db directory if it does not exist

- pkg/provider/provider.go
Currently when streaming a video from captplanet, seeking ahead or stopping the video, tons of errors are logged like:
```
rpc error: code = Unavailable desc = transport is closing
rpc error: code = Canceled desc = context canceled
EOF
```
They pollute the log and it's quite confusing as the first reaction is that something wrong has happened.
This PR filters this kind of errors from zap logger in the `Provider.streamInterceptor` method.
> Reduce garbage errors in captplanet when streaming

- cmd/uplink/cmd/cp.go
> Don't override file if remote file doesn't exist

- pkg/audit/verifier.go
> remove TODO

- pkg/kademlia/kademlia_test.go
There probably is still a logical race which this doesn't fix.
> Fix TestBootstrap and TestLookup

- cmd/captplanet/run.go
- cmd/captplanet/setup.go
- pkg/datarepair/repairer/config.go
- pkg/datarepair/repairer/repairer.go
Start mini redis with captain planet for checker and repairer
> Start redis

- cmd/uplink/cmd/cp.go
Fixes:
* V3-529
* displaying progress bar even when bucket doesn't exist
> Uplink cp upload improvements

- pkg/utils/collect_errors_test.go
- pkg/utils/utils_test.go
Tests for single and multiple errors.
> pkg/utils `CollectErrors` tests 

- examples/eestream/serve-collected/main.go
- examples/eestream/serve/main.go
- examples/eestream/store/main.go
- pkg/eestream/rs_test.go
- pkg/encryption/aesgcm.go
- pkg/encryption/aesgcm_test.go
- pkg/encryption/encryption.go
- pkg/encryption/secretbox.go
- pkg/encryption/secretbox_test.go
- pkg/miniogw/config.go
- pkg/storage/streams/store.go
- pkg/storj/encryption.go
`Cipher`, `Key`, `Nonce` and `EncryptedPrivateKey` types are now part of the main `storj` package. Any encryption implementation logic is left in the `encryption` package.
>  Adapt storj and encryption packages

- pkg/storage/streams/store.go
Handle CTRL+C while using AWS CLI
> Handle CTRL+C while using AWS CLI

- pkg/encryption/aesgcm.go
- pkg/encryption/common.go
- pkg/encryption/encryption.go
- pkg/encryption/secretbox.go
Fixes https://storjlabs.atlassian.net/browse/V3-542
> Improve error handling in encryption pkg

- internal/sync2/limiter.go
- internal/sync2/limiter_test.go
- pkg/datarepair/repairer/config.go
- pkg/datarepair/repairer/repairer.go
https://storjlabs.atlassian.net/browse/V3-573
> Fix repairing run

- cmd/uplink/cmd/mount.go
Change-Id: Ib1661e1c9d3f06783854b2293579ab715d0f1c20
> uplink: fix mount and cli/gateway logical merge conflict

- README.md
> Update note about GOPATH

- pkg/piecestore/rpc/server/psdb/psdb.go
- pkg/piecestore/rpc/server/psdb/psdb_test.go
- pkg/piecestore/rpc/server/server.go
https://storjlabs.atlassian.net/browse/V3-594
> In-memory piecestore database

- cmd/captplanet/run.go
Change-Id: I37fbb76586ee3c0a40d24aad72aff2fcfc039a25
> captplanet: fix output line name

- pkg/storage/ec/client.go
- pkg/storage/ec/client_test.go
- pkg/storage/segments/store.go
Storj V3 V3-353
When we download a piece we should only try to download it from a specific amount of nodes
> download with specific number of nodes  V3-353

- cmd/s3-benchmark/awscli.go
- cmd/s3-benchmark/main.go
- cmd/s3-benchmark/minio.go
- cmd/s3-benchmark/uplink.go
At the moment the `uplink cat` has a bug and the benchmark test will error out.
> s3-benchmark test with uplink

- pkg/encryption/encryption.go
Fixes https://storjlabs.atlassian.net/browse/V3-524
> Don't encrypt empty content for buckets and 0-byte objects

- pkg/accounting/common.go
- pkg/accounting/config.go
- pkg/accounting/tally.go
- pkg/accounting/tally_test.go
- pkg/datarepair/checker/checker.go
- pkg/datarepair/checker/checker_test.go
- pkg/datarepair/checker/config.go
- pkg/datarepair/repairer/config.go
- pkg/datarepair/repairer/repairer.go
- pkg/node/server.go
- pkg/utils/utils.go
> Creates Accounting Pkg to tally at rest node storage

- pkg/satellite/satellitedb/companies.go
- pkg/satellite/satellitedb/companies_test.go
- pkg/satellite/satellitedb/users.go
- pkg/satellite/satellitedb/utils.go
- pkg/satellite/satellitedb/utils_test.go
created better functionality for converting []byte to uuid
> refactored byte to uuid converting

- cmd/satellite/main.go
- pkg/bwagreement/common.go
- pkg/bwagreement/config.go
- pkg/bwagreement/server.go
- pkg/bwagreement/server_test.go
https://storjlabs.atlassian.net/browse/V3-683
> Signature verification

- pkg/satellite/auth.go
- pkg/satellite/satelliteweb/api.go
- pkg/satellite/satelliteweb/config.go
- pkg/satellite/satelliteweb/gateway.go
- pkg/satellite/satelliteweb/satelliteql/mutation.go
- pkg/satellite/satelliteweb/satelliteql/query.go
- pkg/satellite/satelliteweb/satelliteql/typecreator.go
- pkg/satellite/satelliteweb/satelliteql/user.go
- pkg/satellite/service.go
added copyright to every file in satellite pkg
> added copyright to every file in satellite pkg

- cmd/uplink/cmd/cat.go
- cmd/uplink/cmd/cp.go
- cmd/uplink/cmd/put.go
Fixes https://storjlabs.atlassian.net/browse/V3-676
> Fix for uplink cat writing additional bytes

- cmd/captplanet/run.go
- cmd/satellite/main.go
- go.mod
- pkg/accounting/rollup/rollup.go
- pkg/accounting/tally/tally.go
- pkg/datarepair/checker/checker.go
- pkg/datarepair/checker/config.go
- pkg/datarepair/queue/queue.go
- pkg/datarepair/repairer/repairer.go
- pkg/overlay/config.go
- pkg/overlay/mocks/overlay.go
- pkg/overlay/server.go
- pkg/provider/identity.go
- pkg/statdb/dbx/gen.go
Enable checker in captplanet and staging
> Enable checker in captplanet and staging

- pkg/satellite/satelliteweb/api.go
- pkg/satellite/satelliteweb/satelliteql/query.go
- pkg/satellite/satelliteweb/satelliteql/token.go
- pkg/satellite/satelliteweb/satelliteql/typecreator.go
- pkg/satellite/satelliteweb/satelliteql/user.go
- pkg/satellite/service.go
updated token graphql query to return user on demand
> updated login api

- examples/statdb-client/main.go
- pkg/audit/reporter.go
- pkg/auth/apikey.go
- pkg/statdb/config.go
- pkg/statdb/proto/statdb.pb.go
- pkg/statdb/proto/statdb.proto
- pkg/statdb/sdbclient/client.go
- pkg/statdb/statdb.go
- pkg/statdb/statdb_test.go
* Adds `UpdateUptime()` and `UpdateAuditSuccess()` to statdb server
* Updates statdb api key validation
> Node selection 0/4: Update statdb auth/functionality

- pkg/satellite/auth.go
- pkg/satellite/satelliteweb/api.go
- pkg/satellite/satelliteweb/config.go
- pkg/satellite/satelliteweb/gateway.go
- pkg/satellite/satelliteweb/satelliteql/mutation.go
- pkg/satellite/satelliteweb/satelliteql/token.go
- pkg/satellite/satelliteweb/satelliteql/user.go
- pkg/satellite/service.go
-pass authorization claims through context instead of authorizing in each method call
-satellite user delete api
> Satellite user delete

- pkg/datarepair/queue/queue.go
- pkg/datarepair/repairer/repairer.go
- storage/redis/client_queue.go
Fixes https://storjlabs.atlassian.net/browse/V3-824
> Stops logging repairer errors for empty queue

- pkg/satellite/satellitedb/companies.go
- pkg/satellite/satelliteweb/satelliteql/company.go
- pkg/satellite/satelliteweb/satelliteql/mutation.go
- pkg/satellite/satelliteweb/satelliteql/user.go
- pkg/satellite/service.go
-update company api
-small refactoring
> update company api

- pkg/satellite/service.go
- pkg/satellite/users.go
- pkg/satellite/validation.go
intial validation of satellite.User
> intial user validation

- cmd/uplink/cmd/cp.go
https://storjlabs.atlassian.net/browse/V3-618
> Upload with target as prefix save file with prefix name

- pkg/satellite/satelliteweb/satelliteql/mutation.go
- pkg/satellite/satelliteweb/satelliteql/project.go
- pkg/satellite/service.go
-satellite projectmembers add api
-satellite projectmembers delete api
> satellite projectmembers add and delete api

- pkg/satellite/projects.go
- pkg/satellite/satellitedb/dbx/satellitedb.dbx
- pkg/satellite/satellitedb/dbx/satellitedb.dbx.go
- pkg/satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
- pkg/satellite/satellitedb/projects.go
- pkg/satellite/satellitedb/projects_test.go
- pkg/satellite/satelliteweb/satelliteql/project.go
- pkg/satellite/satelliteweb/satelliteql/query.go
- pkg/satellite/satelliteweb/satelliteql/typecreator.go
- pkg/satellite/service.go
- web/satellite/src/api/projects.ts
- web/satellite/src/components/common/HeaderedInput.vue
- web/satellite/src/components/dashboard/newProject/NewProjectPopup.vue
- web/satellite/src/components/projectDetails/ProjectDetailsArea.vue
- web/satellite/src/store/modules/projects.ts
- web/satellite/src/types/projects.d.ts
1. Added CompanyName field to Project entity
2. Project Name is not updatable now
3. Insert in repo and CreateProject in service updated to use CompanyName for project creation
4. GetUsersProjects method in service updated and now returns only projects in which current user participate
5. Updated frontend, to support CompanyName
> Satellite Projects db entity and api updated

- Makefile
- cmd/captplanet/run.go
- cmd/captplanet/setup.go
- cmd/uplink/cmd/run.go
- internal/testplanet/identities.go
- internal/testplanet/node.go
- pkg/miniogw/config.go
- pkg/peertls/extensions.go
- pkg/peertls/peertls.go
- pkg/peertls/peertls_test.go
- pkg/peertls/utils.go
- pkg/provider/certificate_authority.go
- pkg/provider/identity.go
- pkg/provider/identity_test.go
- pkg/provider/provider.go
- pkg/provider/utils.go
https://storjlabs.atlassian.net/browse/V3-627
> TLS extension processing

- cmd/satellite/main.go
https://storjlabs.atlassian.net/browse/V3-860
> Enable audit service on satellite

- CODE_OF_CONDUCT.md
making sure it lines up with our adapted code of conduct https://storj.io/code-of-conduct
> Adding CODE_OF_CONDUCT to storj/storj repo 

- cmd/uplink/cmd/cp.go
This fixes a regression caused by #775 that causes the following error when uploading files:
`object not found: key not found: rpc error: code = NotFound desc = boltdb error: key not found: l/littleskunk/4UWVMNrc4_nS5V8CPt5AOn_t1Y5pjBhUeO24rAwTKULTP5XIES60W_6n`
For the moment the `stream.Upload` must be closed before calling `MutableObject.Commit`.
> Fix "key not found" error on uploading files with uplink cli

- pkg/satellite/satelliteweb/satelliteql/project.go
- pkg/satellite/satelliteweb/satelliteql/projectmember.go
- pkg/satellite/satelliteweb/satelliteql/typecreator.go
- pkg/satellite/service.go
Initial api for querying members
> [WIP] get project members of current project

- cmd/uplink/cmd/cp.go
- pkg/miniogw/gateway-storj.go
As discussed in https://github.com/storj/storj/pull/807#pullrequestreview-183125668
> Better error handling of stream.Upload.Close

- pkg/piecestore/psserver/retrieve.go
Fixes https://storjlabs.atlassian.net/browse/V3-931
> Improve piece retrieving log with offset and length

- pkg/satellite/satellitedb/users.go
- pkg/satellite/satelliteweb/satelliteql/mutation.go
- pkg/satellite/satelliteweb/satelliteql/user.go
- pkg/satellite/service.go
- pkg/satellite/users.go
- pkg/satellite/validation.go
updated user updated api, separated company and user creation
> updated user updated api, separated company and user creation

- cmd/captplanet/run.go
- cmd/captplanet/setup.go
- cmd/storagenode/main.go
- pkg/datarepair/repairer/config.go
- pkg/kademlia/config.go
- pkg/kademlia/kademlia_test.go
- pkg/provider/certificate_authority.go
Fixes https://storjlabs.atlassian.net/browse/V3-835
Make captain planet only use 10 nodes instead of 100
> Reduce number of nodes in captplanet to 10

- cmd/captplanet/setup.go
- pkg/cfgstruct/bind.go
- pkg/cfgstruct/bind_test.go
this will allow some config cleanups in a future PR
> cfgstruct.Bind: support nested config paths

- .travis.yml
Try enabling race for captplanet.
> Enable -race in captplanet tests

- cmd/pdbinspect/main.go
Uses UTC for time format and fixes pointer expiration date format.
> pdbinspect time format fix

- pkg/bwagreement/config.go
- pkg/datarepair/checker/config.go
- pkg/piecestore/psclient/client.go
- pkg/piecestore/psserver/agreementsender/agreementsender.go
- pkg/piecestore/psserver/psdb/psdb.go
- pkg/process/metrics.go
* removes unused params (bwagreements, irreparable)
* converts `_` to `-` for some flags
> Parameters cleanup

- pkg/pb/gen.go
I had to search today a way to regenerate protobuf files so I think it will be helpful :)
> Add gen.go for protobuf

- pkg/satellite/satelliteweb/satelliteql/mutation.go
- pkg/satellite/service.go
Satellite user api:
- delete updated to require user password
> satellite user delete updated to require user password

- go.sum
- pkg/accounting/tally/tally.go
- pkg/pb/pointerdb.proto
- pkg/ranger/content_test.go
removes a few todos in accounting tally, pointerdb, and ranger test
> removes a few todos

- satellite/satellitedb/irreparabledb.go
Fixes db transaction usage in `IncrementRepairAttempts` method
> Fix irreparable db transaction usage

- cmd/identity/certificate_authority.go
- cmd/identity/identity.go
- cmd/identity/main.go
- pkg/peertls/extensions.go
- pkg/peertls/peertls.go
- pkg/peertls/peertls_test.go
- pkg/peertls/utils.go
- pkg/provider/cert_authority_test.go
- pkg/provider/certificate_authority.go
- pkg/provider/identity.go
- pkg/provider/utils.go
> Cert revocation CLI

- pkg/satellite/service.go
- updated project deletion to check owner
- updated user deletion to check for project ownership
- service.Authorize and other methods now wraps all auth related errors in ErrUnathorized class
> updated project and user deletion

- pkg/satellite/projectmembers.go
- pkg/satellite/satellitedb/projectmembers.go
- pkg/satellite/satellitedb/projectmembers_test.go
- pkg/satellite/satelliteweb/satelliteql/project.go
- pkg/satellite/service.go
satellite:
- project members query added limit and offset
> satellite project members pagination api

- pkg/audit/reporter.go
- pkg/audit/service.go
- pkg/audit/verifier.go
- pkg/audit/verifier_test.go
- pkg/datarepair/checker/checker.go
- pkg/inspector/server.go
- pkg/overlay/cache.go
- pkg/statdb/statdb.go
- pkg/statdb/statdb_test.go
- satellite/satellitedb/statdb.go
https://storjlabs.atlassian.net/browse/V3-837
* Update statdb args/return values to minimize structs
* Simplify statdb.Update() to update all stats instead of an arbitrary subset determined by flags
* Remove CreateIfNotExists logic from statdb.Update()
* Simplify audit code structure
> Refactor statdb

- satellite/satellitedb/statdb.go
https://storjlabs.atlassian.net/browse/V3-837
* add sql transactions to statdb
* update statdb errors to use satellitedb error class
> Statdb transactions

- cmd/overlay/cache.go
- cmd/overlay/main.go
- internal/testplanet/node.go
- internal/testplanet/planet.go
- pkg/audit/cursor_test.go
- pkg/audit/service.go
- pkg/datarepair/repairer/config.go
- pkg/inspector/server.go
- pkg/miniogw/config.go
- pkg/overlay/cache.go
- pkg/overlay/cache_test.go
- pkg/overlay/client.go
- pkg/overlay/client_test.go
- pkg/overlay/config.go
- pkg/overlay/config_test.go
- pkg/overlay/server.go
- pkg/overlay/server_test.go
- pkg/piecestore/psserver/agreementsender/agreementsender.go
* `overlay.NewOverlayCache` -> `overlay.NewCache`
* `overlay.NewOverlayClient` -> `overlay.NewClient`
* remove kademlia dependency
> Cleanup overlay methods and names.

- pkg/satellite/satelliteweb/satelliteql/mutation.go
- addProjectMember api modified to accept list of users
- deleteProjectMember api modified to accept list of users
> delete and add projectmember api now accepts list of users

- cmd/captplanet/run.go
https://storjlabs.atlassian.net/browse/V3-861
> Add sleep for satellite startup

- pkg/satellite/satelliteweb/satelliteql/mutation.go
- pkg/satellite/satelliteweb/satelliteql/user.go
- pkg/satellite/service.go
- add project members by email list api update
- delete project members by email list api update
> Satellite add/delete project members by email api

- pkg/satellite/apikeys.go
- pkg/satellite/database.go
- pkg/satellite/satellitedb/apikeys.go
- pkg/satellite/satellitedb/db.go
- pkg/satellite/satellitedb/dbx/satellitedb.dbx
- pkg/satellite/satellitedb/dbx/satellitedb.dbx.go
- pkg/satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
- pkg/satellite/service.go
- added satellite apikey entity 
- added satellite apikeys interface
- added satellite apikeys db implementation
- added satellite service method for apikey creation
> Satellite api keys repo and service method added

- pkg/identity/certificate_authority.go
- pkg/identity/setup.go
- pkg/identity/utils.go
- pkg/process/exec_conf.go
I know it's not really "progress", but keeping track of the highest difficulty seen so far gives that illusion to the user.
> Fix CA Timeout and show progress to the user

- .travis.yml
- Makefile
- cmd/certificates/main.go
- cmd/storagenode/main.go
- pkg/certificates/certificates.go
- pkg/certificates/certificates_test.go
- pkg/identity/certificate_authority.go
- pkg/identity/identity.go
- pkg/peertls/extensions.go
- scripts/test-certificate-signing.sh
- scripts/utils.sh
> CSR automation in storage node setup

- internal/sync2/fence.go
- internal/sync2/fence_test.go
- internal/sync2/sleep.go
- internal/sync2/sleep_test.go
Added fence and sleep for proper waiting between processes. Needed for storj-sdk.
> sync2: add Fence and Sleep

- pkg/satellite/service.go
- pkg/satellite/validation.go
transform email to lower case before user creating, updating, authorization
> normalize login email

- storage/storelogger/logger.go
https://storjlabs.atlassian.net/browse/V3-609
> truncate store value logging

- pkg/accounting/tally/tally_test.go
- pkg/bwagreement/server.go
- pkg/bwagreement/test/common.go
- pkg/bwagreement/test/server_test.go
- pkg/pointerdb/pointerdb.go
- satellite/satellitedb/bandwidthagreement.go
- satellite/satellitedb/dbx/satellitedb.dbx
- satellite/satellitedb/dbx/satellitedb.dbx.go
- satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
- satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
- satellite/satellitedb/locked.go
https://storjlabs.atlassian.net/browse/V3-1022
> Satellite accepts manipulated paychecks V3-1023

- pkg/audit/verifier.go
https://storjlabs.atlassian.net/browse/V3-1015
> do not try to dial nil node from audit verifier

- pkg/bwagreement/server.go
- pkg/bwagreement/test/server_test.go
https://storjlabs.atlassian.net/browse/V3-1022
> Empty satellite signature crashing

- cmd/storj-sim/network.go
> nonessential edits for storj-sim

- cmd/storagenode/Dockerfile
- cmd/storagenode/main.go
- pkg/piecestore/psserver/server.go
Updates spacing and colors on SNO dashboard
> Sno dashboard updates

- pkg/piecestore/psserver/config.go
- pkg/piecestore/psserver/readerwriter.go
- pkg/piecestore/psserver/server.go
- pkg/piecestore/psserver/server_test.go
storagenode only accepts data from satellites it has approved
> storagenode approvedSatelliteIDs

- satellite/console/consoleweb/consoleql/mutation.go
- satellite/console/consoleweb/consoleql/mutation_test.go
- satellite/console/consoleweb/consoleql/query_test.go
- satellite/console/service.go
- satellite/console/users.go
- satellite/satellitedb/dbx/satellitedb.dbx
- satellite/satellitedb/dbx/satellitedb.dbx.go
- satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
- satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
- satellite/satellitedb/locked.go
- satellite/satellitedb/users.go
- satellite/satellitedb/users_test.go
In this pr i added functionality to confirm your registration.
During registration we create and insert user in db without email.
Email is now nullable.
Also this method generates new token, in which he will place ID, of created user, email, from input parameters, and expire date. 
To finish up registration and activate account - user should pass his activation token to ActivateAccount method, which will parse the token and update users email ( if needed )
> V3-1091 Extend Users table with IsActive functionality

- cmd/storagenode/main.go
Fixes https://storjlabs.atlassian.net/browse/V3-1127
> V3-1127 Properly initialize default config dir in storagenode binary

- .travis.yml
- pkg/kademlia/merge_test.go
This makes it more obvious which tests are failing.
> Add top flag to tparse

- pkg/accounting/tally/tally.go
I think this is causing panics.
> make a map object before inserting into it

- internal/testplanet/planet.go
- internal/testplanet/planet_test.go
This is necessary for testing storage nodes being offline.
> testplanet: add capability to stop peers

- pkg/accounting/rollup/rollup_test.go
- satellite/satellitedb/accounting.go
- satellite/satellitedb/dbx/satellitedb.dbx
- satellite/satellitedb/dbx/satellitedb.dbx.go
https://storjlabs.atlassian.net/browse/V3-1085
1. LEFT JOIN overlaycache on nodes.id = overlaycache.node_id to select wallet address
2. Sum by node id: 
"byte-hours:AtRest",
"bytes:BWRepair-GET",
"bytes:BWRepair-PUT",
"bytes:BWAudit",
"bytes:BWGet",
"bytes:BWPut"
3. Remove the date field (keep nodecreationdate though)
> Convert Payments to use SQL, for SUM() and Wallet

- pkg/piecestore/psserver/server_test.go
It's still flaky, skip again to avoid taking dev time.
> Disable psserver.TestRetrieve

- pkg/overlay/cache_test.go
https://storjlabs.atlassian.net/browse/V3-1168
> Add test for randomized node selection

- internal/mail/gmail/gmailauth.go
-Add gmail auth implementation and helper methods for SMTP
> Gmail auth implementation for SMTP

- internal/dbutil/dbschema/schema.go
- internal/dbutil/pgutil/postgres.go
- internal/dbutil/pgutil/query.go
- internal/dbutil/pgutil/query_test.go
- internal/dbutil/pgutil/schema.go
- internal/testplanet/run.go
- satellite/satellitedb/database.go
- satellite/satellitedb/satellitedbtest/run.go
1. set up dbschema declaration that can be used to fetch and compare
2. it has similar structure as dbx, so we can cross-compare
3. postgres table structure loading
4. separates pg schema manipulation to make it usable in other packages
> create dbutil package for migration testing

- cmd/certificates/claims.go
- pkg/certificates/certificates.go
> add `certificates claim delete` & refactor

- web/satellite/tests/unit/store/projectMembers.spec.ts
- web/satellite/tests/unit/store/users.spec.ts
* Users store module unit tests
* ProjectMembers store module unit tests
> Satellite web unit tests fix

- cmd/statreceiver/graphite.go
New PR for https://github.com/storj/storj/pull/1041, to workaround cla-bot issues.
> reorder graphite metric string for easier parsing

- pkg/accounting/tally/stats.go
- pkg/accounting/tally/tally.go
- pkg/datarepair/checker/checker.go
https://storjlabs.atlassian.net/browse/V3-1238
https://storjlabs.atlassian.net/browse/V3-1239
> Total file count through Monkit

- pkg/piecestore/psserver/readerwriter.go
- pkg/piecestore/psserver/retrieve.go
- pkg/piecestore/psserver/server.go
- pkg/piecestore/psserver/store.go
Adds an interface to hide which implementation it's using for storing data.
> add piecestore.Storage interface

- .travis.yml
Cuts about ~30s from test time.
> Disable vet for tests

- pkg/piecestore/psserver/agreementsender/agreementsender.go
- pkg/piecestore/psserver/psdb/psdb.go
https://storjlabs.atlassian.net/browse/V3-1286
> Bwagreements not properly deleted

- cmd/uplink/cmd/cp.go
- pkg/piecestore/psserver/psdb/psdb.go
Add ability to specify ttl for uploads
https://storjlabs.atlassian.net/browse/V3-1189
> uplink ttl

- satellite/satellitedb/accounting.go
problem is sometimes the wallet address is NULL and database/sql refuses to scan that into a `string` field
> accounting: support null wallet addresses

- cmd/certificates/verify.go
- examples/grpc-debug/main.go
- pkg/auth/signedMessage.go
- pkg/bwagreement/server_test.go
- pkg/certificates/certificates.go
- pkg/certificates/certificates_test.go
- pkg/identity/certificate_authority.go
- pkg/identity/identity.go
- pkg/kademlia/dialer.go
- pkg/kademlia/dialer_test.go
- pkg/kademlia/kademlia.go
- pkg/kademlia/peer_discovery.go
- pkg/kademlia/routing_integration_helpers_test.go
- pkg/kademlia/routing_integration_test.go
- pkg/peertls/tlsopts/options.go
- pkg/peertls/tlsopts/options_test.go
- pkg/peertls/tlsopts/tls.go
- pkg/peertls/tlsopts/tls_helpers_test.go
- pkg/peertls/tlsopts/tls_test.go
- pkg/piecestore/psserver/server_test.go
- pkg/transport/transport.go
- pkg/transport/transport_test.go
https://storjlabs.atlassian.net/browse/V3-1320
> [V3-1320] fix empty node ID verification non-error

- Makefile
Should have not been spaces or tabs.
> Fixing tabs in makefile

- pkg/auth/signing/encode.go
- pkg/auth/signing/peers.go
- pkg/auth/signing/sign.go
- pkg/auth/signing/verify.go
Implements signing and signature verification of Order, OrderLimit and PieceHash
> Hammer: auth/signing package

- pkg/auth/signing/peers.go
- satellite/metainfo/metainfo.go
- satellite/peer.go
- uplink/piecestore/download.go
- uplink/piecestore/upload.go
* OrderLimit signing/verifying on metainfo
* fix for getting peer identity from stream
>  Signing improvements

- internal/dbutil/pgutil/db.go
- satellite/satellitedb/database.go
- satellite/satellitedb/dbx/satellitedb.dbx.go
This PR adds a proper Application Name to the PostgreSQL Connection String, if none is provided
> Add Application Name to PostgreSQL Connection String

- pkg/audit/verifier.go
This just rearranges the order of functions in verifier.go and make it easier to read imo. I just thought it wasn't very intuitive to read through when working on my last pr.
> rearranges code in verifier.go

- internal/fpath/editor.go
Fixing https://storjlabs.atlassian.net/browse/V3-1081
> check if the editor exists

- internal/testplanet/uplink_test.go
it was flaky 😱
#1557 failed because of this test, which was unrelated
> skips TestDownloadWithSomeNodesOffline

- uplink/config.go
```
root@kali:~/storj# uplink setup --dev --help
...
Flags:
--rs.max-threshold int                   the largest amount of pieces to encode to. n. (default 10)
--rs.min-threshold int                   the minimum pieces required to recover a segment. k. (default 4)
--rs.repair-threshold int                the minimum safe pieces before a repair is triggered. m. (default 6)
--rs.success-threshold int               the desired total pieces for a segment. o. (default 8)
--satellite-addr string                  the address to use for the satellite (default "localhost:10000")
```
> devDefaults for easy uplink setup connecting to storj-sim

- satellite/orders/service.go
> do not fail if one node is unavailable in CreateAuditOrderLimits

- pkg/audit/newverifier_test.go
- pkg/audit/timeout_test.go
> adds overlay cache deletes for offline nodes in audit tests

- satellite/orders/service.go
> Ensure serial number is not saved if error during order limit creation

- pkg/storj/pieceid.go
> Fix incorrect usage of NodeID and ErrNodeID in PieceID impl

- bootstrap/bootstrapweb/bootstrapserver/utils.go
- cmd/certificates/auth.go
- cmd/uplink/cmd/cp.go
- internal/fpath/os.go
- internal/migrate/create.go
- internal/readcloser/multi.go
- lib/uplink/buckets.go
- pkg/certificates/certificates.go
- pkg/certificates/certificates_test.go
- pkg/eestream/decode.go
- pkg/identity/identity.go
- pkg/kademlia/routing.go
- pkg/miniogw/gateway.go
- pkg/overlay/config.go
- pkg/peertls/peertls.go
- pkg/piecestore/psserver/store.go
- pkg/pkcrypto/encoding.go
- pkg/server/config.go
- pkg/storj/node.go
- pkg/stream/upload.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
- satellite/console/consoleweb/utils.go
- satellite/console/validation.go
- satellite/satellitedb/certdb.go
- satellite/satellitedb/irreparabledb.go
- satellite/satellitedb/overlaycache.go
- satellite/satellitedb/projectmembers.go
- satellite/satellitedb/projects.go
Most of the code has been migrated to `errs` package already, so let's do the final step as a single commit.
> Remove utils.CombineErrors and utils.ErrorGroup

- pkg/overlay/selection_test.go
- satellite/satellitedb/projectmembers.go
When we hit an scanning error then this is most likely an error in code and there's no need to keep scanning the rows.
> fix error handling in GetByProjectID

- pkg/overlay/statdb_test.go
The PR is to root cause, why overlay cache DB is not getting updated, while nodesDB(aka statDB) is. 
RootCause:
The CreateEntryIfNotExists() is used to create an entry if it doesn't exist on both nodesDB (aka statDB) 
and overlayCacheDB. nodesDB uses transactions to create an entry if it doesn't exist, but overlay cache uses two separate queries to do the very similar operation. To make sure it is transaction, I wrote a test case to test CreateEntryIfNotExists() emulation accessing the DBs parallelly and found out that without transactions modification, the function is failing very often, which proves that transactions are more robust than accessing thru individual queries. 
played with concurrency values:
1 . with concurrency set to 1000 -> without transaction it failed 40% of the time …
> OverlayCache DB missing updates

- satellite/satellitedb/overlaycache.go
This changes semantics slightly!
With this change, `CreateEntryIfNotExists()` will do a cache `Update` with every node passed in, whether it exists or not. `Update()` already does a race-free upsert operation, so that change removes the problematic race in `CreateEntryIfNotExists()`. As far as I can tell, this semantic change doesn't break any expectations of callers, and shouldn't affect performance in a significant way, as we already have an awful lot of round-trips to the db either way. But if I've misunderstood the intention of the method, someone ought to catch it during review.
Not adding tests because this is a behavior change for code already covered by tests.
> non-racy CreateEntryIfNotExists()

- storagenode/inspector/inspector.go
> Fix Dashboard Calculation Issues

- .clabot
> Add Fadila to CLA list

- satellite/satellitedb/dbx/satellitedb.dbx
- satellite/satellitedb/dbx/satellitedb.dbx.go
- satellite/satellitedb/overlaycache.go
> Set last_contact_success when a node is initially added to overlay cache

- pkg/audit/verifier.go
> adds defer close for node conn in audit verifier

- pkg/audit/timeout_test.go
it's randomly panicking:
```
PANIC: storj.io/storj/pkg/audit: TestGetShareTimeout/Postgres
--------------------------------------------------------------
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1080afa]
goroutine 19863 [running]:
gopkg.in/spacemonkeygo/monkit%2ev2.newSpan.func1(0xc000293ca0)
/home/travis/gopath/src/gopkg.in/spacemonkeygo/monkit.v2/ctx17.go:150 +0x6f4
panic(0x13119c0, 0x2021550)
/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/runtime/panic.go:513 +0x1b9 …
```
> skips flaky TestGetShareTimeout

- pkg/audit/newverifier_test.go
> skips flaky verifier happy path test

- internal/dbutil/pgutil/db.go
- internal/dbutil/sqliteutil/db.go
- satellite/orders/endpoint.go
- satellite/satellitedb/orders.go
- satellite/satellitedb/orders_test.go
This change fixes `UseSerialNumber` and case when given serial number doesn't exists in DB.
> Fix UseSerialNumber panic

- satellite/satellitedb/overlaycache.go
> Add Version Information for NodeStats Updates

- pkg/process/debug.go
This PR adds logging that records the debug endpoint listen address and port. Previously we were only logging if opening the listen address failed.
Finding this information is problematic and it's easier to parse a log file than it is to look at `netstat` and then hit random ports until you find the one with the `/pprof` endpoint. This also gives us a history in our log files about the ports in case of any breaches.
```
grep "debug server" service.log
versioncontrol/0            02:44:41.925 | DEBUG	debug server listening on 127.0.0.1:64943
bootstrap/0                 02:44:41.945 | DEBUG	debug server listening on 127.0.0.1:64946
satellite/0                 02:44:42.122 | DEBUG	debug server listening on 127.0.0.1:64961
storagenode/0               02:44:42.301 | DEBUG	debug server …
```
> Add a log message that records the debug listening address and port.

- satellite/metainfo/metainfo.go
Fixes https://storjlabs.atlassian.net/browse/V3-1486
> Fix "Number of valid pieces is lower then success threshold"

- .clabot
> Adding Ivan to the CLA bot

- cmd/storagenode/dashboard.go
A few users don't understand what last contact "NEVER" means. Lets change that into "OFFLINE" and see how that works.
> dashboard change last contact never into offline

- satellite/satellitedb/dbx/gen.go
- when we cast dbx errors to regular errors we didn't propagate the constraint violation message (i.e. which constraint was violated)
- this logs what the dbx constraint violation error was
> logs dbx constraint violation error

- satellite/console/apikeys.go
- satellite/console/auth.go
- satellite/console/service.go
- satellite/console/validation.go
- web/satellite/src/components/apiKeys/footerArea/DeleteApiKeysArea.vue
- web/satellite/src/components/project/DeleteProjectPopup.vue
> V3-1399 Error messages

- .dockerignore
- cmd/storagenode/alpha/amd64.Dockerfile
- scripts/release.sh
What: 
This is a collection of deploy and build script changes that made it to release-alpha8 but are not on master yet.
Why: They should be on master!
> Forward-port release-alpha8 build script issues

- pkg/datarepair/checker/checker_test.go
turns out the checker test is the one that takes forever
> skip more data repair tests :(

- .travis.yml
What: use travis that prints a dot every 5s.
Why: currently travis is stalling because tparse is not printing anything for a long time
> add custom tparse that doesn't stall

- pkg/peertls/tlsopts/tls.go
> remove fmt print statements

- pkg/piecestore/psserver/psdb/psdb.go
Why:
- removing files on storage nodes was extremely slow, taking up to 3 seconds per file to delete
What: 
- removes os.Stat check for each file, collects errors and logs
> optimizes deleting obsolete paths

- cmd/satellite/Dockerfile
I broke sending email from Mars in a previous PR. This should fix it again.
> Allow the satellite to connect to other mail servers

- .github/pull_request_template.md
> Remove GIF from Template that does not work correctly

- satellite/satellitedb/migrate.go
- satellite/satellitedb/testdata/postgres.v15.sql
What: 
There a possible scenarios where a node (bootstrap, satellite) is added to the overlaycache and does not have it's nodeType set correctly.
Why:
Its adding those nodes to upload and download requests...
> Set Default Node Type to invalid, to avoid cache issues

- .travis.yml
I created a fork of tparse package to avoid stalling travis, now the changes have been merged into upstream, so there's no need to keep using a fork.
> tparse: switch back to tracking main branch

- Makefile
There was some logic wrong in the last PR. This PR has no known problems.
> Fix :latest tag, again

- Makefile
Missed a part in a previous attempt
> Fixing :latest tag, part iii

- Makefile
- cmd/satellite/Dockerfile
This brings the satellite image more in line with the storagenode image. It also makes it much smaller!
> Clean up satellite image

- pkg/storage/ec/client.go
What: Moving piece putting failures to Debug instead of Error
Why: This is expected behavior and it is a poor experience for the user to see errors when this happens
> Moving failure for putting pieces to Debug as this is expected behavior

- satellite/console/consoleweb/consoleql/mail.go
- web/satellite/src/views/login/Login.vue
- web/satellite/static/emails/Forgot.html
> Implemented send email for support from static email.

- pkg/audit/timeout_test.go
What: 
Enable TestGetShareTimeout
Why:
It was flaky before, but not anymore
> Enable TestGetShareTimeout

- Jenkinsfile.public
What: tee raw output to `.json` and pipe stdin and stderr to xunit script
Why: if something is printed to stderr, it's not captured in xunit output
> save raw output and output both stderr/stdin

- pkg/overlay/cache_test.go
Each run of the selection code takes 100s, run only once instead.
> Run TestRandomizedSelection once per DB

- Dockerfile.jenkins
- Jenkinsfile.public
Changing max_connections requires restart, so moving that into conf file instead.
> set the connection limit in config

- lib/uplink/project.go
- lib/uplink/uplink.go
lib/uplink ends up modifying the config struct, however the caller may not expect that. Make an internal copy of the config struct.
> avoid race in lib/uplink

- pkg/kademlia/kademlia_planet_test.go
Why:
- The test uses `badProxy` which had a `dropInterval` where it dropped connections within a certain interval of time. I suspect that that interval of time was too long and was causing the flaky "panic: planet took too long to shutdown" messages.
What: 
- Replaces `dropInterval` with `dropCount` where the badProxy now drops the first `dropCount` number of connections it receives. Hopefully this will prevent the panics.
If this doesn't work them maybe try #1870 for now.
> makes TestBootstrapBackoffReconnect not flaky

- Jenkinsfile.public
- satellite/satellitedb/dbx/satellitedb.dbx.go
- scripts/check-dbx-version.sh
- scripts/check-imports.go
What: Use -race for check-imports, this means it will use the cached build files.
Why:
> jenkins: use -race for check-imports and fix dbx check

- Jenkinsfile.public
What: Adding a Jenkins Timeout
Why: Prevent exceeding long builds
> Add Build Timeout to Jenkinsfile

- Jenkinsfile
- Makefile
I missed a bit in https://github.com/storj/storj/pull/1875
> Fix Jenkins master builds

- .clabot
What: Add Yingrong to CLA List
Why: She is missing :)
> Add Yingrong to CLA

- .clabot
What: 
Adding Jeff Wendling to the CLA list.
Why:
So that he can start contributing code to V3!
> Adding Jeff Wendling to the CLA list.

- .clabot
What: Add barlock and sndrr to the CLA List.
Why: Both have PRs open ( #1891 and #1882 )
> Add barlock and sndrr to CLA List

- uplink/config.go
> Updates release MaxThreshold default to 130

- pkg/cfgstruct/utils.go
What:
Require an encryption key to be set when the user runs the gateway setup command
https://storjlabs.atlassian.net/browse/V3-1718
Why:
An encryption key is required to be set
> Fix to issue an error for empty enc key

- Jenkinsfile.public
- scripts/check-peer-constraints.go
Check whether any of the libraries import any of the peers. It's easy to introduce such a dependency right now.
Currently doesn't fail the linter since we still have violations in our code.
> jenkins: peer constraints

- .clabot
What: Add BlackDuck888 to CLA List
Why: He signed the CLA.
> Add BlackDuck888

- satellite/console/consoleweb/server.go
> Removed redundant logs from satellite.

- satellite/satellitedb/overlaycache.go
What: Fix the node selection query.
Why: The node selection query ends with an `OR true`. This little mistake will keep selecting satellite, bootstrap and disqualified storage nodes as long as they are running the minimum version.
```
SELECT id,
type, address, free_bandwidth, free_disk, audit_success_ratio,
uptime_ratio, total_audit_count, audit_success_count, total_uptime_count,
uptime_success_count
FROM nodes
WHERE type = $1 AND free_bandwidth >= $2 AND free_disk >= $3
AND total_audit_count >= $4
AND audit_success_ratio >= $5
AND total_uptime_count >= $6
AND uptime_ratio >= $7
AND last_contact_success > $8
AND last_contact_success > last_contact_failure
AND major > $9 OR (major = $10 AND (minor > $11 OR (minor = $12 AND patch >= $13)))
AND release AND id NOT IN ($14, $15, $16, $17, $18, …
```
> fix node selection

- web/satellite/src/store/modules/appState.ts
> Back to login pop-up issue

- cmd/uplink/cmd/share.go
- pkg/macaroon/caveat.go
What: Change caveat nonce from timestamp to random
Why: So that shares don't leak their creation time
> make caveat nonces random

- pkg/audit/newverifier_test.go
Why: sometimes verified nodes would be offline, sometimes not, so the test was flaky. working on figuring out a better way to check.
> removes 0 offline nodes assertion from verifier test

- satellite/console/consoleweb/consoleql/mutation.go
- satellite/console/consoleweb/consoleql/mutation_test.go
- satellite/console/consoleweb/consoleql/query.go
- satellite/console/consoleweb/consoleql/query_test.go
- satellite/mailservice/service.go
- satellite/peer.go
What: Unattended go routines may end up logging after all the contexts and services have been shut down.
Why: There are races being reported from console.
> satellite/mailservice: wait for goroutines to finish

- satellite/console/consoleweb/consoleql/mutation_test.go
- satellite/console/consoleweb/consoleql/query_test.go
Use require.NoError for consistency, this removes 120 repetitive lines.
> satellite/console: use require.NoError in tests

- storagenode/piecestore/endpoint.go
What: Add action into upload and download failure log messages.
Why: Storage node should be able to search for failed GET_AUDIT and find out whats wrong.
> improve logging

- storage/postgreskv/client.go
Currently we are using batch-size 10000, by benchmarking an unrelated thing I noticed that by using 1000 there was a significant perf win.
```
go test -v -benchtime 10x -bench BenchmarkSuiteLong -run XXX ./storage/postgreskv --test-bench-long paths.data.gz --test-bench-long-noinit --test-bench-long-noclean
```
Before:
```
BenchmarkSuiteLong/DeepRecursive-32                   10        4819822700 ns/op          10.63 MB/s
BenchmarkSuiteLong/DeepRecursiveReverse-32            10        4632797470 ns/op           9.84 MB/s
BenchmarkSuiteLong/DeepNonRecursive-32                10        1722895830 ns/op           0.00 MB/s
BenchmarkSuiteLong/DeepNonRecursiveReverse-32                 10        1340622790 ns/op           0.00 MB/s
BenchmarkSuiteLong/ShallowRecursive-32 …
```
> storage/postgreskv: use batch size 1000

- docs/design/metainfo-rpc.md
Rough sketch for all of the methods.
> Rough sketch for Satellite RPC

- pkg/storage/segments/repairer_test.go
TestSegmentStoreRepair seems to be flaky, disable for now.
> disable flaky TestSegmentStoreRepair

- .clabot
What: Add 3bl3gamer
Why: He signed the CLA and has a PR up: #1995 
> Add 3bl3gamer

- pkg/datarepair/checker/checker.go
- pkg/datarepair/repairer/repairer.go
- pkg/overlay/cache.go
- pkg/storage/ec/client.go
- pkg/storage/segments/repairer.go
- pkg/storage/segments/repairer_test.go
What: A new release-alpha11 release tag v0.11.4
Why: This will fix a few issues with the repair service. Lets deploy it and find out what else we have to fix.
> v0.11.4 repair fixes

- pkg/storage/ec/client.go
What: Add a log message to find the successful repairs in the log.
Why: I have removed the long tail cutoff inclusive the log messages around it. Right now we only see failed repair tasks or silence.
> improve repair logging

- pkg/datarepair/repairer/repairer.go
What: 
better logging in repairer main loop
Why:
debugging production traffic
> better repairer logging 

- pkg/storage/ec/client.go
What: Increase success counter.
Why: I removed an important counter with one of my latest PRs. Without that counter the repair service will always fail.
> Bugfix: Repair increase success counter

- docs/design/mountable-drive.md
What: Mountable Drive (FUSE integration) design doc
Why: General overview and current status for Strategy team
> Mountable Drive design doc

- Makefile
There's a weird '-heads-' in version tags. I think this PR will clean that up.
> Clean up version in image tags

- pkg/accounting/projectusage_test.go
What: 
- skips TestProjectUsageBandwidth
Why:
- it keeps flaking
- if anyone has more info about why it's flaking or strategies/existing plans to fix it, please comment here!
> skips flaky TestProjectUsageBandwidth

- satellite/console/consoleweb/consoleql/mutation.go
What: Put the log inside of the if statement for checking the error
Why: So we don't log errors that didn't happen during storj-sim, for example.
> log errors only when an error happens

- pkg/audit/newverifier_test.go
- pkg/audit/reporter.go
- pkg/audit/timeout_test.go
- pkg/audit/verifier.go
Why: this whole PR is a nit but these clunky names were killin me
> rename audit.RecordAuditsInfo to audit.Report

- satellite/orders/endpoint.go
What: Satellite order receiver should print out the storage node ID that submits the order.
Why: We are getting many errors message on the satellite side. I would like to find out if we have a general problem on all storage nodes or if only a few storage node IDs are involved. Maybe these few storage nodes have a problem with info DB? The additional logging should allow us to track that.
> Satellite order receiver named log

- .clabot
> Add 	ethanadams to CLA Bot

- cmd/uplink/cmd/common_test.go
What: Fix a faulty test in `cmd/uplink`
Why: The test was not considering the proper length of a slice generated with
a random length.
> cmd/uplink: Fix a faulty test

- .clabot
What: Adding @ReneSmeekes to our CLA approved List
Why: He signed it and has a PR open ( #2056 )👍 
> Add ReneSmeekes

- pkg/accounting/projectusage_test.go
What: attempt to fix flaky TestProjectUsageBandwidth test
Why:
> Fix flaky TestProjectUsageBandwidth

- uplink/config_test.go
> size of raw key should be at least storj.KeySize

- internal/testplanet/planet.go
- satellite/console/consoleweb/server.go
- satellite/peer.go
- scripts/testdata/satellite-config.yaml.lock
What/Why: There was a minor issue with the authorization
> Fixes Auth Issue

- pkg/storage/segments/repairer.go
> monkit repair stats - address potential divide by 0

- internal/sync2/cycle.go
What: 
We experienced a crash on ARM due to using 64bit atomics.
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x183d0]
goroutine 62 [running]:
gopkg.in/spacemonkeygo/monkit%2ev2.newSpan.func1(0x2d529e8)
/go/pkg/mod/gopkg.in/spacemonkeygo/monkit.v2@v2.0.0-20180827161543-6ebf5a752f9b/ctx17.go:150 +0x2d0
panic(0x882cc0, 0xfc7988)
/usr/local/go/src/runtime/panic.go:522 +0x1a0
runtime/internal/atomic.goCas64(0x2d222e4, 0x0, 0x0, 0x1, 0x0, 0x0)
/usr/local/go/src/runtime/internal/atomic/atomic_arm.go:83 +0x1c
storj.io/storj/internal/sync2.(*Cycle).Run(0x2d222cc, 0xa50f10, 0x2ee63c0, 0x2f63e84, 0x0, 0x0) …
```
> Changing 64bit atomics to 32bit for alignment on ARM.

- cmd/s3-benchmark/main.go
- cmd/uplink/cmd/cp_test.go
- internal/s3client/common.go
- internal/s3client/uplink.go
- scripts/test-aws-benchmark.sh
- scripts/test-sim-benchmark.sh
What/Why: 
This PR does the following:
1. adds a test script that runs upload/download benchmark tests against AWS S3 so that we can compare the performance to storj.
2. adds benchmark tests for aws s3
3. updates the s3client NewUplink now creates a new config file each time it is run. this is so there isn't any conflict with the default location of the normal uplink config.
How to run aws s3 client s3-benchmarks:
```
// expects $AWS_ACCESS_KEY_ID and $AWS_SECRET_ACCESS_KEY environment vars
// from root of storj repo, run
$ ./scripts/test-aws-benchmark.sh
```
How to run uplink client s3-benchmarks with new config options:
```
// creates a new config at path <appDir>/Storj/S3-Client/Uplink/config.yaml
$ s3-benchmark --client=uplink --satellite="$SATELLITE_0_ADDR" --apikey="$apiKey"
// uses …
```
> aws s3 performance tests

- satellite/metainfo/metainfo.go
- satellite/peer.go
What: Remove unused param from metainfo endpoint constructor
Why: It's unused :)
> Remove unused parameter

- web/satellite/src/components/project/UsageReport.vue
What: fix dates source on usage report page
Why: to fix https://storjlabs.atlassian.net/browse/V3-1831
> Fix dates source on UsageReport page

- storagenode/piecestore/endpoint.go
What: 
updating help message on storage node for AllocatedBandwidth
Why:
because it is incorrect
> updating help message on storage node for AllocatedBandwidth

- pkg/auth/signing/encode.go
What: rewrites encode methods for readability
Why: defer method can be unclear
> rewrites encode methods for readability

- pkg/overlay/cache.go
- satellite/satellitedb/dbx/satellitedb.dbx
- satellite/satellitedb/dbx/satellitedb.dbx.go
- satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
- satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
- satellite/satellitedb/locked.go
- satellite/satellitedb/migrate.go
- satellite/satellitedb/overlaycache.go
- satellite/satellitedb/testdata/postgres.v25.sql
What:
- adds disqualified column to nodes table
- updates migrate script
- adds postgres.v25.sql testdata
Why:
- getting disqualification cooking, check out https://github.com/storj/storj/pull/2079 for more details
> add disqualified column to nodes table

- pkg/datarepair/checker/checker.go
What: 
Refactor checker service
https://storjlabs.atlassian.net/browse/V3-1871
Why:
Looks cleaner and consistent
> Checker service refactor (v3-1871)

- docs/design/marketing-offer-program.md
What: 
simplify database schema
add invitee_credit_in_cents column
add methods implementation for offer table
remove Delete and Update methods in offer interface
Why:
Due to changes in the user flow for the marketing offer admin gui, we need to make some changes for the offer table and service
> Change for free credit design doc

- internal/dbutil/defaults.go
- scripts/testdata/satellite-config.yaml.lock
What: Updating the comments to be correct.
Why: We missed them..
> Fix Config Comments in DButil Package

- scripts/check-satellite-config-lock.sh
What: Changing Text to reflect the correct process
Why: It is wrong
> Update Notification Text to new Config Update Process

- storage/blob.go
- storage/filestore/blob.go
- storage/filestore/dir.go
- storage/filestore/store.go
- storage/filestore/store_test.go
- storagenode/pieces/readwrite.go
What: add monkit.Task to a bunch of functions that are missing it
Why: this will significantly help our instrumentation, data collection, and tracing about what's going on in the network
> storage/filestore: add monkit task to missing places

- pkg/auth/signature.go
- pkg/auth/signature_test.go
- pkg/auth/signedMessage.go
- pkg/auth/signing/encode.go
- pkg/auth/signing/peers.go
- pkg/auth/signing/sign.go
- pkg/auth/signing/verify.go
- pkg/bwagreement/server_test.go
- pkg/bwagreement/testbwagreement/common.go
- pkg/macaroon/apikey.go
- pkg/macaroon/apikey_test.go
- pkg/storage/ec/client.go
- pkg/storage/ec/client_planet_test.go
- satellite/metainfo/metainfo.go
- satellite/orders/endpoint.go
- satellite/orders/service.go
- satellite/vouchers/service.go
- storagenode/orders/db_test.go
- storagenode/pieces/db_test.go
- storagenode/piecestore/endpoint.go
- storagenode/piecestore/endpoint_test.go
- storagenode/piecestore/verification.go
- storagenode/piecestore/verification_test.go
- uplink/piecestore/buffering.go
- uplink/piecestore/download.go
- uplink/piecestore/upload.go
- uplink/piecestore/verification.go
What: add monkit.Task to a bunch of functions that are missing it
Why: this will significantly help our instrumentation, data collection, and tracing about what's going on in the network
> pkg/auth: add monkit task to missing places

- satellite/orders/endpoint.go
this single method sometimes runs for an hour. why?
add telemetry to find out
> satellite/orders: monitor order settlement more

- storage/postgreskv/alternateclient.go
I did a sanity check/grep of all the mon.Tasks in the codebase and I messed this one up
> postgreskv: actually monitor the iterate call

- web/satellite/src/components/team/footerArea/DeleteUserArea.vue
> Fixed error notification on fail project member deletion.

- docs/design/value-attribution.md
What: 
updated the reporting section of the design doc so that it is accurate
Why:
the design doc was wrong; it needed to include bandwidth 
> update to the reporting section to calculate bandwidth

- pkg/overlay/statdb_test.go
- satellite/satellitedb/overlaycache.go
What: 
Reverts #2102 from the alpha13 release branch.
Why:
The DQ feature is not finished yet. As a consequence, the repair is broken.
> Revert "add disqualified check to node selection queries (#2102)"

- storagenode/piecestore/endpoint.go
What: Add a log message for upload and download start.
Why: We have a high audit failure rate. Maybe the audits are timing out?
> Log upload and download start

- cmd/uplink/cmd/setup_test.go
- internal/testcontext/context.go
- pkg/accounting/db_test.go
- pkg/audit/verifier_unit_test.go
- pkg/macaroon/macaroon_test.go
- pkg/storj/encryption_test.go
- storage/boltdb/client_test.go
- storagenode/collector/service_test.go
- uplink/encryption_key_test.go
Test names may contain symbols like `:`, `?`, `~`, which may fail on Windows.
Only keep alpha numeric and dash in the folder name.
> testcontext: sanitize folder name

- web/satellite/src/components/project/DatePicker.vue
What: 
export name doesn't match with the component name
Why:
> fix export name for DatePicker

- pkg/audit/service.go
- scripts/testdata/satellite-config.yaml.lock
What: Increase the audit timeout.
Why: Because it reduces the number of audit false negatives. See https://storjlabs.atlassian.net/browse/V3-1921?focusedCommentId=16433&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16433
> increase audit timeout

- web/satellite/src/plugins/analytics.ts
> add fake id for segment.io

- docs/design/disqualification.md
> docs/design: Fix typos in disqualification

- satellite/console/consoleweb/server.go
- web/satellite/index.html
- web/satellite/package.json
- web/satellite/vue.config.js
What: modify build scripts for satellite ui
Why: to clean from unnecessary files and build steps and to make ui build faster
> Modify build scripts for satellite ui

- satellite/console/service.go
- satellite/payments/localpayments/local.go
What: remove payments checks during project creation and member deletion
Why: because there is no way to create payment info for existing users right now
> Console: Remove payments checks during project creation and member deletion

- Makefile
This speeds up builds on a the private jenkins server. It's a dirty hack for now and might be weird on Windows systems.
> Speed up builds

- docs/design/value-attribution.md
- satellite/satellitedb/dbx/satellitedb.dbx
What: 
fixing a minor review comments 
Why:
I overlooked and accidentally hit squash and merge.
> code updates with comments

- Jenkinsfile.gerrit
- Jenkinsfile.public
What: Bind Main Repo Builds to 'main' labeled nodes and tie Gerrit Builds to to 'gerrit' labeled nodes
Why: Improve Builds for Devs
> Bind Jenkins Builds to specific nodes

- .clabot
What: 
Adding Andrew Harding to the CLA bot
Why:
Because he is going to be writing code!
- Test 1: no tests
- Test 2: no tests
> Adding Andrew Harding

- pkg/overlay/config.go
- scripts/testdata/satellite-config.yaml.lock
What:
Updates audit parameters:
- α0 = 1
- β0 = 0
- w = 1
- λ = 0.95
- DQ = 0.
Updates uptime parameters:
- α0 = 2
- β0 = 0
- w = 1
- λ = 0.99
- DQ = 0.6
Why:
- The previous config values were rough guesses. These new values were chosen by the Data Science team after running different simulations of how this would play out on the network. They offered this brief disclaimer:
>The parameters suggested in this document are based on simulated SNO behavior under a few basic assumptions.   We  plan  to  produce  a  more  rigorous  analysis  of  reputation  parameters  in  one  of  our upcoming sprints, after which it is possible/likely that the values suggested in this document will be updated.  The parameters suggested here are expected to be on the generous side, given that disqualification …
> pkg/overlay: update node selection config values for reputation

- uplink/piecestore/download.go
What: 
Includes Node ID and Piece ID in errors returned by uplink's piecestore.
Why:
Easier analysis of errors.
- Test 1:
- Test 2:
> Include Node ID and Piece ID in piecestore errors

- lib/uplinkc/testdata_test.go
What: 
Why:
- Test 1:
- Test 2:
> jenkins timeout workaround

- storagenode/piecestore/endpoint.go
What: delete piece from disk when storing to pieceinfo is aborted
Why:
- Test 1:
- Test 2:
> storagenode: delete piece when upload is cancelled

- pkg/audit/cursor_test.go
- pkg/audit/reverify_test.go
- pkg/audit/verifier_test.go
- pkg/audit/verifier_unit_test.go
What: 
Why:
- Test 1:
- Test 2:
> audit test compilation fixes

- docs/design/value-attribution.md
- satellite/attribution/db.go
- satellite/metainfo/metainfo.go
- satellite/peer.go
- satellite/satellitedb/attribution.go
What: 
Support value attribution endpoint to be able to read/write partner info into value attribution DB.
Why:
support the value attribution feature
https://storjlabs.atlassian.net/browse/V3-1998
> support value attribution endpoint

- satellite/satellitedb/overlaycache.go
This doesn't solve much of the performance difficulty but ought to be
lots more correct in terms of proper node selection semantics.
(this does not yet split unique IPs into a separate table, and does not yet truncate IPv4 addresses to their /24 subnets, as discussed with Stefan. It also does not avoid sequential table scans, and does not provide good strength of randomness.)
What: makes ip filtering work in what is arguably a more correct way.
Why: because we want ip filtering to work in a correct way
- (existing tests should still pass and cover behavior)
- should take maybe 65% of the time of the old implementation
> do ip filtering in a more correct way?

- storagenode/console/consoleserver/server.go
- storagenode/console/service.go
- storagenode/peer.go
- web/operator/dist/build.js
What: 
all static resources are only for test purpose
Why:
- Test 1:
- Test 2:
> SNO Dshboard initial api endpoint added

- internal/migrate/create_test.go
- pkg/encryption/encryption_test.go
- pkg/kademlia/dialer_test.go
- pkg/metainfo/kvmetainfo/buckets_test.go
- pkg/process/exec_conf_test.go
- pkg/storj/identity_version_test.go
- scripts/check-imports.go
- storagenode/orders/db_test.go
- storagenode/piecestore/serials_test.go
- storagenode/vouchers/vouchers_test.go
What: Check-import-order script was ignoring test packages. Fix the tool and test files.
Why:
- Test 1:
- Test 2:
> fix import ordering

- .clabot
What: Add him to the CLA List, he has a PR: #2329 
Why: He is missing
- Test 1: Hard to test.. :)
- Test 2:
Please describe the performance impact: *We are getting quicker!*
> Add Alexander Bender

- cmd/satellite/Dockerfile
What: 
Why:
- Test 1:
- Test 2:
> Dockerfile changes for marketing resources.

- Jenkinsfile.public
- internal/testplanet/uplink.go
- lib/uplink/bucket.go
- lib/uplink/project.go
- lib/uplink/uplink.go
- pkg/metainfo/kvmetainfo/buckets_test.go
- pkg/metainfo/kvmetainfo/metainfo.go
- pkg/metainfo/kvmetainfo/temputils.go
- pkg/miniogw/gateway_test.go
- pkg/storage/segments/store.go
- pkg/storage/segments/store_test.go
- satellite/metainfo/metainfo_test.go
- uplink/config.go
- uplink/metainfo/client.go
What: 
* Fixes quite a few of connection leaks. 
* 5 test packages seem to be additionally clean now.
* Removes metainfo.Client interface.
Why:
Please describe the tests: see results
- Before: https://build.ops.storj.io/blue/organizations/jenkins/storj/detail/PR-2327/1/tests
- After: https://build.ops.storj.io/blue/organizations/jenkins/storj/detail/PR-2327/2/tests
> Fix some metainfo.Client leaks

- cmd/gateway/main.go
- cmd/uplink/cmd/setup.go
- pkg/cfgstruct/utils.go
What: Renaming satellites from planets to regions.
Why: It needs to be done
- Test 1: -
- Test 2: -
Please describe the performance impact: -
> Rename Satellites in the Wizard

- lib/uplinkc/convert.go
- lib/uplinkc/testdata/apikey_test.c
- lib/uplinkc/testdata/bucket_test.c
- lib/uplinkc/testdata/helpers.h
- lib/uplinkc/testdata_test.go
- lib/uplinkc/uplink.go
- lib/uplinkc/uplink_definitions.h
What: 
Why:
- Test 1:
- Test 2:
> Bucket attribution C tests

- lib/uplink/project.go
What: this is already called automatically, we don't need to increase the publicly exposed function surface area. also adds monkit
Why:
- Test 1:
- Test 2:
> lib/uplink: unexport bucket attribution check

- pkg/overlay/cache_test.go
- satellite/console/projectmembers_test.go
- satellite/console/usagerollups_test.go
What: Use require.NoError instead of t.Fatal.
Why:
- Test 1:
- Test 2:
> satellite/console: nicer error handling in tests

- .clabot
What: Add @nerdatwork to our CLA approved list.
Why: He signed it and is working on small contribution!
- Test 1: not needed
- Test 2: "
> Add nerdatwork to CLA List

- pkg/datarepair/datarepair_test.go
What: "
Why:
- accidentally got rid of it in merge
- Test 1:
- Test 2:
> add testrand back to datarepair test

- README.md
What: remove the link to Jira in the readme
Why: Jira is private 
- Test 1:
- Test 2:
> removing Jira in readme

- pkg/overlay/config.go
- scripts/testdata/satellite-config.yaml.lock
What: Reduce vetting requirement from 500 audits to 100 audits.
Why: A new node will need about 3 month to get 500 audits.
- Test 1:
- Test 2:
> reduce vetting requirement

- pkg/storage/ec/client.go
What: Monitor optimal wait fractions
Why: We currently use 1.5x, but maybe that's way too big, and we get most of what we need much faster.
- Test 1:
- Test 2:
Please describe the performance impact: None.
> monitor optimal wait fraction

- internal/version/service.go
What: Format the Error correctly in the log statement.
Why: Its not formatted correctly.
> Properly format Log Message for Version Check Failure

- web/satellite/src/components/account/Profile.vue
- web/satellite/src/components/apiKeys/ApiKeysArea.vue
- web/satellite/src/components/buckets/BucketArea.vue
- web/satellite/src/components/project/ProjectDetails.vue
- web/satellite/src/components/project/UsageReport.vue
- web/satellite/src/components/team/TeamArea.vue
- web/satellite/src/store/modules/projects.ts
- web/satellite/src/views/Dashboard.vue
What: data upload added when we navigates to new page
Why:
- Test 1:
- Test 2:
> Satellite console frontend data reload

- pkg/datarepair/checker/checker.go
What: Fix a typo in a doc comment.
Why: it's obvious.
> pkg/datarepair/checker: Fix typo in doc comment

- pkg/identity/common.go
- pkg/server/common.go
What: Align 2 errs Class messages with the rest of them.
Why: Because the rest of them don't have the package path.
Please describe the tests: No need any test for these changes.
Please describe the performance impact: None.
> pkg: Align errs Class messages

- satellite/metainfo/metainfo.go
What: 🤦
Why: Clear piece hashes from the pointerdb before storing them in the database.
- Test 1:
- Test 2:
> satellite/metainfo: optimize pointerdb size

- satellite/satellitedb/buckets_test.go
What: 
Quick fix of a test case that missed out on a code review comment
Why:
- Test 1:
- Test 2:
> Quick fix of a test case

- storagenode/storagenodedb/pieceinfo.go
What: Monkit was leaking.
Why:
- Test 1:
- Test 2:
> Fix monkit leaking

- satellite/metainfo/validation.go
What: Improves the logic for validating the max segment size on the satellite to consider the encryption overhead.
Why: Validation may fail if segments closer to the max segment size are uploaded
- Test 1:
- Test 2:
> Consider encryption overhead when validating max segment size

- storagenode/storagenodedb/infodb.go
- storagenode/storagenodedb/orders.go
- storagenode/storagenodedb/pieceinfo.go
- storagenode/storagenodedb/testdata/sqlite.v12.sql
- storagenode/storagenodedb/testdata/sqlite.v13.sql
- storagenode/storagenodedb/usedserials.go
What: Drops the tables and recreates them with new names
Why: This way we can't ever improperly run this migration twice and drop data we don't want to drop.
- Test 1:
- Test 2:
> reduce risk of deleting tables by changing their names

- cmd/storagenode/dashboard.go
What: Disabling the dashboard link
Why: It is not working and listening on localhost only
> Disabling Dashboard Link

- storagenode/storagenodedb/infodb.go
- storagenode/storagenodedb/testdata/sqlite.v14.sql
What: Removing the data in <storage-dir>/tmp
Why: Users reported having a bigger amount in that folder
> Remove orphaned tmp data from Storagenodes

- pkg/storage/segments/repairer.go
What: Create a new variable rather than reusing the existing one
Why: because the name of the existing one is confusing when reading the logic and it requires more time that the logic doesn't have a bug.
Please describe the tests: No tests, these changes don't require any other test rather than the existing ones.
> pkg/storage/segments: Clarify logic in Repair method

- pkg/datarepair/repairer/repairer.go
- pkg/overlay/cache.go
- pkg/storage/ec/client.go
- pkg/storage/segments/repairer.go
- satellite/metainfo/config.go
- satellite/metainfo/service.go
- satellite/satellitedb/repairqueue.go
- storage/postgreskv/client.go
What:  Add more information to the reported errors to find out how/where the repair process fails
Why: Because we are having troubles with repair and we want to find which is the part which causes the most of them
Please describe the tests: There is not change in the logic rather than, in majority, improving the error messages or wrapping errors, hence the existing tests are enough.
Please describe the performance impact: probably a bit, however we prefer to have more contextualized errors rather than having the minor improvement in performance.
> [v3 2137] - Add more info to find out repair failures

- storage/redis/client.go
What: 
so that we don't get down into the wrong logic when the put is
successful, as pointed out by jeff
Why:
cause I missed seeing this during the review of #2602 
- Test 1:
- Test 2:
> make sure to return after put()

- cmd/linksharing/main.go
- cmd/storagenode/dashboard.go
- internal/testplanet/bootstrap.go
- pkg/audit/verifier_unit_test.go
- satellite/console/consoleweb/server.go
- satellite/satellitedb/repairqueue.go
What: Few places were not handling the errors properly.
Why:
- Test 1:
- Test 2:
> add missing error handling

- satellite/console/consoleweb/consoleql/mutation.go
- web/satellite/src/api/users.ts
What: 
Why:
- Test 1:
- Test 2:
> satellite/console: fix graphql mutation

- web/satellite/package.json
What: 
Added required to build/serve vue-template-compiler
Why:
- Test 1:
- Test 2:
> web/satellite Master fix

- satellite/audit/reporter.go
What: 
Add more info about the nodes when they fail audit
Why:
more error logging detailed info needed for debugging 
- Test 1:
- Test 2:
> Adds more detailed error logging information V3-2239

- satellite/audit/reporter.go
What:
updating code based on missed code review
Why:
more error logging detailed info needed for debugging
- Test 1:
- Test 2:
> added more logging info

- web/satellite/src/views/forgotPassword/forgotPassword.html
What: 
Changed label on forgot password from "resend configurations" to "Reset Password"
Why:
- Test 1:
- Test 2:
> satellite/console: fix send reset password label

- internal/sync2/cycle.go
What: Fix typo in a doc comment
Please describe the tests: Not needed. 
> internal/sync2: Fix typo in doc comment

- pkg/kademlia/kademlia.go
What: 
Adding more info the error logs in bootstrap
Why:
Need to know when, how and what caused the failure
- Test 1:
- Test 2:
> Adding more info the error logs in bootstrap

- .clabot
What: Adding Karl Mozurkewich to our CLA approved list
Why: he signed the CLA.
> Add Karl Mozurkewich

- .github/CODEOWNERS
Use a proxy team for pull request assignment to avoid notifying everybody about the changes.
- Test 1:
- Test 2:
> codeowners: use proxy team for assignment

- cmd/uplink/cmd/setup.go
What: Use tls cli args to populate libuplink config in uplink setup.
Why: The libuplink calls in uplink setup were passing a `nil` uplink config, as a result tls cli arguments weren't totally respected.
To test for this one can run `uplink setup` with an uplink binary and try to point it at a storj-sim instance. When running with a binary built prior to this:
```
$ uplink setup --tls.use-peer-ca-whitelist=false
Select your satellite:
[1] us-central-1.tardigrade.io
[2] europe-west-1.tardigrade.io
[3] asia-east-1.tardigrade.io
Please enter numeric choice or enter satellite address manually [1]: 2019-08-08T12:18:19.174+0200       DEBUG   process/debug.go:51      debug server listening on 127.0.0.1:38279
localhost:10000
Enter your API key: …
```
> Uplink setup: respect tls args in libuplink config

- go.sum
- internal/testplanet/storagenode.go
- storagenode/nodestats/cache.go
What: Remove random sleep for tests
Why:
- Test 1:
- Test 2:
> storagenode/nodestats: fix test duration

- cmd/uplink/README.md
What: Remove identity setup instructions
Why: It's no longer relevant.
- Test 1:
- Test 2:
> cmd/uplink: remove identity setup instructions

- storagenode/pieces/cache_test.go
What: TestCacheCreateMultipleSatellites is being flaky, skip for now.
Why:
- Test 1:
- Test 2:
> storagenode/pieces: skip flaky TestCacheCreateMultipleSatellites

- docs/design/design-doc-process
What: 
the design doc process for people to reference 
Why:
because we want to make this information available 
- Test 1:
- Test 2:
> design doc for design doc process

- uplink/storage/segments/store.go
What: Seed the segments store download permutation with the timestamp.
Why: So that we don't always download from the same nodes if no other calls to the global RNG are made.
- Test 1:
- Test 2:
> uplink/storage/segments: seed download permutation with timestamp

- Jenkinsfile.public
- scripts/test-sim-backwards.sh
What/Why:
We need the backwards compatibility test to run with postgres not sqlite since we only run migrations for postgres for the Satellite.
n/a
n/a
> jenkins: Backwards Compatibility use Postgres

- docs/design/audit-v2.md
What: Fix unordered list formatting.
Why: It was janky.
Please describe the performance impact: Easier to read.
> docs/audit-v2: formatting fix

- satellite/audit/containment_test.go
- satellite/audit/verifier.go
- satellite/orders/service.go
- satellite/satellitedb/attribution.go
- satellite/satellitedb/containment.go
- satellite/satellitedb/overlaycache.go
- storage/boltdb/client.go
- storage/postgreskv/client.go
- storage/redis/client.go
- storage/teststore/store.go
- storagenode/storagenodedb/orders.go
What: The first argument to Error.New should be a formatting string. Otherwise this can e misinterpreted and cause problems. This tries to fix the issues.
Why:
- Test 1:
- Test 2:
> all: fix Error.New formatting

- web/satellite/tests/unit/store/projects.spec.ts
What: 
Why:
- Test 1:
- Test 2:
> web/satellite: projects tests fixed

- web/satellite/src/components/apiKeys/ApiKeysArea.vue
- web/satellite/src/components/navigation/NavigationArea.vue
- web/satellite/src/components/navigation/navigationArea.html
- web/satellite/src/components/team/HeaderArea.vue
- web/satellite/src/components/team/ProjectMemberListItem.vue
- web/satellite/src/router/index.ts
- web/satellite/src/views/Dashboard.vue
What: 
plus button on navigation removed
delete confirmation message changed
styles and navigation fixed
added redirect from default route 
Why:
> web/satellite: navigation bugs fixed

- storagenode/retain/retain.go
What: address review comments
Why:
- Test 1: I'll figure out how to add tests later.
- Test 2:
> storagenode/retain: review comments

- storagenode/orders/service.go
What & Why:
Don't return an error when archiving errors which aren't found in the DB
because it causes Storage Node send orders cycle to stop.
This was applied in the commit e47b8ed13198734cfbea611e76969ce67e353995
but the last call to `orders.Archive` function was missed so the errors
weren't returned when not found orders in the first call but they were
returned in the second call.
This commit address the second call for making `handleBatches` function
never returns error on not found orders.
See https://storjlabs.atlassian.net/browse/V3-2400?focusedCommentId=18119&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-18119 for more information.
This PR is a fix on a missed correction that should have been applied in PR https://github.com/storj/storj/pull/2801 …
> storagenode/orders: Don't return error Archiving unsent

- satellite/audit/queue.go
- satellite/audit/reservoirchore.go
- satellite/audit/worker.go
- satellite/peer.go
What: 
Why:
- Test 1:
- Test 2:
> Audit queue adjustments

- Jenkinsfile.public
- scripts/test-sim-backwards.sh
Replace for backwards compatibility tests.
> jenkins: work around git.apache.org failures

- .clabot
What: Addint TopperDEL to the CLA list.
Why: He signed the CLA and has a PR ( #2946 ) open!
- Test 1: N/A
- Test 2: N/A
> Add TopperDEL to the CLA list

- web/satellite/tests/unit/store/usage.spec.ts
What: 
Fixed test case by converting dates to UTC instead of local time
Why:
Failing test on jenkins machine
- Test 1:
- Test 2:
> web/satellite: Usage tests fix

- storagenode/storagenodedb/bandwidthdb.go
- storagenode/storagenodedb/database.go
- storagenode/storagenodedb/migrations_test.go
- storagenode/storagenodedb/orders.go
- storagenode/storagenodedb/pieceexpiration.go
- storagenode/storagenodedb/pieceinfo.go
- storagenode/storagenodedb/piecespaceused.go
- storagenode/storagenodedb/reputation.go
- storagenode/storagenodedb/storageusage.go
- storagenode/storagenodedb/testdata/multidbsnapshot.go
- storagenode/storagenodedb/testdata/v0.go
- storagenode/storagenodedb/testdata/v1.go
- storagenode/storagenodedb/testdata/v10.go
- storagenode/storagenodedb/testdata/v11.go
- storagenode/storagenodedb/testdata/v12.go
- storagenode/storagenodedb/testdata/v15.go
- storagenode/storagenodedb/testdata/v17.go
- storagenode/storagenodedb/testdata/v18.go
- storagenode/storagenodedb/testdata/v19.go
- storagenode/storagenodedb/testdata/v2.go
- storagenode/storagenodedb/testdata/v20.go
- storagenode/storagenodedb/testdata/v21.go
- storagenode/storagenodedb/testdata/v3.go
- storagenode/storagenodedb/testdata/v4.go
- storagenode/storagenodedb/testdata/v6.go
- storagenode/storagenodedb/testdata/v7.go
- storagenode/storagenodedb/testdata/v8.go
- storagenode/storagenodedb/testdata/v9.go
- storagenode/storagenodedb/usedserials.go
- storagenode/storagenodedb/versions.go
What: Create migration test for step that splits into multiple dbs
Why: We need to test the migration into multiple dbs
- Test 1: This is an updated test, all is well.
> Add test for migration 21

- satellite/overlay/config.go
- scripts/testdata/satellite-config.yaml.lock
What: Updates NodeSelectionConfig.OnlineWindow to 4hr default
Why: To allow for repair to work with new contact system
Please describe the tests: NA
Please describe the performance impact: NA
> update NodeSelectionConfig.OnlineWindow to 4hr default

- satellite/contact/endpoint.go
What: close grpc connections after node pingback
> satellite/contact: close grpc client connections

- satellite/contact/endpoint.go
What/Why:
GRPC endpoints should return status codes, adding that here.
n/a
n/a
> return status codes for contact endpoint

- satellite/audit/reverify_test.go
What: 
In `TestReverifyDifferentShare`, upload each file to at least 3 of the 4 nodes in the test planet network
Why:
With the default uplink settings, there is a very unlikely scenario in `TestReverifyDifferentShare` where each of the two files will be uploaded to exactly two nodes, and these nodes will be mutually exclusive. This situation will cause the test to fail.
- Test 1:
- Test 2:
> satellite/audit: Fix flakiness in TestReverifyDifferentShare

- satellite/overlay/service.go
What: 
Don't use transport observers to get information about node addresses or uptime. Those will come from the contact service (see #2952).
This probably can't pass tests or be merged into master until #2952 is merged first.
Why:
Honestly, I'm not totally sure, except that V3-2305 said to do it.
- Existing tests exercise node information updates and node uptime updates. If they continue to work, I consider this change to be sufficiently tested.
Performance may be mildly impacted, as a result of updating node information every time a node checks in, rather than every time we dial out to a node. On the other hand, I'm not entirely sure how often we dial out to nodes now, so maybe this will actually improve performance.
> satellite/overlay: don't use transport observers

- .clabot
What: Adding our new employees ( @mbouzi , @kristaxox and @calebcase ) to the approved CLA list.
Why: They are part of the team!
> Adding our new employees

- pkg/certificate/peer.go
What: Actually run the certificate authorization HTTP endpoint.
Why: Because otherwise it's pointless.
- Test 1:
- Test 2:
> pkg/certificates: run certificate authorization endpoint

- .clabot
What: adding @AlexeyALeonov to CLA list
Why: He is a community lead.
> Add AlexeyALeonov to CLA list

- README.md
What: 
update to go v.1.13
Why:
The minimum required version of go is 1.13
- Test 1:
```
git clone https://github.com/storj/storj.git storj
cd storj && go install -v ./cmd/...
```
Should successfully build.
- Test 2:
> update to go 1.13

- storagenode/console/bandwidth.go
- storagenode/console/diskspace.go
- storagenode/console/service.go
What: use bytes for remaining info
Why: to let dashboard UI handle the conversion
- Test 1:
- Test 2:
> storagenode/console: use bytes for remaining info

- web/storagenode/src/app/components/BarInfo.vue
- web/storagenode/src/app/utils/chartUtils.ts
- web/storagenode/src/app/utils/converter.ts
What: added TB and PB conversions
Why: SNOboard enhancements
- Test 1:
- Test 2:
> web/storagenode: memory conversions extended

- .gitignore
- Makefile
- cmd/storj-sim/network.go
- internal/testplanet/storagenode.go
- storagenode/console/consoleassets/.gitignore
- storagenode/console/consoleserver/server.go
- storagenode/peer.go
What: Make the changes reported in review of #3164
Why: We want to merge #3164 as soon as possible.
Please describe the tests: the same as described in #3164
Please describe the performance impact: the same as described in #3164
> storagenode/console: Changes reported by reviewers

- installer/windows/AllocatedBandwidthConfig.wxs
- installer/windows/IdentityDir.wxs
- installer/windows/PublicAddressConfig.wxs
- installer/windows/WalletConfig.wxs
What: Hyperlinks to Storj documentation in wizard dialogs are updated.
Why: The documentation site has just been restructured and URL to some articles changed.
> installer/windows: Update links to documentation

- satellite/overlay/service.go
- satellite/overlay/service_test.go
- satellite/satellitedb/locked.go
- satellite/satellitedb/overlaycache.go
What: 
Remove `IsVetted` from the overlay
Why:
It isn't used anywhere
- Test 1:
- Test 2:
> satellite/overlay: remove overlay.IsVetted

- Jenkinsfile.drpc
- Makefile
- internal/testcontext/compile.go
- pkg/rpc/rpc_test.go
- scripts/test-sim.sh
What: 
Why:
- Test 1:
- Test 2:
> testing: GOFLAGS=-drpc

- docs/blueprints/storagenode-graceful-exit/reports.md
What: updating blueprint to have the correct terminology. 
Why: its held amount. 
- Test 1:
- Test 2:
> updating term to be accurate; Its held amount.

- satellite/gracefulexit/endpoint_test.go
What: 
Fix drpc/grpc interface and EOF check in endpoint tests
Why:
DRPC tests failed.
- Test 1:
- Test 2:
> satellite/gracefulexit: Fix drpc/grpc interface and EOF check in endpoint tests

- certificate/endpoint.go
What: Changes the error handling to return the precise error instead of a general error
Why: It has a better UI/UX, as the client/user knows exactly why it was refused.
> cmd/certificates: Change Error Handling to return more clear messages to the user/client

- satellite/payments/creditcards.go
- satellite/payments/stripecoinpayments/creditcards.go
What: Added functionality to add credit card as a payment method to payment account
Why:
- Test 1:
- Test 2:
> satellite/payments: add credit card to payment account

- .clabot
What: Adding @cpustejovsky to our CLA
Why: He signed it and has a PR #3314 up.
> Adding cpustejovsky to the CLA

- web/storagenode/src/app/components/SNOContentTitle.vue
- web/storagenode/src/storagenode/api/storagenode.ts
- web/storagenode/src/storagenode/dashboard.ts
What: node version comes from server as string. Earlier it was coming as object. That caused bug on front-end
Why: bug fixing
- Test 1:
- Test 2:
> web/storagenode: node version bug fixed

- satellite/console/consoleweb/consoleapi/auth.go
- satellite/console/consoleweb/consoleql/mutation.go
- satellite/console/consoleweb/server.go
- satellite/console/service.go
What: get, update auth  api endpoints added
Why:
- Test 1:
- Test 2:
> satellite/console: get, update auth  api endpoints added

- storagenode/piecestore/endpoint.go
What: A few changes to how MaxConcurrentRequests is respected:
- Default value should be `0`
- If drpc, if the value is `0` it is unlimited. If the value is set (i.e. > 0) respect the limit.
- If grpc:
- If the value is `0` (unset), enforce limit (as we had before).
- If the value is > 0, respect limit.
Why: We want drpc requests to be unlimited by default. But we want to allow SNOs to set a limit if they desire.
> storagenode/piecestore: Respect config.MaxConcurrentRequests for drpc

- web/satellite/tests/unit/common/VDatePicker.spec.ts
What: unit test fixed
Why: 
- Test 1:
- Test 2:
> web/satellite: datepicker unit test hot fix

- go.mod
- go.sum
What: Bump drpc version
Why: To get the fixes for context cancellation.
- Test 1:
- Test 2:
> drpc: version bump

- internal/testplanet/satellite.go
- satellite/peer.go
- satellite/repair/repairer/ec.go
- satellite/repair/repairer/repairer.go
- satellite/repair/repairer/segments.go
- satellite/repairer.go
- scripts/testdata/satellite-config.yaml.lock
What: 
- add timeout for repair download
Why:
- right now there's no timeout for download. A slow node could hold up the repair process
- Test 1:
- Test 2:
> satellite/repair: add timeout for repair download

- web/satellite/tests/unit/common/VDatePicker.spec.ts
What: temporary removed unit tests for date picker
Why:
- Test 1:
- Test 2:
> web/satellite: date picker unit tests temporary removed

- cmd/storagenode-updater/main.go
- cmd/storagenode-updater/main_test.go
- internal/testcontext/compile.go
- internal/version/checker/client.go
- internal/version/checker/client_test.go
- internal/version/version.go
- internal/version/version_test.go
- versioncontrol/peer.go
What: Part of #3338 extracted to simplify review and testing.
Why: Part of work for storagenode-updater autoupdating. https://storjlabs.atlassian.net/browse/V3-2882
- Test 1: automatic test added
> storagenode-updater: add autoupdating

- satellite/payments/stripecoinpayments/customers.go
- satellite/payments/stripecoinpayments/service.go
- satellite/satellitedb/customers.go
What: archview comments updated
Why: to create more detailed diagram 
- Test 1:
- Test 2:
> satellite/payments: archview comments updated

- .clabot
update to the CLA file adding Rafael Gomes
What: Adding Rafael Gomes to the CLA bot 
Why: because he just joined the team
- Test 1: N/A
- Test 2: N/A
> update to the CLA file adding Rafael Gomes

- storagenode/contact/service.go
What:  change dev default for contact chore interval to 30s
Why: 5s was too noisy in storj-sim
> storagenode/contact: change dev default for contact chore interval to 30s

- web/storagenode/src/app/components/BarInfo.vue
- web/storagenode/src/app/components/ChecksArea.vue
- web/storagenode/src/app/components/PayoutArea.vue
- web/storagenode/src/app/components/SNOContentFilling.vue
- web/storagenode/src/app/components/SNOContentTitle.vue
- web/storagenode/src/app/components/SNOFooter.vue
- web/storagenode/src/app/components/SNOHeader.vue
- web/storagenode/src/app/components/SatelliteSelection.vue
What: text selection limited
scrollup after click on bottom logo added
Why: enhancements
- Test 1:
- Test 2:
> web/storagenode: text selection on specific elements disabled

- web/satellite/src/components/project/ProjectDetails.vue
- web/satellite/src/components/project/UsageReport.vue
What: supporting of empty lines added
scrollbar fixed 
usage-report downloading fixed
Why: enhancements
- Test 1:
- Test 2:
> web/satellite: project description enhanced

- Makefile
we don't want the shell builtin because we're using `-e`
> release: use /usr/bin/env echo

- internal/dbutil/pgutil/schema.go
What: Retry `create schema` to fix constraint error. We could try to lock the table, however since the postgres tables are shared by all tests, it would end up very costly to test. The next best thing is to retry, since after it has been created the next call should succeed without problems.
See https://stackoverflow.com/a/29908840/192220.
Why:
- Test 1:
- Test 2:
> internal/dbutil/pgutil: retry create schema on a concurrent call

- web/satellite/src/api/auth.ts
What: web/satellite: token error status code fixed
Why:
- Test 1:
- Test 2:
> web/satellite: token error status code fixed

- web/satellite/vue.config.js
What: 
bug with not compressing to small css file fixed
Why:
to allow us to reach forgot passwork page
- Test 1:
- Test 2:
> web/satellite: gzip bug fixed

- satellite/console/consoleweb/consoleapi/auth.go
What: satellite/console: auth API error handling refactored
Why:
- Test 1:
- Test 2:
> satellite/console: auth API error handling refactored

- Jenkinsfile
What: Send the current stage to the slack channel too.
Why: To help prioritize errors when they're submitted to slack.
Please describe the tests: existing tests.
Please describe the performance impact: no impact.
> Add stage name to slack error message

- pkg/rpc/gen.go
What: fix tags on generated code
Why: cause we changed the tags
Please describe the tests: tests are broken for newly generated code without this
- Test 1:
- Test 2:
> pkg/rpc: generate drpc/grpc tags correctly

- Dockerfile.jenkins
- scripts/update-tools
- scripts/update-tools.sh
What: We need to keep tools updated. This is a start.
Why: Out of date tools are bad.
Please describe the tests: existing tests
Please describe the performance impact: Probably makes something faster.
> scripts: add script to update tools

- satellite/payments/stripecoinpayments/tokens.go
What: switch to using STORJ tokens
Why:
- Test 1:
- Test 2:
> satellite/payments: switch to using STORJ tokens

- satellite/repair/repairer/repairer.go
- scripts/testdata/satellite-config.yaml.lock
What: Decrease repair upload timeout from 10 minutes to 5 minutes
Why: The slowest successful upload was 4m54s. -> If it takes more than 5 minutes it will hit the 10 minutes timeout anyway. We can as well reduce the timeout. Less waiting for timeout = more time for the next repair.
```
[4006501384074266902] storj.io/storj/satellite/repair/repairer.(*ECRepairer).putPiece
parents: 5301582005553658410
current: 63, highwater: 888, success: 483620, errors: 4337, panics: 0
error Canceled: 753
error System Error: 261
error protocol: 2327
error piecestore: 996
success times:
0.00: 1.374202752s
0.10: 1.404455616s
0.25: 1.43986144s
0.50: 1.531947008s
0.75: 2.211706112s
0.90: 1m12.600773836s
0.95: 2m11.902450892s
1.00: 4m54.11311616s
avg: 21.60192309s
ravg: 24.041336832s
failure times:
0.00: …
```
> satellite/repair: reduce upload timeout

- storagenode/piecestore/endpoint_test.go
- uplink/piecestore/client.go
What: Fix invalid comment and typos
Why: They were wrong or had a typo.
> piecestore: Fix invalid comment and typos

- web/satellite/static/resetPassword/success.html
What: 
styles are now being applied 
Why:
bug fixing
- Test 1:
- Test 2:
> web/satellite: successful reset password page styling bug fixed

- satellite/satellitedb/apikeys.go
What: satellite/console: api-key case insensitive search added
Why:
- Test 1:
- Test 2:
> satellite/console: apiKeys case-insensitive search added

- satellite/console/consoleweb/consoleapi/payments.go
- satellite/console/service.go
- satellite/payments/mockpayments/mockpayments.go
- satellite/payments/stripecoinpayments/conversion.go
- satellite/payments/stripecoinpayments/tokens.go
- satellite/payments/tokens.go
What: token deposit accept cents
Why: it is more convenient to for user to work with USD amounts comparing to raw STORJ token values. 
- Test 1:
- Test 2:
> satellite/payments: token deposit accept cents

- private/testplanet/planet.go
- private/testplanet/reconfigure.go
- private/testplanet/referralmanager.go
- private/testplanet/satellite.go
- satellite/peer.go
- satellite/referrals/service.go
- scripts/testdata/satellite-config.yaml.lock
What: 
add a mock referral manager server into testplanet
Why:
we would like to test referral manager client logic on the satellite
- Test 1:
- Test 2:
> private/testplanet: add a mock referral manager server into testplanet

- web/storagenode/src/app/components/SNOContentFilling.vue
What: 
containers moved to appear under charts
redundant title removed
Why:
SNO Dashboard enhancements
- Test 1:
- Test 2:
> web/storagenode: info containers of remaining bandwidth/diskSpace replaced

- cmd/segment-reaper/observer.go
what: Use bitmask type in `observer`
Why: Because the `bitmask` type was created for making easy to understand the `observer` bit logic.
Please describe the tests: There was no test. The test is under https://github.com/storj/storj/pull/3658 and it will be adapted if this gets merged before.
> cmd/segment-reaper: Use bitmask type in observer

- satellite/satellitedb/projectaccounting.go
What: project usage query was optimized. Memory allocation in go was reduced and some db queries works faster and returns less data
Why: In some cases this query works slow. Our QA andrew should wait 4 sec until he gets project usage on his local machine. Also, this query is used often
So what have been changed:
1. 
```All_BucketStorageTally_By_ProjectId_And_BucketName_And_IntervalStart_GreaterOrEqual_And_IntervalStart_LessOrEqual_OrderBy_Desc_IntervalStart``` - 
this dbx query fetch all table columns, but we need only 4 here
```
SELECT
bucket_storage_tallies.interval_start, 
bucket_storage_tallies.inline,
bucket_storage_tallies.remote,
bucket_storage_tallies.object_count
```
2. there were a  roullupsQuery 
```
SELECT
SUM(settled), SUM(inline), action
FROM
bucket_bandwidth_rollups
WHERE …
```
> satellitedb/accounting: project usage optimization

- satellite/satellitedb/projectaccounting.go
What: returned missing line
Why:
- Test 1:
- Test 2:
> satellite/accounting: missing line returned

- satellite/satellitedb/projectaccounting.go
What: Fixed error with closing nil db row, added COALESCE operator to sum null values
Why: because i'm very smart (no)
- Test 1:
- Test 2:
> satellitedb/accounting: fixed query

- satellite/satellitedb/satellitedbtest/cockroachnamespace_test.go
What: `TestNewCockroach` was failing the check which asserts that the db was correctly created. This is because inside the `NewCockroach` method, the db name is formatted to remove all non-alphanumeric characters. However, in the query which checks for the existence of the database, the name was not formatted in the same way resulting in a failure
- Test 1:
- Test 2:
> satellitedb/satellitedbtest: fix TestNewCockroach

- satellite/rewards/rewards_test.go
- satellite/satellitedb/offers.go
What: use crdb wrapper to make transaction in `offersDB.Create` cockroach compatible
Why: cockroach compatibility
- Test 1:
- Test 2:
> satellite/satellitedb: cockroachDB compatible transaction in offersDB.Create

- satellite/console/consoleweb/consoleql/consoleerrors.go
- satellite/console/service.go
- web/satellite/src/api/auth.ts
What: Error messages while register without token and creation project over limit fixed
Why:
- Test 1:
- Test 2:
> error messages fixed

- .clabot
What: 
adding Igor Gaidaenko
Why:
He is our new team member
- Test 1:
- Test 2:
> adding Igor Gaidaenko our new team member!

- pkg/encryption/path_test.go
- uplink/metainfo/kvmetainfo/buckets_test.go
- uplink/metainfo/kvmetainfo/objects_test.go
What: 
Why:
- Test 1:
- Test 2:
> {pkg/encryption,uplink/metainfo}: test additions

- README.md
What: Update the URL in the readme to point to the correct Instance
Why: The old one is deprecated.
- Test 1: X
- Test 2: X
> Update Coverage URL

- Jenkinsfile
What: Track the Stage in a global variable to ensure, we have it for alerting
Why: Alerting messages are currently reporting step null, as the variable is not set.
Please describe the performance impact: Quicker turnaround in case of a failure
> Jenkinsfile: Catch the Stage properly for Alerts

- Jenkinsfile
- Makefile
> jenkins: use go 1.13.8

- cmd/satellite/stripe.go
- satellite/accounting/rollup/rollup.go
- satellite/payments/paymentsconfig/config.go
- scripts/testdata/satellite-config.yaml.lock
What: 
- Project Default: 5GB
- Coupon Value: 30ct
- Fix migration script
Why:
- Migration was failing
> satellite/payments: Set proper defaults for the release

- go.mod
- go.sum
- satellite/metainfo/metainfo_test.go
What: bumps uplink to 1.0.0
Why: we just released it!
> bump uplink to 1.0.0

- .clabot
What: Adding @sixcorners to the CLA list
Why: He agreed on it and has a PR open (#3820)
> cla: Adding sixcorners to the CLA approved list

- storagenode/storagenodedb/database.go
What: improves the error message to make troubleshooting easier
Why: its hard to know for which schema/db the check failed.
> storagenode/storagenodedb: Improve preflight schema error message

- satellite/accounting/rollup/rollup.go
- satellite/payments/paymentsconfig/config.go
- scripts/testdata/satellite-config.yaml.lock
- web/satellite/src/components/account/billing/paymentMethods/AddStorjForm.vue
- web/satellite/src/components/account/billing/paymentMethods/PaymentsBonus.vue
- web/satellite/src/components/account/billing/paymentMethods/TokenDepositSelection.vue
- web/satellite/src/components/onboardingTour/steps/AddPaymentStep.vue
- web/satellite/src/components/onboardingTour/steps/paymentStates/AddStorjState.vue
- web/satellite/src/components/onboardingTour/steps/paymentStates/tokenSubSteps/PayingStep.vue
- web/satellite/tests/unit/account/billing/paymentMethods/AddStorjForm.spec.ts
- web/satellite/tests/unit/account/billing/paymentMethods/__snapshots__/AddStorjForm.spec.ts.snap
- web/satellite/tests/unit/account/billing/paymentMethods/__snapshots__/PaymentMethods.spec.ts.snap
- web/satellite/tests/unit/onboardingTour/steps/__snapshots__/AddPaymentStep.spec.ts.snap
- web/satellite/tests/unit/onboardingTour/steps/paymentStates/__snapshots__/AddStorjState.spec.ts.snap
- web/satellite/tests/unit/onboardingTour/steps/paymentStates/tokenSubSteps/PayingStep.spec.ts
What: Changes the default storage limit to 50GB and the minimum Storj Token Payment to $10
Why: It is appropriate.
Please describe the performance impact: possibly more load on the satellite as more users use the network?
> satellite: Change Default Project Limits and minimum STORJ Payment

- cmd/storj-admin/main.go
What: Creates the construct for the new admin UI client tool.
Why: It makes support ticket handling easier
- Test 1: none with this raw construct
> cmd/storj-admin: initial commit of new tool

- cmd/satellite/Dockerfile
- cmd/satellite/entrypoint
What: Removes old ENV vars from the entrypoint
Why: They dont exist any longer
> cmd/satellite: clean up entrypoint

- scripts/tests/rollingupgrade/test-sim-rolling-upgrade.sh
> scripts/tests/rollingupgrade: continue for v1.6.4

- Jenkinsfile
- docker-compose.yaml
- scripts/postgres-dev.sh
- scripts/tests/rollingupgrade/test-sim-rolling-upgrade-dev.sh
- scripts/tests/testversions/test-sim-versions-dev.sh
What: 
Change testing to use PG 12.3
Why:
Production was upgraded
- Test 1:
- Test 2:
> satellite/testing: Change testing to use PG 12.3

- .clabot
What: Adding @alexottoboni to the approved list.
Why: Has signed the CLA and has PR open #3914
> cla: add alexottoboni

- .clabot
What: changes the username of JT.
Why: He changed it and used it in #3916
> clabot: change JTs username

- satellite/rewards/partners.go
What: Adding some new partners for value attribution
Why: Because we need to be able to figure out who refers clients to us
- Test 1:
- Test 2:
> Adding Kesque, MSP360, Innovoedge, Taloflow, Restic partners

- storagenode/pieces/trashchore.go
What: Fixing typo
Why: It did not sound correct
- Test 1:
- Test 2:
> Tidying trash log

- .clabot
What: Adding dominickmarino to the CLA bot list
Why: dominickmarino is joining the Storj Labs team
- Test 1:
- Test 2:
> Adding dominickmarino to the CLA bot list

- web/satellite/src/views/DashboardArea.vue
What: Link to the limit increase form.
Why: The old link is pointing to general support tickets. We have a dedicated form for project limit increase and should link that one instead.
- Test 1:
- Test 2:
> satellite/projectlimit: Update limit increase link

- .clabot
Adding hextorj2f to clabot.
...
> .clabot: add hectorj2f

- docs/blueprints/storage-node-downtime-tracking-with-audits.md
What: Fixes a couple typos in the downtime tracking design doc.
> Fixed typos in downtime tracking with audits doc

- cmd/satellite/admin.go
- cmd/satellite/api.go
- cmd/satellite/billing.go
- cmd/satellite/compensation.go
- cmd/satellite/gc.go
- cmd/satellite/gracefulexit.go
- cmd/satellite/main.go
- cmd/satellite/repairer.go
- cmd/satellite/reports/attribution.go
- cmd/satellite/usage.go
- cmd/segment-reaper/delete.go
- cmd/segment-reaper/detect.go
- multinode/multinodedb/database.go
- private/dbutil/pgutil/db.go
- satellite/metainfo/config.go
- satellite/satellitedb/database.go
- satellite/satellitedb/migrate_test.go
- satellite/satellitedb/satellitedbtest/run.go
- storage/cockroachkv/client.go
- storage/postgreskv/client.go
- storage/postgreskv/client_test.go
What: 
Cherry pick DB application name change
Why:
Makes troubleshooting easier
- Test 1:
- Test 2:
> Allow for DB application names per process. (#3983)

- .clabot
What: Adding myself to clabot.
Why: Just joined Storj!
N/A
N/A
> .clabot: adding nergdron to the clabot list

- .clabot
What: Adding @Doom4535 to approved cla list.
Why: He signed it and has a PR open #3987
> .clabot: adding Doom4535 to approved list

- Makefile
- cmd/satellite/Dockerfile
- satellite/console/wasm/README.md
- scripts/build-wasm.sh
What: Adds the wasm build steps to build pipeline.
Why: Else the Satellite UI isnt fully functional.
> build: add wasm bits to Dockerfile and bump to go v1.15.6

- Jenkinsfile
What: Bumps the go version to the latest version.
Why: Upgrades are nice!
> Jenkinsfile: update to go v1.15.6

- satellite/rewards/partners.go
What: adding fastly
Why: to track attribution 
- Test 1:
- Test 2:
> Adding Fastly

- Makefile
- cmd/satellite/Dockerfile
- web/satellite/Dockerfile
What: Update to node v14.15.3
Why: Node v10.15.1 is outdated and does not support brotli out of the box.
> build: update node to v14.15.3

- Makefile
- scripts/deploy-storagenode.sh
What: Cherry pick a commit for storage nodes.
Why: Storage node rollout hasn't started yet and we belive this commit is needed to avoid issues with the rollout.
- Test 1:
- Test 2:
> v1.19.4 point release

- satellite/rewards/partners.go
What: 
Adding hypernet to our value attribution list
Why:
So that we can share revenue with them
- Test 1: N/A
- Test 2: N/A
> adding hypernet to the list

- Jenkinsfile
- Makefile
What: Update to v1.15.7 of go
Why: Security issues
> Makefile: update to go v1.15.7

- .clabot
What/Why: Adding both as they signed the CLA and PRs have been opened: #4031 
> .clabot: add harrymaurya05 and gregoirevda

- satellite/metainfo/metabase/alias.go
- satellite/metainfo/metabase/db.go
> satellite/metainfo/metabase: optimize node aliases migration

- private/migrate/versions.go
- satellite/metainfo/metabase/db.go
> satellite/metainfo/metabase: avoid tx in migration

- Jenkinsfile
- Makefile
- cmd/metainfo-loop-benchmark/bench.go
- cmd/metainfo-loop-benchmark/main.go
- private/version/release.go
- satellite/accounting/tally/tally.go
- satellite/core.go
- satellite/gc.go
- satellite/gracefulexit/pathcollector.go
- satellite/metainfo/config.go
- satellite/metainfo/loop.go
- satellite/metainfo/loop_test.go
- satellite/metainfo/metabase/commit.go
- satellite/metainfo/metabase/commit_object.go
- satellite/metainfo/metabase/db.go
- satellite/metainfo/metabase/delete.go
- satellite/metainfo/metabase/delete_bucket.go
- satellite/metainfo/metabase/fulliterator.go
- satellite/metainfo/metabase/get.go
- satellite/metainfo/metabase/iterator.go
- satellite/metainfo/metabase/list_segments.go
- satellite/metainfo/metabase/list_segments_test.go
- satellite/metainfo/metabase/loop.go
- satellite/metainfo/metabase/loop_test.go
- satellite/metainfo/metabase/test_test.go
- satellite/repair/checker/checker.go
What: 
Why:
- Test 1:
- Test 2:
> v1.24-multipart point release

- satellite/metainfo/config.go
- satellite/metainfo/expireddeletion/chore.go
- satellite/metainfo/metabase/bench_expired_test.go
- satellite/metainfo/metabase/delete_expired.go
- satellite/metainfo/metabase/test_test.go
- scripts/testdata/satellite-config.yaml.lock
What: Changes needed to fix issue with expired objects deletion
Why:
- Test 1:
- Test 2:
> Changes needed to fix issue with expired objects deletion

- satellite/console/consoleweb/server.go
- scripts/testdata/satellite-config.yaml.lock
What:  Enable new file browser and onboarding workflow on all satellites.
Why: We want to test this in production.
- Test 1:
- Test 2:
> satellite/web: enable feature flag for new file browser and onboarding workflow

- go.mod
- go.sum
- satellite/gc.go
What: 
Why:
- Test 1:
- Test 2:
> Point release-v1.27.1

- storagenode/peer.go
- storagenode/planneddowntime/common.go
- storagenode/planneddowntime/planneddowntime_test.go
- storagenode/planneddowntime/service.go
- storagenode/storagenodedb/database.go
- storagenode/storagenodedb/planneddowntime.go
- storagenode/storagenodedb/schema.go
- storagenode/storagenodedb/testdata/multidbsnapshot.go
- storagenode/storagenodedb/testdata/v52.go
Change-Id: Ic79d3ee1c0073e792dae115e922edc655df13046
What: 
Why:
- Test 1:
- Test 2:
> storagenode/planneddowntime: Add planned downtime database and service

- web/satellite/package-lock.json
- web/satellite/package.json
WHAT:
use new object browser version
Change-Id: Ieb473b8f4b1beff81a5c2661f55e8e3f946daa2e
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.30.2

- satellite/audit/reservoir.go
- satellite/audit/reservoir_test.go
- satellite/audit/verifier.go
- satellite/metabase/commit.go
- satellite/metabase/commit_test.go
- satellite/metabase/db.go
- satellite/metabase/db_internal_test.go
- satellite/metabase/delete_objects_test.go
- satellite/metabase/loop.go
- satellite/metabase/metabasetest/create.go
- satellite/metabase/metaloop/service.go
- satellite/metabase/segmentloop/service.go
- satellite/metainfo/metainfo.go
- satellite/metainfo/metainfo_test.go
- scripts/testdata/satellite-config.yaml.lock
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.32.1

- satellite/rewards/partners.go
What: Adding a few partners to our partners list for value attribution
Why: N/A
- Test 1: N/A
- Test 2: N/A
> adding partners to list

- Makefile
- multinode/console/consoleassets/assets.go
- multinode/console/server/server.go
- multinode/peer.go
- web/multinode/src/app/router/index.ts
web/multinode: redirect fix before route enters dashboard
makink node/infos request if trying to reach protected routes
multinode/console: embed web assets 
Change-Id: I34af0437437f8c670ac2a6eb61902fbc9114e540
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.34.3

- web/satellite/src/components/account/billing/paidTier/AddPaymentMethodModal.vue
What: 
Why:
- Test 1:
- Test 2:
> web/satellite: fix typo in  `Add a Payment method` popup

- Makefile
This reverts commit d867a7007f1df61241187697d7069b40452b4530.
What: 
Why:
- Test 1:
- Test 2:
> Revert "Makefile: disable building storagenode for darwin"

- cmd/uplink/cmd/cp.go
- scripts/test-uplink.sh
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.37.3

- web/multinode/.eslintrc.js
- web/satellite/.eslintrc.js
- web/storagenode/.eslintrc.js
Disable storj linter, because the build system doesn't know how to handle it.
> web/: disable storj linter

- Jenkinsfile.public
- Makefile
- scripts/test-sim-backwards.sh
- scripts/tests/rollingupgrade/test-sim-rolling-upgrade.sh
- scripts/tests/testversions/test-sim-versions.sh
- web/satellite/src/views/RegisterArea.vue
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.39.4

- web/satellite/jestSetup.ts
- web/satellite/src/router/index.ts
Also disable some warning/error checks in jestSetup.ts that are causing
build to fail.
Change-Id: Iafaa05af4058bd0f6cc1ec94f6d85b11672612f3
What: 
Why:
- Test 1:
- Test 2:
> web/satellite: Route all child routes to object browser

- Jenkinsfile
- Makefile
Change-Id: Ieed044780a38ebd209662ddacb24ba5e2998a319
What: 
Why:
- Test 1:
- Test 2:
> ci: use correct Go version for the image

- satellite/payments/coinpayments/client.go
- satellite/payments/coinpayments/conversionrates.go
- satellite/payments/coinpayments/conversionrates_test.go
- satellite/payments/stripecoinpayments/service.go
What: 
Why:
- Test 1:
- Test 2:
> point release v1.40.3

- satellite/console/consoleweb/server.go
- scripts/testdata/satellite-config.yaml.lock
What: 
NewNavigation, NewBrowser  set to true
Why:
For deployment convenience
- Test 1:
- Test 2:
> satellite/console: change default feature flag

- satellite/console/consoleweb/server.go
- scripts/testdata/satellite-config.yaml.lock
What: 
Why:
- Test 1:
- Test 2:
> satellite/console: enable object flow by default (#4298)

- scripts/release.sh
What: 
making clear if builing a production or development version
Why:
https://forum.storj.io/t/is-anybody-having-issues-with-v1-41-and-1-42/16128
- Test 1:
- Test 2:
> scripts: making clear if builing a production or development version

- cmd/storagenode-updater/loop.go
- cmd/storagenode-updater/main.go
- cmd/storagenode-updater/restart.go
- cmd/storagenode/service_nonwindows.go
- cmd/uplinkng/cmd_share_test.go
- storage/filestore/dir_unix.go
What: 
Changes to fix or ignore errors returned by golangci-lint v1.43.0
- dupArg: suspicious method call with the same argument and receiver (gocritic)
- File is not `gofmt`-ed with `-s` (gofmt)
See See https://github.com/storj/ci/pull/39
Why:
- We want to upgrade golangci-lint
- Test 1:
- Test 2:
> Golangci lint v1.43.0 changes

- satellite/analytics/hubspot.go
- satellite/analytics/service.go
- satellite/api.go
- satellite/console/consoleweb/consoleapi/analytics.go
- satellite/console/service.go
- scripts/testdata/satellite-config.yaml.lock
Track user events through HubSpot events API
What: 
Why:
- Test 1:
- Test 2:
> Track user events through HubSpot events API (#4300)

- Jenkinsfile
- Makefile
What: Bump go version to v1.17.5
Why: Critical Vulnerabilities in net/http.
- Test 1:
- Test 2:
> point release v1.45.3

- Makefile
What: Small fix to properly trigger the script.
- Test 1:
- Test 2:
> Makefile: fix variable used to trigger release drafting

- web/satellite/src/components/browser/FileModal.vue
What: Changes/Updates the function call for getting the Share Link.
Why: The FileModal had an outdated function call that caused issues
> web/satellite: fix FileModal Share Link

- go.mod
- go.sum
- satellite/contact/contact_test.go
- satellite/contact/endpoint.go
- testsuite/go.mod
- testsuite/go.sum
Change-Id: I832a72fafeacf76ad64a0129bcc6582cc4f9290d
What: add PingMe endpoint cherry-pick
Why:
- Test 1:
- Test 2:
> satellite/contact: add PingMe endpoint

- private/server/server.go
- satellite/console/consoleweb/consoleapi/auth.go
- satellite/console/consoleweb/consoleapi/auth_test.go
- storagenode/console/service.go
- storagenode/contact/contact_test.go
- storagenode/contact/service.go
- storagenode/peer.go
- web/storagenode/src/app/components/SNOContentTitle.vue
- web/storagenode/src/app/store/modules/node.ts
- web/storagenode/src/storagenode/api/storagenode.ts
- web/storagenode/src/storagenode/sno/sno.ts
- web/storagenode/tests/unit/components/DiskStatChart.spec.ts
- web/storagenode/tests/unit/components/payments/EstimationPeriodDropdown.spec.ts
- web/storagenode/tests/unit/store/node.spec.ts
What: 
Why:
- Test 1:
- Test 2:
> point release v1.47.2-rc

- satellite/console/service.go
The Update method of the usersDB takes a console.User as an argument.
To update the columns in the DB, we have to migrate the fields from the
console.Users struct into a special dbx struct. If one of these fields
is left empty, then the zero value of that field's type will be used to
update the respective column.
In most cases where the users.Update method is called, the entire
console.User is apparently retrieved first, fields are updated, then it
is passed to users.Update. This is not the case for
service.UpdateAccount. Because these fields are not populated in the
user struct in UpdateAccount before it is passed into users.Update,
their respective columns in the database are overwritten with zero:
ProjectLimit, ProjectStorageLimit, ProjectBandwidthLimit,
ProjectSegmentLimit, PaidTier, …
> satellite/console: pass entire auth.User into users.Update in service UpdateAccount

- cmd/uplinkng/external_access.go
- cmd/uplinkng/external_migrate.go
- scripts/tests/rollingupgrade/test-rolling-upgrade.sh
- scripts/tests/testversions/test-versions.sh
What: 
We need to include this fix to unblock our tests
Why:
- Test 1:
- Test 2:
> uplink fix for the release-v1.48

- Makefile
Change-Id: I3552de12fa99892bcd7e83aa5b0fdddb268f7db5
What: 
Why:
- Test 1:
- Test 2:
> makefile: remove uplink-image

- Makefile
- cmd/multinode/Dockerfile
- cmd/multinode/README.md
- cmd/multinode/entrypoint
What: 
Why:
- Test 1:
- Test 2:
> point release v1.49.3

- cmd/metabase-orphaned-segments/main.go
- cmd/metabase-orphaned-segments/main_test.go
- cmd/metabase-verify/main.go
- cmd/satellite/admin.go
- cmd/satellite/api.go
- cmd/satellite/fetchpieces.go
- cmd/satellite/gc.go
- cmd/satellite/main.go
- cmd/satellite/repairer.go
- private/testplanet/satellite.go
- satellite/metabase/commit_test.go
- satellite/metabase/db.go
- satellite/metabase/metabasetest/run.go
- satellite/repair/repairer/ec.go
- satellite/repair/repairer/segments.go
What: 
Why:
- Test 1:
- Test 2:
> point release-v1.49

- MAINTAINERS.md
What: 
Why:
- Test 1:
- Test 2:
> Maintainers: remove link

- web/multinode/src/app/components/modals/AddNewNode.vue
- web/multinode/src/app/views/AddFirstNode.vue
What: 
small change to the placeholder text to also include port and not only the IP address.
Why:
I do not add nodes to the dashboard on a regular basis but I always forget to add the port. I figured other people face the same experience.
> web/multinode: UI clarification to also add port

- cmd/storagenode/Dockerfile
- cmd/storagenode/Dockerfile.base
- cmd/storagenode/docker/bin/systemctl
Updating the version of the base image for the storagenode docker image.
Also fixes the non-root permission issue to /app directory
Change-Id: I8b55a1e3062f55ce6fc52e126ec1a18bfa24e669
What: 
Why:
- Test 1:
- Test 2:
> cmd/storagenode: update base image for storagenode

- Jenkinsfile.public
- certificate/certificatepb/gen.go
- cmd/storagenode-updater/loop_windows.go
- cmd/storagenode-updater/main_windows.go
- cmd/storagenode-updater/restart_linux.go
- cmd/storagenode-updater/restart_windows.go
- cmd/storagenode/service_windows.go
- private/crashreportpb/gen.go
- private/cui/example.go
- private/multinodepb/gen.go
- satellite/admin/oauthclients_testplanet_test.go
- satellite/console/wasm/main.go
- satellite/gc/gc_test.go
- satellite/internalpb/gen.go
- satellite/metabase/delete.go
- satellite/metabase/delete_test.go
- satellite/oidc/oauth_stores.go
- satellite/oidc/service.go
- satellite/satellitedb/migrate_gen.go
- satellite/satellitedb/migrate_test.go
- satellite/satellitedb/repairqueue.go
- scripts/draft-release.sh
- scripts/pg-to-crdb.go
- scripts/test-network-stalls.go
- scripts/update-access.go
- storage/filestore/dir_windows.go
- storagenode/internalpb/gen.go
- storagenode/storagenodedb/schemagen.go
- web/satellite/src/views/RegisterArea.vue
What: 
Why:
- Test 1:
- Test 2:
> release v1.51.2

- cmd/storagenode/Dockerfile
- cmd/storagenode/docker-base/bin/stop-supervisor
- cmd/storagenode/docker-base/etc/supervisor/supervisord.conf
- cmd/storagenode/docker/entrypoint
What: Add cherry-picks 
Why:
- Test 1:
- Test 2:
> Ak/cherry pick v1.54

- private/testplanet/satellite.go
- satellite/admin.go
- satellite/admin/README.md
- satellite/admin/project.go
- satellite/admin/project_test.go
- satellite/admin/server.go
- satellite/admin/user.go
- satellite/admin/user_test.go
- satellite/console/consoleweb/server.go
- satellite/core.go
- scripts/testdata/satellite-config.yaml.lock
What: 
Why:
- Test 1:
- Test 2:
> Release v1.56.1

- satellite/console/consoleweb/server.go
- satellite/console/emailreminders/chore.go
- scripts/testdata/satellite-config.yaml.lock
What: 
Why:
- Test 1:
- Test 2:
> Release v1.56.3

- satellite/console/consoleweb/server.go
What: 
fix for reCaptcha
Why:
- Test 1:
- Test 2:
> Release v1.56.4

- web/satellite/src/components/common/VInput.vue
- web/satellite/src/components/modals/OpenBucketModal.vue
- web/satellite/src/components/objects/BucketCreation.vue
Bucket creation/open flow wasn't storing credentials correctly inside Vuex store.
Change-Id: Ifc2eb8ca79a672dbc44d95089f7d6cee2e71bb57
What: 
Why:
- Test 1:
- Test 2:
> web/satellite: fix linksharing issue

- storagenode/reputation/service.go
What: 
Implement suggested fix for https://github.com/storj/storj/issues/4920
Why:
The wording was bad and confusing
- Test 1:
- Test 2:
> storagenode/reputation: clarify wording on suspension notification

- satellite/audit/verifier_test.go
- satellite/metabase/copy_object.go
- satellite/metabase/copy_object_test.go
- satellite/metabase/db.go
- satellite/metabase/delete.go
- satellite/metabase/metabasetest/create.go
- satellite/metabase/metabasetest/run.go
- satellite/metainfo/config.go
- satellite/metainfo/endpoint_object.go
- satellite/overlay/config.go
- satellite/overlay/service.go
- satellite/satellitedb/overlaycache.go
- scripts/testdata/satellite-config.yaml.lock
- web/satellite/src/components/common/TableItem.vue
- web/satellite/src/components/navigation/AccountArea.vue
- web/satellite/src/components/navigation/NavigationArea.vue
- web/satellite/src/components/objects/BucketItem.vue
- web/satellite/src/components/objects/BucketsView.vue
- web/satellite/src/router/index.ts
What: 
fixes filebrowser issues
Why:
- Test 1:
- Test 2:
> point-release v1.58.1

- satellite/console/consoleweb/server.go
- scripts/testdata/satellite-config.yaml.lock
What: Enable the new access grant flow in the satellite UI.
Why: It works on the QA satellite. There are some small issues but nothing that should stop us from enabling it on all production satellites.
- Test 1:
- Test 2:
> satellite/console: enable new access grant flow

- satellite/console/consoleweb/server.go
- scripts/testdata/satellite-config.yaml.lock
- web/satellite/src/components/modals/OpenBucketModal.vue
- web/satellite/src/components/objects/BucketCreation.vue
- web/satellite/src/components/objects/BucketDetails.vue
- web/satellite/src/components/objects/BucketItem.vue
- web/satellite/src/components/objects/BucketSettingsNav.vue
What: 
fix for bucket deletion
Why:
- Test 1:
- Test 2:
> point release v1.58.2

- Jenkinsfile.premerge
- Jenkinsfile.verify
- satellite/admin/ui/.gitignore
- satellite/admin/ui/node_modules/go.mod
- web/multinode/.gitignore
- web/multinode/node_modules/go.mod
- web/satellite/.gitignore
- web/satellite/node_modules/go.mod
- web/storagenode/.gitignore
- web/storagenode/node_modules/go.mod
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.59.1

- web/satellite/src/components/account/billing/paymentMethods/AddStorjForm.vue
- web/satellite/src/components/account/billing/paymentMethods/PaymentMethods.vue
- web/satellite/src/components/modals/AddPaymentMethodModal.vue
- web/satellite/tests/unit/account/billing/paymentMethods/__snapshots__/AddStorjForm.spec.ts.snap
- web/satellite/tests/unit/account/billing/paymentMethods/__snapshots__/PaymentMethods.spec.ts.snap
What:  Changes with Coinpayments restrictions
Why:
- Test 1:
- Test 2:
> point release v1.60.3

- satellite/console/consoleweb/consoleapi/auth_test.go
- satellite/mailservice/simulate/nomail.go
- satellite/peer.go
- satellite/satellitedb/projectaccounting.go
- web/satellite/src/api/projects.ts
- web/satellite/src/components/project/newProjectDashboard/NewProjectDashboard.vue
The new dashboard currently gets stuck on loading and displays an error when
it fails to get usage data. Failure happens on satelliteDb due to a cockroach transaction error
caused by reading data before using AS OF SYSTEM TIME in the same transaction.
This change reverses the order of daily usage queries to avoid this error.
And hides the loaders on the dashboard if/when an error occurs.
see: https://github.com/storj/storj/issues/5012
Change-Id: I06b6ee434f72242f9b7d21dec7aaf39d1d622f1e
What: 
Fix for Dashboard
Why:
- Test 1:
- Test 2:
> point release v1.61.2 fix project daily usage error

- web/satellite/src/components/account/billing/billingTabs/BillingHistory.vue
- web/satellite/src/components/account/billing/billingTabs/Coupons.vue
- web/satellite/src/components/account/billing/billingTabs/Overview.vue
- web/satellite/src/components/account/billing/billingTabs/PaymentMethods.vue
- web/satellite/src/components/account/billing/estimatedCostsAndCredits/UsageAndChargesItem2.vue
- web/satellite/src/components/navigation/NavigationArea.vue
What: Changed the Billing History tab to only display Stripe payments, and addressed the following tickets:
https://github.com/storj/storj/issues/5028
https://github.com/storj/storj/issues/5027
https://github.com/storj/storj/issues/5026
https://github.com/storj/storj/issues/5021
Why:
- Test 1:
- Test 2:
> web/satellite Billing screen bug fixes

- storagenode/storagenodedb/storageusage.go
- storagenode/storageusage/storageusage_test.go
Wrapping a COALESCE around the computed at_rest_total value to fallback
to the original at_rest_total value when the computed value is null.
https://forum.storj.io/t/release-preparation-v1-62/19444/5?u=clement
Change-Id: Ifa268ccbe35a63e3b68f07464194fa034ad261b5
What: 
Why:
- Test 1:
- Test 2:
> storagenode/storagenodedb: fix null at_rest_total values for storage usage

- satellite/metabase/iterator.go
- satellite/metabase/iterator_test.go
- web/satellite/src/components/accessGrants/CreateAccessModal.vue
- web/satellite/src/components/accessGrants/modals/CreateFormModal.vue
- web/satellite/src/components/accessGrants/modals/EncryptFormModal.vue
- web/satellite/src/components/accessGrants/modals/GrantCreatedModal.vue
What: A few cherry picks for listing performance optimization and a fix for the access grant wizard in the satellite UI.
- Test 1:
- Test 2:
> Point release v1.62.4 listing optimization and access grant fix

- web/satellite/src/components/accessGrants/AccessGrants.vue
- web/satellite/src/components/accessGrants/modals/CreateFormModal.vue
- web/satellite/src/components/accessGrants/modals/GrantCreatedModal.vue
- web/satellite/src/components/modals/ShareBucketModal.vue
- web/satellite/src/components/objects/UploadFile.vue
- web/satellite/src/components/project/newProjectDashboard/NewProjectDashboard.vue
What: 
fixes for links and for sharing access grants were added
Why:
- Test 1:
- Test 2:
> point release v1.63.1

- go.mod
- go.sum
- testsuite/storjscan/go.mod
- testsuite/storjscan/go.sum
- testsuite/ui/go.mod
- testsuite/ui/go.sum
- web/satellite/src/components/browser/FileBrowser.vue
- web/satellite/src/store/modules/files.ts
- web/satellite/src/utils/eventBus.ts
- web/satellite/src/views/DashboardArea.vue
What: 
Why:
- Test 1:
- Test 2:
> point release 1.66.1

- scripts/draft-release.sh
What: 
Why:
- Test 1:
- Test 2:
> scripts/draft-release.sh: change path to script

- Jenkinsfile.premerge
- Jenkinsfile.public
- Jenkinsfile.verify
This change removes the go mod download process for the UI tests, removes the commented out code block that once called the UI tests, and the duplicate web/wasm build step. The Build step for the web/wasm is now executed via a shell script and called much earlier in the tests.
What: Remove left over pieces from the gorod Ui tests and clean up a duplicate call to building web packages and wasm file. 
Why: Some parts of the process were executing to provide dependencies and requirements for go-rod UI tests. This steps are not necessary and can be removed in order to accelerate the execution time. While making these changes I noticed that the web packages and wasm code were being built twice. As the newest process calls shell scripts and is executed before the build process, I removed the …
> ci: removed ui artifacts

- web/satellite/src/components/navigation/AccountArea.vue
- web/satellite/src/components/navigation/MobileNavigation.vue
- web/satellite/src/utils/localData.ts
- web/satellite/src/views/DashboardArea.vue
Fixed Vuex state clearing on session timeout.
Now state is being cleared right after redirect to login and before logout API call.
Change-Id: I3cddb85735899f0913a273a49335730a4097435e
What: 
Why: fix for passphrase problem after inactivity logout
- Test 1:
- Test 2:
> web/satellite: fix Vuex state clearing on session timeout

- satellite/orders/endpoint.go
- satellite/orders/rollups_write_cache_test.go
Orders from storage nodes are received by SettlementWithWindowFinal method. There is a stream which receives all orders and after getting all orders we are inserting into DB storagenode and bucket bandwidth. Problem is with bucket bandwidth which is stored through cache which is often using context from SettlementWithWindowFinal stream to perform DB inserts and its doing this in separate goroutine. Because of that is possible that  SettlementWithWindowFinal is finished before flushing was finished and context is canceled while doing insert into DB
Change-Id: I3a72c86390e9aedc060f6b082bb059f1406231ee
What: point release v1.74.4 with potential fix for bucket bandwidth
Why:
- Test 1:
- Test 2:
> point release v1.72.4 

- satellite/payments/balance.go
- web/satellite/src/components/account/billing/billingTabs/Overview.vue
- web/satellite/src/components/account/billing/estimatedCostsAndCredits/UsageAndChargesItem.vue
- web/satellite/src/components/account/billing/estimatedCostsAndCredits/UsageAndChargesItem2.vue
- web/satellite/src/components/modals/AddPaymentMethodModal.vue
- web/satellite/src/components/onboardingTour/steps/OverviewStep.vue
- web/satellite/src/types/payments.ts
- web/satellite/src/utils/strings.ts
- web/satellite/src/views/DashboardArea.vue
- web/satellite/tests/unit/onboardingTour/steps/OverviewStep.spec.ts
- web/satellite/tests/unit/utils/strings.spec.ts
What: 
fix  stripe balance, onboarding, and prices for gb-labs
Why:
- Test 1:
- Test 2:
> cherry pick v1.75

- private/testplanet/satellite.go
- satellite/nodeselection/uploadselection/state.go
- satellite/overlay/service.go
- satellite/overlay/uploadselection.go
- satellite/repair/checker/observer_test.go
- satellite/repair/repair_test.go
What: 
Why:
fix for ranged loop 
- Test 1:
- Test 2:
> point release 1.79.2

- satellite/repair/checker/observer.go
Clumped segments (segments with multiple pieces on the same subnet) may need repair, but the clumped pieces are considered retrievable and we don't need to call such segments irreparable.
We do want to know where they're coming from, though, if we can, because we are seeing more than expected.
Change-Id: I41863b243f4bb007ef8929191a3fde1562565ef9
What: 
fix for repair and ranged loop
Why:
- Test 1:
- Test 2:
> point release 1.79.3

- satellite/nodeselection/uploadselection/state.go
- satellite/overlay/service.go
- satellite/overlay/uploadselection.go
- satellite/repair/checker/config.go
- satellite/repair/checker/observer.go
- satellite/repair/checker/observer_test.go
- satellite/repair/repair_test.go
- satellite/repair/repairer/repairer.go
- satellite/repair/repairer/segments.go
- scripts/testdata/satellite-config.yaml.lock
What: 
Why:
fix for ranged loop
- Test 1:
- Test 2:
> point release 1.79.4

- satellite/console/consoleweb/config.go
- satellite/console/consoleweb/server.go
- scripts/testdata/satellite-config.yaml.lock
- web/satellite/src/api/v0.gen.ts
- web/satellite/src/components/project/dashboard/ProjectDashboard.vue
- web/satellite/src/types/config.gen.ts
What: 
disable new limits area and all project to false 
Why:
- Test 1:
- Test 2:
> point release 1.80.3

- satellite/repair/repairer/segments.go
- satellite/repair/repairer/segments_test.go
Change-Id: I4efe67f2d5f545a1d70e831e5d297f0977a4eed1
What: 
fix problem with segment repairer
Why:
- Test 1:
- Test 2:
> point release 1.81.2

- satellite/overlay/placement.go
- satellite/overlay/placement_test.go
> satellite/overlay: NR placement should exclude nodes without geofencing information

- satellite/metainfo/endpoint_object_test.go
- satellite/nodeselection/filter.go
- satellite/nodeselection/filter_test.go
- satellite/nodeselection/region.go
- satellite/nodeselection/selector_test.go
- satellite/nodeselection/state.go
- satellite/overlay/placement.go
- satellite/overlay/placement_test.go
- satellite/overlay/uploadselection.go
- satellite/overlay/uploadselection_test.go
- satellite/repair/repairer/segments.go
- satellite/repair/repairer/segments_test.go
- satellite/repair/repairer/segments_unit_test.go
- satellite/satellitedb/overlaycache.go
What: 
Why:
cherry-pick important changes for SOC-2 support
- Test 1:
- Test 2:
> point release v1.86.1

- satellite/metabase/commit.go
- satellite/metabase/commit_test.go
- satellite/metainfo/endpoint.go
- web/satellite/src/components/account/billing/billingTabs/Overview.vue
- web/satellite/src/components/browser/FileBrowser.vue
- web/satellite/src/components/common/TableSizeChanger.vue
- web/satellite/src/components/common/VTable.vue
- web/satellite/src/components/project/dashboard/ProjectDashboard.vue
- web/satellite/src/components/projectsList/ProjectsList.vue
- web/satellite/vuetify-poc/src/views/Billing.vue
- web/satellite/vuetify-poc/src/views/Dashboard.vue
What: 
Why:
- Test 1:
- Test 2:
> point release v1.88.2

- satellite/console/consoleweb/server.go
Include *.storjsatelliteshare.io in the `connect-src` portion of the CSP for the satellite UI.
Change-Id: Ic8c3d0cf892a3275866634cae3e9260d925e1c3e
What: 
Include *.[storjsatelliteshare.io](http://storjsatelliteshare.io/) in the `connect-src` portion of the CSP
for the satellite UI
Why:
fix for linksharing
- Test 1:
- Test 2:
> point release v1.88.3

- private/post/sender.go
- satellite/admin/project.go
- satellite/console/projects.go
- satellite/peer.go
- satellite/satellitedb/projects.go
What: 
Add support for unauthenticated, cleartext SMTP connections,  fix geofence removal
Why:
- Test 1:
- Test 2:
> point release v1.89.4

- web/satellite/src/store/modules/objectBrowserStore.ts
What: 
fix object count calculation inside folders
Why:
- Test 1:
- Test 2:
> point release v1.90.1

- satellite/console/consoleweb/server.go
What: 
rate limit project invitation endpoint
Why:
fix to prevent exploiting invitation functionality
- Test 1:
- Test 2:
> point release v1.90.2

- satellite/console/config.go
- satellite/console/consoleweb/config.go
- satellite/console/consoleweb/server.go
- scripts/testdata/satellite-config.yaml.lock
- web/satellite/src/api/payments.ts
- web/satellite/src/components/account/billing/billingTabs/PaymentMethods.vue
- web/satellite/src/components/modals/ChangeProjectLimitModal.vue
- web/satellite/src/components/modals/PricingPlanModal.vue
- web/satellite/src/components/modals/upgradeAccountFlow/AddCreditCardStep.vue
- web/satellite/src/store/modules/billingStore.ts
- web/satellite/src/types/config.gen.ts
- web/satellite/src/types/payments.ts
- web/satellite/vuetify-poc/src/components/AddCreditCardComponent.vue
- web/satellite/vuetify-poc/src/components/dialogs/CreateProjectDialog.vue
- web/satellite/vuetify-poc/src/components/dialogs/upgradeAccountFlow/AddCreditCardStep.vue
- web/satellite/vuetify-poc/src/components/dialogs/upgradeAccountFlow/PricingPlanStep.vue
What: 
cherry-pick fixes for GooglePay, Storj tokens amount for banner, limit increase feature flag
Why:
- Test 1:
- Test 2:
> release v1.92.1

- cmd/satellite/main.go
- satellite/admin/project_test.go
- satellite/console/config.go
- satellite/console/consoleweb/config.go
- satellite/console/consoleweb/server.go
- satellite/payments/stripe/projectrecords.go
- satellite/payments/stripe/service.go
- satellite/payments/stripe/service_test.go
- satellite/satellitedb/invoiceprojectrecords.go
- scripts/testdata/satellite-config.yaml.lock
- web/satellite/src/types/config.gen.ts
What: 
add aggregate invoice items if many projects feature
Why:
- Test 1:
- Test 2:
> release v1.93.1

- web/satellite/index-vuetify.html
- web/satellite/src/types/router.ts
- web/satellite/src/utils/httpClient.ts
- web/satellite/vuetify-poc/src/App.vue
- web/satellite/vuetify-poc/src/components/utils/BrandedLoader.vue
- web/satellite/vuetify-poc/src/layouts/default/AllProjects.vue
- web/satellite/vuetify-poc/src/layouts/default/AppBar.vue
- web/satellite/vuetify-poc/src/layouts/default/Auth.vue
- web/satellite/vuetify-poc/src/layouts/default/Default.vue
- web/satellite/vuetify-poc/src/router/index.ts
- web/satellite/vuetify-poc/src/views/Billing.vue
- web/satellite/vuetify-poc/src/views/Bucket.vue
- web/satellite/vuetify-poc/src/views/Login.vue
What: cherry-pick
Why: This change fixes an issue where navigating directly to a page when unauthenticated will show the page for a while before navigating to the login page
- Test 1:
- Test 2:
> cherry-pick v1.96.2

- web/satellite/vuetify-poc/src/styles/styles.scss
- web/satellite/vuetify-poc/src/views/ForgotPassword.vue
- web/satellite/vuetify-poc/src/views/Login.vue
- web/satellite/vuetify-poc/src/views/Signup.vue
Responsive improvements
Background styling and responsiveness
Added tooltip for remember me checkbox
Fix password strength to show over the cards on mobile
> web/satellite/v2: update signup and login

- web/satellite/src/composables/useSessionTimeout.ts
- web/satellite/src/utils/localData.ts
- web/satellite/vuetify-poc/src/styles/styles.scss
- web/satellite/vuetify-poc/src/views/ForgotPassword.vue
- web/satellite/vuetify-poc/src/views/Login.vue
- web/satellite/vuetify-poc/src/views/Signup.vue
What: 
fix for remember me functionality along with UI improvement
Why:
- Test 1:
- Test 2:
> v1.96.3 cherry pick UI fixes

- web/satellite/vuetify-poc/src/components/ErrorPage.vue
- web/satellite/vuetify-poc/src/components/UsageProgressComponent.vue
- web/satellite/vuetify-poc/src/components/dialogs/ChangeNameDialog.vue
- web/satellite/vuetify-poc/src/components/dialogs/CreateAccessDialog.vue
- web/satellite/vuetify-poc/src/components/dialogs/EditDefaultCreditCardDialog.vue
- web/satellite/vuetify-poc/src/components/dialogs/RemoveCreditCardDialog.vue
- web/satellite/vuetify-poc/src/components/dialogs/accountSetupSteps/BusinessStep.vue
- web/satellite/vuetify-poc/src/components/dialogs/accountSetupSteps/PersonalStep.vue
- web/satellite/vuetify-poc/src/components/dialogs/ccActionComponents/CreditCardItem.vue
- web/satellite/vuetify-poc/src/components/dialogs/upgradeAccountFlow/AddTokensStep.vue
- web/satellite/vuetify-poc/src/views/Dashboard.vue
- web/satellite/vuetify-poc/src/views/ProjectSettings.vue
What: 
V2 UI UX Improvements
Update language and colors
Update error page
Update add tokens dialog
Update remove card dialog
Update edit default card dialog
Make access creation dialog persistent
Change order of use cases during onboarding
Why:
Continuous improvements of the v2 ui.
> web/satellite/v2: ui-ux improvements

- satellite/accounting/projectusage_test.go
- satellite/metabase/iterator.go
- satellite/metabase/iterator_test.go
- satellite/metabase/list.go
- satellite/metabase/metabasetest/create.go
- satellite/metabase/metabasetest/test.go
- satellite/metainfo/endpoint_object.go
- satellite/orders/service.go
- satellite/orders/service_test.go
- satellite/satellite-config.yaml.lock
What: 
Why:
- Test 1:
- Test 2:
> point release v1.96.4

- web/satellite/src/components/dialogs/DropzoneDialog.vue
Why : cherry-pick fix for an issue where dropping a file in the drag dropzone will not upload the file and will throw an error in the console.
> cherry-pick fix file dropzone

- satellite/console/config.go
- satellite/console/consoleweb/config.go
- satellite/console/consoleweb/consoleapi/projects.go
- satellite/console/consoleweb/server.go
- satellite/satellite-config.yaml.lock
- satellite/satellitedb/apikeys.go
- web/satellite/src/types/config.gen.ts
What: fix for critical issue
Why: Nil slice ends up serialized as null in JSON, so some parsing can fail.
- Test 1:
- Test 2:
> fix for release-v1.99

- cmd/certificates/main.go
- cmd/crashcollect/main.go
- cmd/identity/main.go
- cmd/metric-receiver/main.go
- cmd/multinode/main.go
- cmd/satellite/main.go
- cmd/storagenode-updater/main.go
- cmd/storagenode-updater/main_windows.go
- cmd/storagenode/cmd_run.go
- cmd/storagenode/main.go
- cmd/storagenode/service_windows.go
- cmd/storj-admin/main.go
- cmd/tools/metabase-verify/main.go
- cmd/tools/migrate-public-ids/main.go
- cmd/tools/node-cleanup/main.go
- cmd/tools/placement-test/main.go
- cmd/tools/segment-verify/main.go
- cmd/tools/tag-signer/main.go
- cmd/uplink/cmd_cp.go
- cmd/uplink/cmd_cp_test.go
- cmd/versioncontrol/main.go
- private/date/utils.go
- private/date/utils_test.go
- storagenode/blobstore/filestore/dir_windows.go
What: 
fix for windows nodes
Why:
- Test 1:
- Test 2:
> point release v1.99.3

- satellite/console/config.go
- satellite/console/observerupgradeuser.go
- satellite/console/service.go
- satellite/console/service_test.go
- satellite/satellite-config.yaml.lock
- web/satellite/src/views/Login.vue
What: 
fix token upgrade logic - remove trialExpiredFrozen event
along with improvements for L2
Why:
- Test 1:
- Test 2:
> point release: fix token upgrade

- web/satellite/src/components/BrowserCardViewComponent.vue
- web/satellite/src/components/BrowserTableComponent.vue
- web/satellite/src/components/BucketsDataTable.vue
- web/satellite/src/components/PageTitleComponent.vue
- web/satellite/src/components/dialogs/AddTokensDialog.vue
- web/satellite/src/components/dialogs/EmissionsDialog.vue
- web/satellite/src/components/dialogs/appSetupSteps/ChooseFlowStep.vue
- web/satellite/src/components/dialogs/appSetupSteps/ChoosePermissionsStep.vue
- web/satellite/src/components/dialogs/appSetupSteps/SelectBucketsStep.vue
- web/satellite/src/components/dialogs/upgradeAccountFlow/AddTokensStep.vue
- web/satellite/src/components/dialogs/upgradeAccountFlow/AddTokensStepBanner.vue
- web/satellite/src/components/icons/IconVersioning.vue
Update add tokens dialog to explain the 10% bonus and update the network information alert. 
Add information to carbon emissions sustainability dialog. 
Update browser drop-zones in table and card view.
Show all columns in the buckets table, on all screen sizes. 
Update versioning icon.
Update new apps setup flow.
Plus additional styling updates.
> web/satellite: ui updates

- cmd/storagenode/internalcmd/gc_filewalker.go
- cmd/storagenode/internalcmd/trash_filewalker.go
- cmd/storagenode/internalcmd/used_space_filewalker.go
- cmd/tools/segment-verify/main_test.go
- storagenode/blobstore/blob.go
- storagenode/blobstore/filestore/dir.go
- storagenode/blobstore/filestore/dir_test.go
- storagenode/blobstore/filestore/store.go
- storagenode/blobstore/filestore/store_test.go
- storagenode/blobstore/testblobs/bad.go
- storagenode/blobstore/testblobs/slow.go
- storagenode/peer.go
- storagenode/pieces/cache_test.go
- storagenode/pieces/deleter_test.go
- storagenode/pieces/filewalker.go
- storagenode/pieces/filewalkerdb.go
- storagenode/pieces/filewalkerdb_test.go
- storagenode/pieces/lazyfilewalker/process.go
- storagenode/pieces/lazyfilewalker/supervisor.go
- storagenode/pieces/lazyfilewalker/supervisor_test.go
- storagenode/pieces/lazyfilewalker/writer.go
- storagenode/pieces/readwrite_test.go
- storagenode/pieces/store.go
- storagenode/pieces/store_test.go
- storagenode/retain/retain.go
- storagenode/retain/retain_test.go
- storagenode/storagenodedb/gcprogress.go
What: 
Why:
- Test 1:
- Test 2:
> Fix for gc filewalker v1.101.3

- satellite/analytics/hubspot.go
- satellite/analytics/service.go
- satellite/console/consoleweb/server.go
- web/satellite/src/api/projects.ts
What: 
Why:
- Test 1:
- Test 2:
> release candidate  v1.102.2

- satellite/analytics/hubspot.go
- web/satellite/src/components/dialogs/accountSetupSteps/BusinessStep.vue
Update business form in the satellite UI to match form values in Hubspot; update property names in analytics backend to match property names in Hubspot.
Change-Id: I2365584867f3fad1e08579e4e53b028bbf4dd52c
What: 
Why:
- Test 1:
- Test 2:
> release v1.102.3

- web/satellite/src/layouts/default/AppBar.vue
- web/satellite/src/layouts/default/AuthBar.vue
What: 
Fix updated logo sizing and position in auth pages and in nav bar. 
> web/satellite: logo size and position fix

- storagenode/diskmon.go
- storagenode/diskmon_unsupported.go
- storagenode/peer.go
Change-Id: I0951a252e8bd77468296290dd76f23f931543a98
What: 
Why:
Jenkins build fails
- Test 1:
- Test 2:
> cherry-pick: fix disk monitoring for FreeBSD

- satellite/console/consoleweb/server.go
Remove rate limit on plausible pageview route.
Change-Id: If372cbb2c6be7f1287622d06363acff6ad9bc3ae
What: 
Why:
- Test 1:
- Test 2:
> cherry-pick fix ratelimiter

- web/satellite/src/components/dialogs/createAccessSteps/AccessEncryptionStep.vue
Fix the layout of the encryption step for access creation flow.
> web/satellite: fix layout of access encryption

- web/satellite/src/api/abtesting.ts
Added NULL check for GET A/B testing values response.
What: 
fix for a/b testing
Why:
- Test 1:
- Test 2:
> cherry pick v1.104.3

- satellite/api.go
- satellite/metabase/commit.go
- satellite/metabase/commit_test.go
- satellite/metabase/metabasetest/test.go
- satellite/metainfo/batch.go
- satellite/metainfo/config.go
- satellite/metainfo/endpoint.go
- satellite/metainfo/endpoint_object.go
- satellite/metainfo/endpoint_segment.go
- satellite/metainfo/success_tracker.go
- satellite/metainfo/success_tracker_test.go
- satellite/satellite-config.yaml.lock
What: 
Cherry pick "power of 2" changes for node selection and inline object upload improvements
Why:
Create an RC build for testing performance improvements in SLC
- Test 1:
- Test 2:
> cherry-pick for v1.104.6-rc2

- cmd/satellite/Dockerfile
- cmd/storagenode/Dockerfile.dev
What: 
fix for building images
Why:
- Test 1:
- Test 2:
> cherry pick v1.105.4

- web/satellite/src/App.vue
- web/satellite/src/components/dialogs/managePassphraseSteps/ManageOptionsStep.vue
What: 
UI fixes 
Why:
- Test 1:
- Test 2:
> cherry pick v1.107.1

- satellite/console/accountfreezes.go
- satellite/console/accountfreezes_test.go
- satellite/console/projectusagelimits.go
What: 
fix for account freeze limits
Why:
- Test 1:
- Test 2:
>  cherry pick v1.107.2

- web/satellite/src/components/dialogs/accountSetupSteps/ManagedPassphraseOptInSelector.vue
Update the onboarding screen for choosing project encryption.
> web/satellite: update managed passphrase step

- web/satellite/src/components/dialogs/AccountSetupDialog.vue
- web/satellite/src/components/dialogs/accountSetupSteps/BusinessStep.vue
- web/satellite/src/components/dialogs/accountSetupSteps/PersonalStep.vue
What: 
Fixed the issue when user data was not updated during setup account flow
Why:
- Test 1:
- Test 2:
> cherry-pick v1.108.1

- Jenkinsfile.public
- storagenode/blobstore/blob.go
- storagenode/blobstore/filestore/dir.go
- storagenode/blobstore/filestore/store.go
- storagenode/blobstore/testblobs/bad.go
- storagenode/blobstore/testblobs/slow.go
- storagenode/pieces/store.go
- storagenode/pieces/store_test.go
- web/satellite/package-lock.json
- web/satellite/package.json
- web/satellite/src/plugins/vuetify.ts
- web/satellite/src/views/ProjectSettings.vue
What: 
Why:
- Test 1:
- Test 2:
> point release v1.109.1

- web/satellite/src/components/StorjTokenCardComponent.vue
- web/satellite/src/components/TokenTransactionsTableComponent.vue
- web/satellite/src/components/billing/BillingHistoryTab.vue
- web/satellite/src/components/billing/BillingInformationTab.vue
- web/satellite/src/components/dialogs/ApplyCouponCodeDialog.vue
- web/satellite/src/components/dialogs/BillingAddressDialog.vue
- web/satellite/src/components/dialogs/BucketDetailsDialog.vue
- web/satellite/src/components/dialogs/EditDefaultCreditCardDialog.vue
- web/satellite/src/components/dialogs/FilePreviewDialog.vue
- web/satellite/src/components/dialogs/ProjectEncryptionInformationDialog.vue
- web/satellite/src/components/dialogs/RemoveCreditCardDialog.vue
- web/satellite/src/components/dialogs/RemoveProjectMemberDialog.vue
- web/satellite/src/components/dialogs/ccActionComponents/CreditCardItem.vue
- web/satellite/src/layouts/default/ProjectNav.vue
- web/satellite/src/styles/styles.scss
- web/satellite/src/views/AccountSettings.vue
- web/satellite/src/views/Dashboard.vue
- web/satellite/src/views/ForgotPassword.vue
- web/satellite/src/views/ProjectSettings.vue
- web/satellite/src/views/Projects.vue
Design updates for satellite ui.
> web/satellite: design updates

- storagenode/monitor/monitor.go
What: 
I was curious about how much exactly are readability/writability checks taking. Given that they don't contribute much to the volume of logs, added their duration there. Besides, might be a useful diagnostic for many forum posts.
Why:
None.
> storagenode/monitor: log duration of storage checks

- satellite/accounting/db.go
- satellite/accounting/projectusage.go
- satellite/accounting/projectusage_test.go
- satellite/metainfo/endpoint_object.go
- satellite/metainfo/endpoint_segment.go
- satellite/metainfo/validation.go
- satellite/satellitedb/projectaccounting.go
- storagenode/pieces/cache.go
- storagenode/retain/retain_test.go
> point release v1.110.3

- satellite/gc/bloomfilter/config.go
- satellite/gc/bloomfilter/observer.go
- satellite/metabase/delete_objects.go
- satellite/metabase/delete_objects_test.go
- satellite/metainfo/expireddeletion/chore.go
- satellite/metainfo/expireddeletion/expireddeletion_test.go
- satellite/satellite-config.yaml.lock
> Point release v1.111.5

- satellite/console/consoleweb/consoleapi/projects_test.go
- satellite/repair/queue/queue_test.go
- web/satellite/src/components/BrowserCardViewComponent.vue
- web/satellite/src/components/BrowserTableComponent.vue
- web/satellite/src/components/FileCard.vue
- web/satellite/src/components/dialogs/AccountSetupDialog.vue
- web/satellite/src/store/modules/objectBrowserStore.ts
- web/satellite/src/views/Bucket.vue
What: 
make versioning default, fix sign up flow, fix gallery view
Why:
- Test 1:
- Test 2:
> cherry pick v1.113.1

- cmd/tools/piecestore-benchmark/main.go
- satellite/satellitedb/repairqueue_test.go
- storagenode/pieces/store.go
- storagenode/piecestore/endpoint.go
Change-Id: I89e375ad09dc839c7475e9862a0dd93daa6fed96
What: 
Why:
- Test 1:
- Test 2:
> storagenode/piece: enable flat expiration store by default

- satellite/metabase/commit_object.go
- satellite/metabase/delete.go
- satellite/metabase/delete_objects.go
- satellite/metabase/precommit.go
Looks like ARRAY_INCLUDES uses Full Table Scan:
```
spanner> explain analyze DELETE FROM segments WHERE ARRAY_INCLUDES([B'\xcafebabe'], stream_id);
+-----+----------------------------------------------------------------------------------------------+---------------+------------+---------------+
| ID  | Query_Execution_Plan                                                                         | Rows_Returned | Executions | Total_Latency |
+-----+----------------------------------------------------------------------------------------------+---------------+------------+---------------+
|   0 | Apply Mutations (operation_type: DELETE, table: segments)                                    | 0             | 1          | 0.19 msecs    |
|   1 | +- Distributed Union (distribution_table: segments, …
```
> satellite/metabase: replace spanner ARRAY_INCLUDES with BatchUpdate

- satellite/console/accountfreezes.go
- satellite/metainfo/success_tracker.go
- satellite/metainfo/success_tracker_test.go
- satellite/nodeselection/config.go
- satellite/nodeselection/config_test.go
- satellite/nodeselection/config_test.yaml
- satellite/nodeselection/selector.go
- satellite/nodeselection/selector_test.go
- satellite/overlay/uploadselection.go
- satellite/repair/repairer/segments.go
What: 
Why:
- Test 1:
- Test 2:
> cherry pick v1.113.4

- web/satellite/src/components/VersioningBetaBanner.vue
- web/satellite/src/components/dialogs/AccountSetupDialog.vue
- web/satellite/src/components/dialogs/CreateBucketDialog.vue
- web/satellite/src/components/dialogs/LockBetaDialog.vue
- web/satellite/src/components/dialogs/VersioningBetaDialog.vue
- web/satellite/src/components/dialogs/accountSetupSteps/AccountTypeStep.vue
- web/satellite/src/components/dialogs/accountSetupSteps/BusinessStep.vue
- web/satellite/src/components/dialogs/accountSetupSteps/ChoiceStep.vue
- web/satellite/src/components/dialogs/accountSetupSteps/ManagedPassphraseOptInStep.vue
- web/satellite/src/components/dialogs/accountSetupSteps/PersonalStep.vue
- web/satellite/src/components/dialogs/accountSetupSteps/SuccessStep.vue
- web/satellite/src/components/onboarding/OnboardingStepperComponent.vue
- web/satellite/src/layouts/default/AppBar.vue
- web/satellite/src/layouts/default/AuthBar.vue
- web/satellite/src/styles/styles.scss
- web/satellite/src/views/Access.vue
- web/satellite/src/views/Buckets.vue
- web/satellite/src/views/Domains.vue
- web/satellite/src/views/Team.vue
Update account onboarding, app and auth bars, onboarding stepper, versioning banner, bucket creation step order, fix docs links for versioning and object lock, icons, styles, and layouts.
> web/satellite: ui ux improvements

- Jenkinsfile.public
- satellite/payments/billing/chore_test.go
- storagenode/orders/store.go
What: 
fix data race
Why:
- Test 1:
- Test 2:
> cherry pick v1.114.2

- cmd/storagenode-updater/cmd.go
- cmd/storagenode-updater/cmd_test.go
- cmd/storagenode-updater/loop.go
- cmd/storagenode-updater/loop_windows.go
- cmd/storagenode-updater/update.go
- cmd/tools/metabase-verify/verify/verify.go
- satellite/audit/observer_test.go
- satellite/gc-bf.go
- satellite/gc/bloomfilter/observer.go
- satellite/gc/bloomfilter/observer_test.go
- satellite/gc/bloomfilter/upload.go
- satellite/gc/gc_test.go
- satellite/gc/sender/service_test.go
- satellite/metabase/loop.go
- satellite/metabase/loop_test.go
- satellite/metabase/rangedloop/providerdb.go
- satellite/metabase/rangedloop/providerdb_test.go
- satellite/metabase/rangedloop/service.go
- satellite/metabase/rangedloop/service_test.go
- satellite/rangedloop.go
- satellite/repair/checker/observer_test.go
- satellite/satellite-config.yaml.lock
What: 
Why:
- Test 1:
- Test 2:
> cherry pick v1.114.5

- cmd/satellite/usage.go
- satellite/accounting/common.go
- satellite/accounting/db.go
- satellite/accounting/rollup/rollup_test.go
- satellite/overlay/service.go
- satellite/overlay/service_test.go
- satellite/overlay/uploadselection_test.go
- satellite/satellitedb/overlaycache.go
- satellite/satellitedb/storagenodeaccounting.go
What: 
Why:
- Test 1:
- Test 2:
> point release v1.115.2

- cmd/storagenode/cmd_run.go
- storagenode/blobstore/filestore/dir.go
- storagenode/peer.go
- storagenode/pieces/cache.go
- storagenode/pieces/pieceexpiration.go
- storagenode/storagenodedb/pieceexpiration.go
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.115.3

- go.mod
- go.sum
- satellite/console/consoleauth/sso/oidc.go
- satellite/console/consoleweb/consoleapi/auth.go
- satellite/console/consoleweb/server.go
- scripts/generate-gomod-for-storagenode-go1.20.sh
- web/satellite/src/api/auth.ts
- web/satellite/src/components/dialogs/AccountSetupDialog.vue
- web/satellite/src/components/dialogs/upgradeAccountFlow/AddTokensStep.vue
- web/satellite/src/components/onboarding/NextStepsContainer.vue
- web/satellite/src/types/users.ts
- web/satellite/src/views/Login.vue
- web/satellite/src/views/Signup.vue
What: 
Why:
- Test 1:
- Test 2:
> cherry pick v1.116.1 rc

- satellite/metabase/accounting.go
Avoid creating a separate table that needs to be queried against and instead use COUNTIF, which is similar to the Cockroach implementation.
Change-Id: I6b2b5c7da35f93eef7d14fae64a8002f8ebaad83
What: 
Why:
- Test 1:
- Test 2:
> satellite/metabase: optimize CollectBucketTallies for Spanner

- satellite/metainfo/endpoint_object.go
- satellite/metainfo/endpoint_object_test.go
- web/satellite/src/components/dialogs/SetBucketObjectLockConfigDialog.vue
- web/satellite/src/components/dialogs/defaultBucketLockConfig/SetDefaultObjectLockConfig.vue
Change-Id: I83ad3f1137abf138a3be4147d2ff082070877338
What: 
fix for default retention for inline segments
Why:
- Test 1:
- Test 2:
> cherry pick v1.117.4 

- satellite/durability/config.go
- satellite/durability/observer.go
- satellite/durability/observer_test.go
- satellite/peer.go
- satellite/rangedloop.go
- satellite/satellite-config.yaml.lock
- testsuite/wasm/check-size.sh
> satellite/durability: make the durability ranged-loop classes configurabe

- satellite/satellitedb/migrate.go
This ensures we can start migration on a database that already exists.
Change-Id: Ie5428e3386062c5074cf9f627a22ae1fa5ed6470
What: 
fix for DB migration
Why:
- Test 1:
- Test 2:
> cherry-pick v.118.2-rc

- satellite/satellitedb/migrate.go
What: 
Why:
- Test 1:
- Test 2:
> cherry-pick v.118.3-rc

- testsuite/rolling-upgrade/start-sim.sh
- testsuite/uplink-versions/start-sim.sh
Change-Id: Ief23f675750b86f170a1de23354e2983d414e926
What: 
fix for TMP variable in tag build
Why:
- Test 1:
- Test 2:
> cherry-pick v1.118.5

- satellite/metabase/loop.go
- satellite/metabase/loop_test.go
- satellite/metabase/rangedloop/service_test.go
Change-Id: Id0275d4cca175762d9bb20748e77b1b832c2f604
What: 
Why:
- Test 1:
- Test 2:
> satellite/metabase: fix error handling for spanner segments iterator

- satellite/admin/user.go
- satellite/admin/user_test.go
- web/satellite/src/api/payments.ts
- web/satellite/src/components/BucketsDataTable.vue
- web/satellite/src/components/dialogs/BucketDetailsDialog.vue
- web/satellite/src/components/dialogs/CreateBucketDialog.vue
- web/satellite/src/components/dialogs/SetBucketObjectLockConfigDialog.vue
- web/satellite/src/components/dialogs/defaultBucketLockConfig/SetDefaultObjectLockConfig.vue
- web/satellite/src/types/buckets.ts
- web/satellite/src/types/objectLock.ts
What: 
fix for admin and small UI fixes
Why:
- Test 1:
- Test 2:
> cherry-pick v1.119.1-rc

- cmd/tools/metabase-verify/verify/verify.go
- private/testplanet/satellite.go
- satellite/api.go
- satellite/audit/observer_test.go
- satellite/audit/verifier.go
- satellite/console-api.go
- satellite/gc-bf.go
- satellite/gc/bloomfilter/observer.go
- satellite/gc/bloomfilter/observer_test.go
- satellite/gc/gc_test.go
- satellite/gc/sender/service_test.go
- satellite/metabase/rangedloop/providerdb.go
- satellite/metabase/rangedloop/providerdb_test.go
- satellite/metabase/rangedloop/service.go
- satellite/metabase/rangedloop/service_test.go
- satellite/orders/endpoint.go
- satellite/orders/endpoint_test.go
- satellite/orders/service.go
- satellite/rangedloop.go
- satellite/repair/checker/observer_test.go
- satellite/satellite-config.yaml.lock
What: 
Why:
- Test 1:
- Test 2:
> point release v1.119.3

- satellite/metabase/list_objects.go
- satellite/metabase/list_objects_test.go
While scanning for items we may need to requery for more items, because some items may have been skipped.
Change-Id: Ia9b4285f77e145d1693656ad0e8a5c09ac5ad136
What: 
Why:
- Test 1:
- Test 2:
> satellite/metabase: fix Spanner ListObjects boundary condition

- satellite/metabase/list_objects.go
- satellite/metabase/list_objects_test.go
- satellite/nodeselection/config_test.yaml
What: 
Why:
- Test 1:
- Test 2:
> Fix versioned listing corner case

- satellite/analytics/hubspot.go
- satellite/analytics/service.go
- satellite/console/consoleweb/consoleapi/analytics.go
- web/satellite/src/components/dialogs/CreateBucketDialog.vue
- web/satellite/src/components/dialogs/SetBucketObjectLockConfigDialog.vue
- web/satellite/src/components/dialogs/defaultBucketLockConfig/SetDefaultObjectLockConfig.vue
- web/satellite/src/router/index.ts
- web/satellite/src/store/modules/domainsStore.ts
- web/satellite/src/views/CunoFS.vue
What: 
fixes for the current release candidate
Why:
- Test 1:
- Test 2:
> cherry pick v1.120.3

- cmd/satellite/repair_segment.go
- satellite/accounting/projectusage.go
- satellite/metabase/accounting.go
- satellite/metabase/delete_objects.go
- satellite/metabase/zombiedeletion/chore.go
- satellite/orders/service.go
- satellite/repair/checker/config.go
- satellite/repair/checker/observer.go
- satellite/repair/repairer/segments.go
- satellite/satellite-config.yaml.lock
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.120.7

- cmd/tools/metabase-verify/verify/verify.go
- satellite/audit/observer_test.go
- satellite/gc-bf.go
- satellite/gc/bloomfilter/observer_test.go
- satellite/gc/gc_test.go
- satellite/gc/sender/service_test.go
- satellite/metabase/loop.go
- satellite/metabase/loop_test.go
- satellite/metabase/rangedloop/mud.go
- satellite/metabase/rangedloop/providerdb.go
- satellite/metabase/rangedloop/providerdb_test.go
- satellite/metabase/rangedloop/service.go
- satellite/metabase/rangedloop/service_test.go
- satellite/rangedloop.go
- satellite/repair/checker/observer_test.go
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.122.2

- cmd/tools/piecestore-benchmark/main.go
- storagenode/hashstore/config.go
- storagenode/hashstore/config_test.go
- storagenode/hashstore/db.go
- storagenode/hashstore/db_test.go
- storagenode/hashstore/helpers_test.go
- storagenode/hashstore/store.go
- storagenode/hashstore/store_test.go
- storagenode/mud.go
- storagenode/peer.go
- storagenode/piecemigrate/chore_test.go
- storagenode/piecestore/backend.go
- storagenode/piecestore/backend_test.go
What: 
Why:
- Test 1:
- Test 2:
> cherry-pick v1.122.9

- satellite/admin/user.go
- satellite/analytics/service.go
- satellite/console/accountfreezes.go
- satellite/console/consoleweb/consoleapi/analytics.go
- satellite/console/consoleweb/consoleapi/auth.go
- satellite/console/consoleweb/consoleapi/auth_test.go
- satellite/console/consoleweb/server.go
- satellite/console/observerupgradeuser.go
- satellite/console/service.go
- satellite/console/service_test.go
- satellite/oidc/integration_test.go
- satellite/payments/accountfreeze/chore.go
- satellite/payments/accountfreeze/chore_test.go
- satellite/payments/stripe/service.go
What: 
Why:
- Test 1:
- Test 2:
> release v1.123.1-rc

- satellite/gc-bf.go
- satellite/gc/bloomfilter/config.go
- satellite/gc/bloomfilter/observer.go
- satellite/gc/bloomfilter/observer_sync.go
- satellite/gc/bloomfilter/observer_sync_v2.go
- satellite/gc/bloomfilter/observer_test.go
- satellite/gc/bloomfilter/upload.go
- satellite/gc/gc_test.go
- satellite/satellite-config.yaml.lock
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.123.5

- satellite/gc/bloomfilter/observer_sync_v2.go
- satellite/gc/bloomfilter/observer_sync_v2_test.go
- satellite/metabase/aliaspiece.go
- satellite/metabase/loop.go
- satellite/metabase/loop_test.go
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.123.6

- storagenode/hashstore/tbl.go
Change-Id: I7b212f369bc1b846cfb568d813e844f0723b86be
What: 
fix for storagenode hashstore
Why:
- Test 1:
- Test 2:
> cherry pick v1.124.2

- private/testplanet/satellite.go
- satellite/metabase/adapter_spanner.go
- satellite/metabase/adapter_spanner_test.go
- satellite/metabase/db.go
- satellite/metainfo/config.go
- satellite/satellite-config.yaml.lock
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.124.5

- storagenode/blobstore/statcache/statcache.go
> Point release v1.124.6

- satellite/metabase/adapter.go
- satellite/metabase/adapter_spanner.go
- satellite/metabase/commit.go
- satellite/metabase/commit_object.go
- satellite/metabase/commit_test.go
- satellite/metabase/copy_object.go
- satellite/metabase/delete.go
- satellite/metabase/move_object.go
- satellite/metabase/precommit_test.go
- satellite/metainfo/config.go
- satellite/metainfo/endpoint_object.go
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.126.5

- satellite/jobq/jobqueue/jobqueue.go
- satellite/jobq/jobqueue/jobqueue_test.go
- satellite/payments/stripe/service.go
What: 
Why:
fix invoicing for partner
- Test 1:
- Test 2:
> cherry pick v1.128.4

- satellite/metabase/commit.go
- satellite/metabase/delete.go
- satellite/metabase/delete_batch.go
- satellite/metabase/delete_bucket.go
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.128.5

- satellite/api.go
- satellite/metabase/adapter.go
- satellite/metabase/alias.go
- satellite/metabase/commit.go
- satellite/metabase/commit_object.go
- satellite/metabase/commit_test.go
- satellite/metabase/copy_object.go
- satellite/metabase/delete.go
- satellite/metabase/metadata.go
- satellite/metabase/move_object.go
- satellite/metabase/raw.go
- satellite/metabase/update.go
- satellite/metainfo/config.go
- satellite/metainfo/endpoint.go
- satellite/metainfo/endpoint_segment.go
- satellite/metainfo/mud.go
- satellite/metainfo/node_selection_stats.go
- satellite/nodeselection/config.go
- satellite/nodeselection/config_test.go
- satellite/nodeselection/selector.go
- satellite/nodeselection/selector_test.go
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.128.6

- web/satellite/src/views/Signup.vue
Update the schedule a meeting link in the signup page.
> web/satellite: update business contact link

- satellite/audit/verifier.go
- satellite/metabase/common.go
- satellite/metabase/delete_bucket.go
- satellite/satellitedb/storagenodeaccounting.go
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.30.5

- cmd/satellite/billing.go
- satellite/admin.go
- satellite/api.go
- satellite/console-api.go
- satellite/console/service_test.go
- satellite/core.go
- satellite/payments/paymentsconfig/config.go
- satellite/payments/stripe/accounts.go
- satellite/payments/stripe/accounts_test.go
- satellite/payments/stripe/service.go
- satellite/satellite-config.yaml.lock
What: 
changes allow to delete account with estimated charge < 5$ immediately
Why:
- Test 1:
- Test 2:
> cherry-pick v1.130.8 

- satellite/console/accountfreezes.go
- satellite/console/config.go
- satellite/satellite-config.yaml.lock
What: 
fix panic for satellite core pod and change add funds default value
Why:
- Test 1:
- Test 2:
> cherry pick v1.131.4

- satellite/metabase/adapter.go
- satellite/metabase/check_segments_pieces.go
- satellite/metabase/check_segments_pieces_test.go
- satellite/metainfo/attribution_test.go
- satellite/metainfo/endpoint_bucket.go
- satellite/orders/mock_test.go
- satellite/orders/service.go
- satellite/overlay/mockdb.go
- satellite/overlay/service.go
- satellite/repair/repair_test.go
- satellite/repair/repairer/repairer.go
- satellite/repair/repairer/segments.go
- satellite/repairer.go
- satellite/satellite-config.yaml.lock
- satellite/satellitedb/overlaycache.go
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.132.5

- cmd/satellite/main.go
- cmd/satellite/users.go
- cmd/satellite/users_test.go
- satellite/metabase/delete_bucket.go
- satellite/metabase/delete_bucket_uncoordinated.go
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.132.6

- satellite/accounting/db.go
- satellite/accounting/projectaccounting_test.go
- satellite/api.go
- satellite/console-api.go
- satellite/console/config.go
- satellite/console/consoleweb/config.go
- satellite/console/consoleweb/consoleapi/usagelimits_test.go
- satellite/console/consoleweb/server.go
- satellite/console/service.go
- satellite/console/service_test.go
- satellite/payments/account.go
- satellite/payments/stripe/accounts.go
- satellite/payments/stripe/service.go
- satellite/payments/stripe/service_test.go
- satellite/satellite-config.yaml.lock
- satellite/satellitedb/projectaccounting.go
- web/satellite/src/types/config.gen.ts
What: 
fix for invoices
Why:
- Test 1:
- Test 2:
> cherry pick v1.132.7

- cmd/multinode/Dockerfile
- cmd/satellite/Dockerfile
- cmd/storagenode/Dockerfile.dev
- cmd/uplink/Dockerfile
- cmd/versioncontrol/Dockerfile
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.132.9

- testsuite/playwright-ui/tests/objectBrowser.test.ts
- web/satellite/src/components/billing/pricingPlans/PricingPlanContainer.vue
- web/satellite/src/components/dialogs/accountSetupSteps/AccountTypeStep.vue
- web/satellite/src/store/modules/billingStore.ts
- web/satellite/src/store/modules/objectBrowserStore.ts
What: 
Why:
- Test 1:
- Test 2:
> cherry pick v1.134.1

- satellite/audit/observer.go
- satellite/audit/observer_test.go
- satellite/audit/reservoir.go
- satellite/audit/reservoir_test.go
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.134.4

- satellite/metabase/delete.go
- satellite/metabase/delete_test.go
What: 
Why:
- Test 1:
- Test 2:
> Point release v.135.6

- satellite/metainfo/config.go
- satellite/metainfo/endpoint.go
- satellite/metainfo/endpoint_object.go
- satellite/metainfo/endpoint_object_test.go
- satellite/metainfo/validation.go
- satellite/satellite-config.yaml.lock
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.136.4

- satellite/metabase/commit.go
- satellite/metabase/commit_test.go
- satellite/metainfo/config.go
- satellite/metainfo/success_tracker_monitor.go
- satellite/metainfo/success_tracker_monitor_test.go
What: 
Why:
- Test 1:
- Test 2:
> Point release v1.136.5

- satellite/accounting/db.go
- satellite/console/consoleweb/consoleapi/usagelimits_test.go
- satellite/console/service.go
- satellite/nodeselection/config.go
- satellite/nodeselection/config_test.go
- satellite/nodeselection/config_test.yaml
- satellite/nodeselection/selector_download.go
- satellite/nodeselection/selector_download_test.go
Issue: https://github.com/storj/storj-private/issues/1557
Change-Id: I34fd69b1a7bb4178de36daf52024ad1b69e06996
What: 
fix for Detailed report
Why:
- Test 1:
- Test 2:
> cherry-pick v1.139.3
